#!/usr/bin/env python3
# Batch 6 sequences — part 2: physics GCSE, IBDP, KS3
import importlib.util, os
spec = importlib.util.spec_from_file_location('p1', os.path.join(os.path.dirname(__file__), 'apply_b6_p1.py'))
p1 = importlib.util.module_from_spec(spec); spec.loader.exec_module(p1)
G = 'physics-gcse-'
I = 'physics-ibdp-'
K = 'physics-ks3-'
SEQ = {
G+'aqa-atomic-structure-adventure-1': [
 ("Dalton's atom (1803)","Tiny solid spheres that cannot be divided"),
 ("Plum pudding model (1897)","Thomson finds the electron inside a positive ball"),
 ("Nuclear model (1911)","Rutherford's alpha scattering reveals the nucleus"),
 ("Bohr's energy levels (1913)","Electrons orbit at fixed distances"),
 ("Neutron discovered (1932)","Chadwick completes the modern picture"),
],
G+'aqa-magnetism-electromagnetism-adventure-1': [
 ("Current flows in the coil","The supply pushes charge through the loop"),
 ("Motor effect force appears","Field exerts a force on each current-carrying side"),
 ("Opposite sides pushed opposite ways","Currents run in opposite directions, so a turning effect"),
 ("Coil rotates half a turn","The turning effect spins the coil"),
 ("Commutator swaps the current","Split ring reverses the direction every half turn"),
 ("Rotation continues smoothly","Force always turns the coil the same way"),
],
G+'aqa-particle-model-of-matter-adventure-1': [
 ("Ice below 0 °C warms up","Energy raises the temperature of the solid"),
 ("Ice melts at 0 °C","Temperature stays constant; latent heat of fusion"),
 ("Water warms to 100 °C","Specific heat capacity 4200 J/kg°C"),
 ("Water boils at 100 °C","Temperature constant; latent heat of vaporisation"),
 ("Steam keeps heating","Energy raises the gas temperature again"),
],
G+'aqa-space-physics-adventure-1': [
 ("Nebula","A cloud of dust and gas pulled together by gravity"),
 ("Protostar","Collapsing core heats until fusion can start"),
 ("Main sequence star","Hydrogen fusion balances gravity — the Sun today"),
 ("Red giant","Star expands when core hydrogen runs low"),
 ("White dwarf","Outer layers lost; hot dense core remains"),
 ("Black dwarf","The cooled, dark remnant — the final stage"),
],
G+'cambridge-igcse-electricity-magnetism-adventure-1': [
 ("Power station generates","The generator produces alternating current"),
 ("Step-up transformer","Voltage raised to about 400,000 V, lowering current"),
 ("Transmission lines","High voltage cuts I²R heating losses in cables"),
 ("Step-down transformer","Substation lowers the voltage for safe use"),
 ("Homes receive mains","Supplied at 230 V in the UK"),
],
G+'cambridge-igcse-motion-forces-energy-adventure-1': [
 ("Hazard appears","The driver sees an obstacle ahead"),
 ("Reaction time elapses","Car covers the thinking distance before any braking"),
 ("Brakes applied","Friction force acts at the wheels"),
 ("Braking distance covered","Kinetic energy transfers to thermal in the brakes"),
 ("Car stops","Stopping distance = thinking + braking distance"),
],
G+'cambridge-igcse-nuclear-physics-adventure-1': [
 ("Alpha particles fired at gold foil","Geiger and Marsden's experiment begins"),
 ("Most pass straight through","The atom is mostly empty space"),
 ("Some deflect slightly","A concentrated positive charge repels them"),
 ("A few bounce almost back","Roughly 1 in 8000 return toward the source"),
 ("Nuclear model proposed (1911)","Rutherford: a tiny, dense, positive nucleus"),
],
G+'cambridge-igcse-space-physics-adventure-1': [
 ("The Moon","About 3,500 km across"),
 ("The Earth","About 12,700 km across"),
 ("The Sun","About 1.4 million km across"),
 ("The Solar System","Billions of kilometres across"),
 ("The Milky Way","About 100,000 light-years across"),
 ("The Universe","Observable part spans tens of billions of light-years"),
],
G+'cambridge-igcse-thermal-physics-adventure-1': [
 ("Air above the heater warms","Particles gain energy and move faster"),
 ("Warm air expands","Same mass fills a larger volume, so density falls"),
 ("Warm air rises","Less dense air floats above cooler air"),
 ("Cool air flows in below","Denser air sinks and takes its place"),
 ("Convection current circulates","The cycle repeats, carrying energy round the room"),
],
G+'ccea-atomic-nuclear-physics-adventure-1': [
 ("Solid sphere model (1803)","Dalton: atoms are indivisible balls"),
 ("Plum pudding model (1897)","Electrons dotted through a positive sphere"),
 ("Rutherford's nucleus (1911)","Alpha scattering shows a tiny dense centre"),
 ("Bohr's orbits (1913)","Electrons at set energy levels"),
 ("Chadwick's neutron (1932)","Neutral particle found in the nucleus"),
],
G+'ccea-density-pressure-adventure-1': [
 ("Air","Density about 1.2 kg/m³"),
 ("Olive oil","About 920 kg/m³ — floats on water"),
 ("Water","1000 kg/m³"),
 ("Aluminium","About 2700 kg/m³"),
 ("Iron","About 7900 kg/m³"),
 ("Gold","About 19,300 kg/m³"),
],
G+'ccea-magnetism-electromagnetism-adventure-1': [
 ("Switch pressed","Circuit completes and current flows in the coil"),
 ("Electromagnet switches on","Coil with iron core becomes magnetic"),
 ("Armature attracted","The iron arm is pulled toward the electromagnet"),
 ("Hammer strikes the gong","The moving arm rings the bell"),
 ("Contact breaks the circuit","Movement separates the contacts; current stops"),
 ("Armature springs back","Field collapses; contact remakes and the cycle repeats"),
],
G+'ccea-space-physics-adventure-1': [
 ("Big Bang","The Universe begins 13.8 billion years ago"),
 ("CMB released","380,000 years later; seen today as microwaves"),
 ("First stars form","A few hundred million years after the Big Bang"),
 ("Sun forms","4.6 billion years ago from a nebula"),
 ("Earth forms","About 4.5 billion years ago"),
 ("Present day","Redshift shows galaxies still receding"),
],
G+'domestic-electricity--power-adventure-1': [
 ("Fault develops","The live wire touches the metal case"),
 ("Earth wire carries current","Low-resistance path from the case to the ground"),
 ("Large current surges","Far above the appliance's normal current"),
 ("Fuse wire melts","Current above its rating breaks the thin wire"),
 ("Circuit disconnected","Live supply cut off; the case is safe to touch"),
],
G+'edexcel-astronomy-adventure-1': [
 ("Nebula","Gravity gathers a giant cloud of gas and dust"),
 ("Protostar","The collapsing cloud heats up"),
 ("Main sequence star","Stable hydrogen fusion for millions of years"),
 ("Red supergiant","A massive star swells enormously"),
 ("Supernova","The star explodes, scattering heavy elements"),
 ("Black hole","The most massive cores collapse completely"),
],
G+'edexcel-conservation-of-energy-adventure-1': [
 ("Motor lifts the car","Work done fills the gravitational store"),
 ("Pause at the summit","Maximum gravitational potential energy, minimum speed"),
 ("Descent","Gravitational store empties into the kinetic store"),
 ("Bottom of the dip","Maximum kinetic energy and top speed"),
 ("Climb up the next hill","Kinetic transfers back to gravitational; some dissipates"),
 ("Each crest is lower","Friction has moved energy to thermal stores"),
],
G+'edexcel-electricity-circuits-adventure-1': [
 ("Set up the circuit","Component, ammeter and cell in series; voltmeter across it"),
 ("Adjust the variable resistor","Change the pd across the component"),
 ("Record I and V pairs","Take readings over the whole range"),
 ("Reverse the connections","Collect negative values too"),
 ("Plot the I-V graph","Shape reveals resistor, lamp or diode behaviour"),
 ("Interpret the resistance","Use R = V/I at points on the curve"),
],
G+'edexcel-electromagnetic-induction-adventure-1': [
 ("Coil rotated in the field","A turbine or crank does work on the coil"),
 ("Field through the coil changes","The wires cut magnetic field lines"),
 ("Voltage induced","A pd appears across the coil ends"),
 ("Current flows in the circuit","The induced pd drives charge through the load"),
 ("Direction reverses each half turn","The output is alternating current"),
],
G+'edexcel-forces-matter-adventure-1': [
 ("Hang the spring","Clamp it with a ruler alongside"),
 ("Measure the natural length","Unstretched length recorded first"),
 ("Add weights one at a time","Known force added in equal steps"),
 ("Record each extension","New length minus natural length"),
 ("Plot force against extension","Straight line through the origin while elastic"),
 ("Gradient gives the spring constant","k = F/x in the linear region"),
],
G+'edexcel-igcse-astrophysics-adventure-1': [
 ("Nebula","A cloud of gas and dust contracts under gravity"),
 ("Protostar","Core temperature climbs toward fusion"),
 ("Main sequence star","Hydrogen fuses steadily to helium"),
 ("Red giant","The Sun's fate when core hydrogen runs out"),
 ("Planetary nebula","Outer layers are shed into space"),
 ("White dwarf","Hot, dense remnant core remains"),
],
G+'edexcel-igcse-energy-resources-energy-transfers-adventure-1': [
 ("Chemical store of the fuel","Energy held in coal, oil or gas"),
 ("Combustion","Burning fills the thermal store of the boiler"),
 ("Steam spins the turbine","Thermal store transfers to kinetic"),
 ("Generator rotates","Kinetic store transferred electrically"),
 ("Step-up transformer","Electricity sent out at high voltage"),
 ("Energy reaches homes","Useful output plus dissipated waste heat"),
],
G+'edexcel-igcse-forces-motion-adventure-1': [
 ("Skydiver jumps","Only weight acts at first; acceleration is about 10 m/s²"),
 ("Speed rises, drag rises","Air resistance grows with speed"),
 ("Terminal velocity reached","Drag balances weight; speed stays constant"),
 ("Parachute opens","Larger area means drag now beats weight"),
 ("Skydiver slows down","Resultant force acts upward while falling"),
 ("New lower terminal velocity","Forces balance again for a safe landing"),
],
G+'edexcel-igcse-magnetism-electromagnetism-adventure-1': [
 ("Generator at the power station","Produces alternating current"),
 ("Step-up transformer","More secondary turns raise the voltage"),
 ("National grid pylons","High voltage, low current cuts heating losses"),
 ("Step-down transformer","Fewer secondary turns lower the voltage"),
 ("Mains sockets at home","A safe 230 V supply"),
],
G+'edexcel-igcse-radioactivity-particles-adventure-1': [
 ("Alpha source aimed at gold foil","A thin metal target in a vacuum"),
 ("Most alphas pass through","Atoms are mostly empty space"),
 ("Some are deflected","Repelled by concentrated positive charge"),
 ("A tiny fraction rebound","Evidence of a small massive centre"),
 ("Nuclear atom accepted","Mass and positive charge sit in a tiny nucleus"),
],
G+'edexcel-igcse-solids-liquids-gases-adventure-1': [
 ("Heat the solid","Particle vibrations grow; temperature rises"),
 ("Melting point reached","Temperature pauses while bonds loosen"),
 ("Liquid heats up","Particles move faster and further apart"),
 ("Boiling point reached","Temperature pauses while particles escape the liquid"),
 ("Gas heats further","Particle speed and pressure keep rising"),
],
G+'edexcel-key-concepts-of-physics-adventure-1': [
 ("nano (n)","One billionth: 10⁻⁹"),
 ("micro (μ)","One millionth: 10⁻⁶"),
 ("milli (m)","One thousandth: 10⁻³"),
 ("centi (c)","One hundredth: 10⁻²"),
 ("kilo (k)","One thousand: 10³"),
 ("mega (M)","One million: 10⁶"),
],
G+'edexcel-light-the-electromagnetic-spectrum-adventure-1': [
 ("Radio waves","Longest wavelength, lowest frequency"),
 ("Microwaves","Used for ovens and satellite links"),
 ("Infrared","Thermal radiation from warm objects"),
 ("Visible light","The only part our eyes detect"),
 ("Ultraviolet","Beyond violet; causes sunburn"),
 ("X-rays","Very high frequency; image bones"),
],
G+'edexcel-magnetism-the-motor-effect-adventure-1': [
 ("Connect the supply","Current flows through the coil in the field"),
 ("Force on each side","Fleming's left-hand rule gives the direction"),
 ("Turning effect produced","Opposite sides are pushed opposite ways"),
 ("Half-turn completed","The coil reaches the vertical position"),
 ("Split-ring swaps the current","Force direction stays the same"),
 ("Continuous spinning","The motor turns steadily"),
],
G+'edexcel-motion-forces-adventure-1': [
 ("Driver spots the hazard","The clock starts on stopping distance"),
 ("Thinking distance travelled","Typical reaction time 0.2–0.9 s at full speed"),
 ("Brakes are applied","Friction acts between brakes and wheels"),
 ("Braking distance travelled","Kinetic energy becomes thermal energy"),
 ("Vehicle at rest","Total stop = thinking + braking distance"),
],
G+'edexcel-particle-model-adventure-1': [
 ("Solid","Fixed lattice; particles only vibrate — least energy"),
 ("Melting","Energy at the melting point loosens the structure"),
 ("Liquid","Particles slide past each other; more energy"),
 ("Boiling","Latent heat fully separates the particles"),
 ("Gas","Fast, far-apart particles — greatest energy"),
],
G+'edexcel-radioactivity-adventure-1': [
 ("Start: activity 800 Bq","A fresh sample of unstable nuclei"),
 ("After 1 half-life: 400 Bq","Half of the unstable nuclei have decayed"),
 ("After 2 half-lives: 200 Bq","A quarter of the original remain"),
 ("After 3 half-lives: 100 Bq","One eighth remain"),
 ("After 4 half-lives: 50 Bq","One sixteenth remain"),
],
G+'electricity-adventure-1': [
 ("Connect the test wire","Crocodile clips set a length along a metre ruler"),
 ("Start with a short length","Begin at 10 cm between the clips"),
 ("Record current and voltage","Calculate R = V/I for that length"),
 ("Increase the length in steps","Repeat the readings every 10 cm"),
 ("Plot resistance against length","A straight line through the origin appears"),
 ("Conclude proportionality","Doubling the length doubles the resistance"),
],
G+'electromagnetic-spectrum-adventure-1': [
 ("Radio waves","Lowest frequency in the EM family"),
 ("Microwaves","Higher frequency than radio"),
 ("Infrared","Below visible; emitted by warm objects"),
 ("Visible light","Red through violet"),
 ("Ultraviolet","Above visible in frequency"),
 ("Gamma rays","Highest frequency, most dangerous"),
],
G+'energy-adventure-1': [
 ("Ball held above the ground","The gravitational store is full"),
 ("Released and falling","Gravitational store transfers to kinetic store"),
 ("Fastest just before impact","Kinetic store at its maximum"),
 ("Impact with the ground","Some energy moves to thermal and sound"),
 ("Rebounds to a lower height","Less energy left in the gravitational store"),
],
G+'forces-adventure-1': [
 ("Car sets off","Driving force far exceeds resistance; large acceleration"),
 ("Speed builds","Air resistance grows with speed"),
 ("Resultant force shrinks","Acceleration drops although speed still rises"),
 ("Forces balance","Driving force equals total drag"),
 ("Top speed reached","Zero resultant force — constant velocity (1st law)"),
],
G+'light-adventure-1': [
 ("Light leaves the object","Rays travel out in straight lines"),
 ("Rays strike the mirror","Angle of incidence measured from the normal"),
 ("Reflection occurs","Angle of reflection equals angle of incidence"),
 ("Rays enter the eye","Reflected light reaches the retina"),
 ("Brain perceives the image","A virtual image appears behind the mirror"),
],
G+'magnetism-adventure-1': [
 ("Place the magnet on paper","Draw around it; label the N and S poles"),
 ("Compass beside the north pole","The needle lines up with the field"),
 ("Mark the needle's direction","Pencil dot at the compass tip"),
 ("Step the compass along","Tail on the last dot, then mark again"),
 ("Join the dots","A smooth line from N pole to S pole"),
 ("Repeat for more lines","Closer lines show a stronger field"),
],
G+'motion-adventure-1': [
 ("Walking","Typical speed about 1.5 m/s"),
 ("Cycling","About 6 m/s"),
 ("Car on a motorway","About 31 m/s (70 mph)"),
 ("Passenger jet","About 250 m/s"),
 ("Sound in air","About 330 m/s"),
 ("Light","3 × 10⁸ m/s"),
],
G+'newtons-laws-of-motion-adventure-1': [
 ("Engines ignite","Exhaust gas is forced downward at high speed"),
 ("Reaction thrust upward","Third law: the gas pushes the rocket up equally"),
 ("Lift-off","Thrust exceeds weight, giving a resultant force"),
 ("Acceleration grows","Second law: a = F/m, and m falls as fuel burns"),
 ("Engines cut off in space","No resultant force remains"),
 ("Coasting at constant velocity","First law: motion continues unchanged"),
],
G+'ocr-electricity-magnetism-adventure-1': [
 ("Generating station","Alternator produces AC"),
 ("Step-up transformer","Voltage raised for transmission"),
 ("High-voltage grid lines","Low current means little energy wasted as heat"),
 ("Local step-down transformer","Voltage reduced near the consumer"),
 ("230 V at the socket","Safe mains supply delivered"),
],
G+'ocr-global-challenges-adventure-1': [
 ("Hazard seen","Stopping sequence begins"),
 ("Reaction time passes","Thinking distance covered at constant speed"),
 ("Brakes engage","Friction force begins to act"),
 ("Kinetic energy dissipated","Work done by brakes becomes thermal energy"),
 ("Vehicle stationary","Thinking plus braking distance equals stopping distance"),
],
G+'ocr-matter-adventure-1': [
 ("Measure the mass","Irregular object on a digital balance"),
 ("Fill the eureka can","Water up to the spout; beaker beneath"),
 ("Lower the object in","Fully submerge it gently"),
 ("Collect the displaced water","Its volume equals the object's volume"),
 ("Read the volume","Use a measuring cylinder"),
 ("Calculate density","ρ = m/V"),
],
G+'ocr-practical-skills-adventure-1': [
 ("Choose the variables","Independent, dependent and controls identified"),
 ("Write the method","Equipment list and risk assessment"),
 ("Collect readings","Repeats taken across a sensible range"),
 ("Average the results","Means found; anomalies excluded"),
 ("Draw the graph","Best-fit line through the plotted points"),
 ("Conclude and evaluate","Relationship stated with its uncertainty"),
],
G+'ocr-waves-radioactivity-adventure-1': [
 ("Measure the distance to a wall","Record d, for example 50 m"),
 ("Make a loud clap","A sound wave sets off toward the wall"),
 ("The wave reflects","An echo returns"),
 ("Time the echo","Stopwatch measures the round trip t"),
 ("Calculate the speed","v = 2d/t — there and back"),
],
G+'radioactive-decay-adventure-1': [
 ("Fresh sample: 100%","All the original unstable nuclei present"),
 ("After 1 half-life: 50%","Half have decayed into new nuclei"),
 ("After 2 half-lives: 25%","Half of the remainder decayed again"),
 ("After 3 half-lives: 12.5%","One eighth remain"),
 ("After 4 half-lives: 6.25%","One sixteenth remain"),
],
G+'specific-heat-capacity-adventure-1': [
 ("Lead","c about 130 J/kg°C — warms very easily"),
 ("Copper","c about 385 J/kg°C"),
 ("Aluminium","c about 900 J/kg°C"),
 ("Ice","c about 2100 J/kg°C"),
 ("Water","c = 4200 J/kg°C — superb at storing heat"),
],
G+'waves-adventure-1': [
 ("Source vibrates","A drum skin moves back and forth"),
 ("Air is squashed and stretched","Compressions and rarefactions form"),
 ("Wave travels outward","About 330 m/s through the air"),
 ("Eardrum vibrates","It oscillates at the wave's frequency"),
 ("Signal reaches the brain","Tiny bones and nerves turn vibration into hearing"),
],
I+'astrophysics-option-adventure-1': [
 ("Astronomical unit","1.5 × 10¹¹ m, Earth to Sun"),
 ("Light-year","9.46 × 10¹⁵ m"),
 ("Parsec","3.26 light-years"),
 ("Proxima Centauri","Nearest star, about 1.3 pc away"),
 ("Milky Way diameter","About 30 kpc"),
 ("Andromeda galaxy","About 770 kpc away"),
],
I+'atomic-nuclear--particle-physics-adventure-1': [
 ("Thomson's electron (1897)","First subatomic particle discovered"),
 ("Rutherford's nucleus (1911)","Alpha scattering reveals the nuclear atom"),
 ("Bohr's energy levels (1913)","Explains hydrogen's emission spectrum"),
 ("Chadwick's neutron (1932)","Neutral nucleon found"),
 ("Quark model (1964)","Gell-Mann organises the hadrons"),
],
I+'circular-motion--gravitation-adventure-1': [
 ("Low Earth orbit","ISS at roughly 400 km altitude"),
 ("GPS constellation","About 20,200 km up"),
 ("Geostationary orbit","35,786 km; period exactly one day"),
 ("Moon's orbit","384,000 km from Earth"),
 ("Earth's orbit of the Sun","1 AU, about 1.5 × 10¹¹ m"),
],
I+'electricity--magnetism-adventure-1': [
 ("Cell provides an emf","Chemical energy sets up a potential difference"),
 ("Field acts along the wire","Free electrons feel an electric force"),
 ("Electrons drift","Slow net motion on top of random thermal motion"),
 ("Current is established","I = nAvq everywhere in the series loop"),
 ("Collisions heat the lattice","Energy dissipates — the origin of resistance"),
],
I+'energy-production-adventure-1': [
 ("Fission in the reactor core","U-235 releases about 200 MeV per split"),
 ("Coolant carries thermal energy","Heated fluid leaves the core"),
 ("Heat exchanger raises steam","Thermal energy boils high-pressure water"),
 ("Steam spins the turbine","Thermal becomes kinetic energy"),
 ("Generator induces an emf","Kinetic becomes electrical energy"),
 ("Grid transmission","Step-up transformer sends power out"),
],
I+'hl-electromagnetic-induction-adventure-1': [
 ("Coil driven round in the field","External torque does work on the coil"),
 ("Flux linkage changes","NΦ varies sinusoidally with rotation"),
 ("EMF induced","Faraday: ε = −N dΦ/dt"),
 ("Lenz's law sets the direction","Induced current opposes the change causing it"),
 ("AC delivered to the load","The emf reverses every half-turn"),
],
I+'hl-fields-adventure-1': [
 ("Moon","Escape speed about 2.4 km/s"),
 ("Mars","About 5.0 km/s"),
 ("Earth","11.2 km/s"),
 ("Jupiter","About 59.5 km/s"),
 ("Sun","About 618 km/s"),
],
I+'hl-quantum-nuclear-physics-adventure-1': [
 ("Planck's quanta (1900)","Radiation emitted in packets E = hf"),
 ("Einstein's photon (1905)","Photoelectric effect explained"),
 ("Bohr model (1913)","Quantised orbits for hydrogen"),
 ("de Broglie hypothesis (1924)","Matter has wavelength λ = h/p"),
 ("Schrödinger equation (1926)","Wavefunctions describe the atom"),
 ("Uncertainty principle (1927)","Heisenberg limits Δx·Δp"),
],
I+'hl-wave-phenomena-adventure-1': [
 ("Laser lights the double slit","One coherent, monochromatic source"),
 ("Diffraction at each slit","Wavefronts spread and overlap"),
 ("Waves superpose","Displacements add where they meet"),
 ("Path difference decides","nλ constructive; (n+½)λ destructive"),
 ("Fringes appear","Bright and dark bands on the screen"),
 ("Spacing gives wavelength","s = λD/d rearranged for λ"),
],
I+'measurements--uncertainties-adventure-1': [
 ("femto (f)","10⁻¹⁵"),
 ("pico (p)","10⁻¹²"),
 ("nano (n)","10⁻⁹"),
 ("milli (m)","10⁻³"),
 ("kilo (k)","10³"),
 ("giga (G)","10⁹"),
],
I+'mechanics-adventure-1': [
 ("Launch at an angle","Initial velocity split into components"),
 ("Climb: vertical speed decreases","Gravity acts downward at 9.8 m/s²"),
 ("Highest point","Vertical velocity zero; horizontal unchanged"),
 ("Descent: vertical speed grows","Symmetric to the climb"),
 ("Impact at launch height","Flight time twice the time to the apex"),
],
I+'quantum--nuclear-physics-hl-adventure-1': [
 ("Photon hits the surface","A quantum of energy hf arrives"),
 ("One electron absorbs it all","One photon frees at most one electron"),
 ("Work function Φ paid","The escape cost from the metal"),
 ("Photoelectron leaves","E_max = hf − Φ"),
 ("Stopping voltage measured","eVₛ = E_max verifies Einstein's equation"),
],
I+'thermal-physics-adventure-1': [
 ("Absolute zero","0 K — minimum internal energy"),
 ("Nitrogen boils","77 K"),
 ("Ice melts","273 K"),
 ("Human body temperature","310 K (37 °C)"),
 ("Water boils","373 K"),
 ("Sun's photosphere","About 5800 K"),
],
I+'waves-adventure-1': [
 ("Radio","Lowest frequency EM radiation"),
 ("Microwave","Above radio in frequency"),
 ("Infrared","Just below the visible band"),
 ("Visible","About 4–7.5 × 10¹⁴ Hz"),
 ("Ultraviolet","Just above the visible band"),
 ("Gamma","Highest frequencies of all"),
],
K+'earth--space-adventure-1': [
 ("The Moon","About 3,500 km across"),
 ("The Earth","About 12,700 km across"),
 ("Jupiter","About 140,000 km across — the biggest planet"),
 ("The Sun","About 1.4 million km across"),
 ("The Solar System","The Sun and everything orbiting it"),
 ("The Milky Way","Billions of stars including our Sun"),
],
K+'electricity--magnetism-adventure-1': [
 ("Close the switch","The circuit loop is complete"),
 ("The cell pushes charges","Its voltage drives the current"),
 ("Current flows round the loop","The same current everywhere in series"),
 ("The bulb filament heats up","Current transfers energy in the bulb"),
 ("Light shines out","Energy leaves by light and heating"),
],
K+'energy-adventure-1': [
 ("Sun radiates light","Energy travels to Earth by radiation"),
 ("Plants photosynthesise","Energy stored chemically in food"),
 ("You eat the food","A chemical store now in your body"),
 ("Muscles work as you run","Chemical store transfers to kinetic store"),
 ("Surroundings warm slightly","Energy dissipates into thermal stores"),
],
K+'energy-stores--transfers-adventure-1': [
 ("Stretch the elastic band","Work done fills the elastic store"),
 ("Release!","Elastic store empties into the ball's kinetic store"),
 ("The ball climbs","Kinetic store transfers to gravitational store"),
 ("Top of the flight","Gravitational store full; slowest point"),
 ("The ball falls back","Gravitational store returns to kinetic"),
 ("It lands","Energy spreads to thermal and sound stores"),
],
K+'forces--motion-adventure-1': [
 ("Skydiver leaps out","Weight pulls down; hardly any air resistance yet"),
 ("Falling faster and faster","Air resistance grows with speed"),
 ("Forces become balanced","Terminal velocity — steady top speed"),
 ("Parachute opens","Huge air resistance now beats weight"),
 ("The fall slows right down","Unbalanced force acts upward"),
 ("Gentle, steady landing speed","Forces balance again, much slower"),
],
K+'heat-transfer-adventure-1': [
 ("Radiator warms nearby air","Particles gain energy and spread out"),
 ("Warm air becomes less dense","The same mass takes up more space"),
 ("Warm air rises","It floats above the cooler air"),
 ("Cool air sinks and moves in","Denser air replaces the rising air"),
 ("The cycle repeats","A convection current heats the whole room"),
],
K+'light-adventure-1': [
 ("A light source shines","Luminous objects give out their own light"),
 ("Light hits the object","It travels there in straight lines"),
 ("The object reflects the light","Non-luminous things only scatter light"),
 ("Light enters your eye","Some reflected rays pass through the pupil"),
 ("The retina detects it","Light-sensitive cells at the back of the eye"),
 ("Your brain builds the picture","Signals travel along the optic nerve"),
],
K+'magnets--electromagnets-adventure-1': [
 ("Coil wire around an iron nail","Many neat turns of insulated wire"),
 ("Connect the coil to a cell","Complete the circuit with a switch"),
 ("Switch on — current flows","The coil now produces a magnetic field"),
 ("The nail becomes a magnet","The iron core makes the field much stronger"),
 ("Test it on paperclips","It attracts magnetic materials"),
 ("Switch off — magnetism gone","Unlike a bar magnet, it can be turned off"),
],
K+'pressure--density-adventure-1': [
 ("Air","About 1.2 kg/m³"),
 ("Ice","About 920 kg/m³ — that's why it floats"),
 ("Water","1000 kg/m³"),
 ("Concrete","About 2400 kg/m³"),
 ("Steel","About 7800 kg/m³"),
 ("Gold","About 19,300 kg/m³"),
],
K+'speed-distance--time-adventure-1': [
 ("Walking","About 1.5 m/s"),
 ("Sprinting","A top athlete reaches about 10 m/s"),
 ("Motorway car","About 30 m/s"),
 ("Jet airliner","About 250 m/s"),
 ("Sound in air","About 330 m/s"),
 ("Light","300,000,000 m/s — nothing is faster"),
],
K+'waves--sound-adventure-1': [
 ("Something vibrates","A guitar string or drum skin moves to and fro"),
 ("Air particles pass it on","Squashed and stretched regions travel outward"),
 ("The sound wave spreads","Moving at about 330 m/s in air"),
 ("Your eardrum vibrates","It copies the wave's frequency"),
 ("You hear the sound","Tiny ear bones and nerves alert the brain"),
],
}
if __name__ == '__main__':
    p1.apply(SEQ)
