#!/usr/bin/env python3
# Batch 6 sequences — part 1: physics A-level
import json, os
ROOT = os.path.join(os.path.dirname(__file__), '..', 'adventures', '_specs')
P = 'physics-a-level-'
SEQ = {
P+'aqa-electricity-adventure-1': [
 ("Build the test circuit","Component in series with ammeter and battery; voltmeter in parallel across it"),
 ("Vary the potential difference","Adjust the variable resistor to change V across the component"),
 ("Record paired readings","Note current I and pd V at each setting; repeat and average"),
 ("Plot the I-V graph","Current against potential difference for the component"),
 ("Examine the line's shape","Ohmic conductor: straight line through the origin"),
 ("Calculate resistance","R = V/I at any point on the characteristic"),
],
P+'aqa-fields-their-consequences-adventure-1': [
 ("Moon","Surface gravitational field strength about 1.6 N/kg"),
 ("Mars","Surface g about 3.7 N/kg"),
 ("Earth","Surface g about 9.8 N/kg"),
 ("Neptune","Surface g about 11.2 N/kg"),
 ("Jupiter","Surface g about 24.8 N/kg"),
 ("Sun","Surface g about 274 N/kg"),
],
P+'aqa-further-mechanics-thermal-physics-adventure-1': [
 ("Ice warms below 0 °C","Energy raises the solid's temperature; Q = mcΔT"),
 ("Melting at 0 °C","Temperature constant; latent heat of fusion breaks bonds"),
 ("Water warms 0–100 °C","Liquid temperature rises; c ≈ 4200 J kg⁻¹ K⁻¹"),
 ("Boiling at 100 °C","Temperature constant; latent heat of vaporisation absorbed"),
 ("Steam warms above 100 °C","Energy now raises the temperature of the gas"),
],
P+'aqa-measurements-errors-adventure-1': [
 ("pico (p)","Prefix meaning 10⁻¹²"),
 ("nano (n)","Prefix meaning 10⁻⁹"),
 ("micro (μ)","Prefix meaning 10⁻⁶"),
 ("milli (m)","Prefix meaning 10⁻³"),
 ("kilo (k)","Prefix meaning 10³"),
 ("mega (M)","Prefix meaning 10⁶"),
],
P+'aqa-mechanics-materials-adventure-1': [
 ("Limit of proportionality","Last point where stress is proportional to strain (Hooke's law)"),
 ("Elastic limit","Beyond this the material no longer returns to its original length"),
 ("Yield point","Material suddenly extends with little extra stress"),
 ("Plastic deformation","Permanent extension as planes of atoms slide"),
 ("Ultimate tensile stress","Maximum stress the material can withstand"),
 ("Fracture","The material breaks; the curve ends"),
],
P+'aqa-nuclear-physics-adventure-1': [
 ("Dalton's solid sphere (1803)","Atoms pictured as tiny indivisible balls"),
 ("Thomson's plum pudding (1897)","Electron discovered; negative charges in positive dough"),
 ("Rutherford's nuclear model (1911)","Alpha scattering reveals a tiny dense nucleus"),
 ("Bohr's orbits (1913)","Electrons occupy fixed energy levels"),
 ("Chadwick finds the neutron (1932)","Completes the proton-neutron nuclear model"),
],
P+'aqa-particles-radiation-adventure-1': [
 ("Electron","Rest energy 0.511 MeV — lightest charged lepton"),
 ("Muon","Rest energy 105.7 MeV; a heavier lepton"),
 ("Charged pion","Rest energy 139.6 MeV; lightest meson"),
 ("Charged kaon","Rest energy 493.7 MeV; a strange meson"),
 ("Proton","Rest energy 938.3 MeV; lightest baryon"),
 ("Neutron","Rest energy 939.6 MeV; just heavier than the proton"),
],
P+'aqa-waves-adventure-1': [
 ("Radio waves","Lowest frequency, longest wavelength (>10 cm)"),
 ("Microwaves","Frequency above radio; cm-scale wavelengths"),
 ("Infrared","Higher frequency than microwaves; felt as heat"),
 ("Visible light","Roughly 400–700 nm wavelengths"),
 ("Ultraviolet","Higher frequency than violet light"),
 ("X-rays","Among the highest frequencies, ~10¹⁸ Hz"),
],
P+'astrophysics-adventure-1': [
 ("Nebula","Cloud of gas and dust contracts under gravity"),
 ("Protostar","Core heats as it collapses; fusion not yet started"),
 ("Main sequence star","Hydrogen fuses to helium in stable equilibrium"),
 ("Red supergiant","Massive star swells after core hydrogen runs out"),
 ("Supernova","Core collapse blasts outer layers into space"),
 ("Neutron star or black hole","Remnant left by the collapsed core"),
],
P+'capacitance--capacitors-adventure-1': [
 ("Capacitor connected to supply","Switch closes; emf starts to drive electrons round"),
 ("Charging current flows","Electrons pile onto one plate and leave the other"),
 ("Charge and pd build up","Q rises and V = Q/C grows across the plates"),
 ("Current decays","Plate pd opposes the emf; I falls exponentially"),
 ("Fully charged","Capacitor pd equals supply emf; current is zero"),
],
P+'ccea-deformation-of-solids-thermal-physics-adventure-1': [
 ("Proportional region ends","Up to here extension obeys Hooke's law"),
 ("Elastic limit passed","Specimen will now keep a permanent stretch"),
 ("Yield point reached","Large strain for little extra stress begins"),
 ("Plastic flow","Permanent deformation as atomic planes slip"),
 ("Ultimate tensile stress","The peak of the stress-strain curve"),
 ("Breaking point","The sample fractures"),
],
P+'ccea-fields-capacitors-particle-physics-adventure-1': [
 ("Quark","Smaller than 10⁻¹⁸ m; no measured size"),
 ("Proton","Diameter about 10⁻¹⁵ m (1 fm scale)"),
 ("Gold nucleus","Diameter about 10⁻¹⁴ m"),
 ("Atom","Diameter about 10⁻¹⁰ m — mostly empty space"),
 ("Large molecule","Nanometre scale, about 10⁻⁹ m"),
 ("Virus","About 10⁻⁷ m across"),
],
P+'ccea-forces-energy-electricity-adventure-1': [
 ("Chemical store in the fuel","Coal or gas holds energy before burning"),
 ("Burning heats the boiler","Thermal store of water and steam fills"),
 ("Steam drives the turbine","Energy transfers to the kinetic store of the blades"),
 ("Generator turns","Kinetic store transferred electrically by induction"),
 ("Power reaches the grid","Transmitted at high voltage to consumers"),
],
P+'ccea-momentum-nuclear-particle-physics-adventure-1': [
 ("Electron","Rest energy 0.511 MeV"),
 ("Muon","Rest energy 105.7 MeV"),
 ("Proton","Rest energy 938.3 MeV"),
 ("Neutron","Rest energy 939.6 MeV"),
 ("Deuteron","Rest energy about 1876 MeV (p + n bound)"),
 ("Alpha particle","Rest energy about 3727 MeV (2p + 2n)"),
],
P+'ccea-practical-techniques-adventure-1': [
 ("Identify the variables","Choose independent, dependent and control variables"),
 ("Plan the method","Select apparatus and ranges; assess risks"),
 ("Take repeat readings","Measure across the full range, repeating each value"),
 ("Calculate means","Average repeats and reject anomalies"),
 ("Plot a graph","Dependent vs independent; draw the best-fit line"),
 ("Evaluate uncertainties","Estimate errors and conclude on the relationship"),
],
P+'ccea-waves-photons-astronomy-adventure-1': [
 ("Radio photon","Lowest photon energy E = hf"),
 ("Microwave photon","More energetic than radio"),
 ("Infrared photon","Below visible in energy"),
 ("Visible photon","Roughly 1.8–3.1 eV"),
 ("Ultraviolet photon","Above visible; ionises some atoms"),
 ("Gamma photon","Highest photon energies, MeV scale"),
],
P+'cosmology--hubbles-law-adventure-1': [
 ("Slipher measures redshifts (1912)","Most spiral nebulae are receding from us"),
 ("Hubble's law (1929)","v = H₀d links recession speed to distance"),
 ("Nucleosynthesis prediction (1948)","Alpher and Gamow explain light-element abundances"),
 ("CMB discovered (1965)","Penzias and Wilson detect the 2.7 K background"),
 ("Accelerating expansion (1998)","Distant supernovae reveal dark energy"),
],
P+'edexcel-electric-circuits-adventure-1': [
 ("Measure the wire's diameter","Micrometer at several points; take the mean"),
 ("Calculate the area","A = πd²/4 from the mean diameter"),
 ("Record V and I for one length","Clip on a set length; compute R = V/I"),
 ("Repeat for other lengths","Same wire, several lengths along the ruler"),
 ("Plot R against length","Straight line through the origin expected"),
 ("Find resistivity","ρ = gradient × A"),
],
P+'edexcel-electric-magnetic-fields-adventure-1': [
 ("Capacitor fully charged","Plate pd equals the supply voltage"),
 ("Switched across a resistor","Discharge path created"),
 ("Discharge current flows","Electrons leave the negative plate through R"),
 ("Charge falls exponentially","Q = Q₀e^(−t/RC)"),
 ("One time constant passes","At t = RC about 37% of the charge remains"),
 ("Effectively discharged","After about 5RC the pd is close to zero"),
],
P+'edexcel-further-mechanics-adventure-1': [
 ("Measure the trolley masses","Record m₁ and m₂ on a balance"),
 ("Measure initial velocities","Light gates time the trolleys before impact"),
 ("Trolleys collide","They stick together or bounce apart"),
 ("Measure final velocities","Light gates record the motion after impact"),
 ("Compare total momentum","Check m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂"),
],
P+'edexcel-materials-adventure-1': [
 ("Measure the wire's diameter","Micrometer readings give area A = πd²/4"),
 ("Measure the original length","Clamp to marker with a metre rule"),
 ("Add known loads","Increase the force in steps with slotted masses"),
 ("Record each extension","Marker movement noted for every load"),
 ("Plot stress against strain","σ = F/A and ε = ΔL/L for each reading"),
 ("Gradient gives Young modulus","E = stress/strain in the linear region"),
],
P+'edexcel-oscillations-adventure-1': [
 ("Released at maximum displacement","x = +A; velocity zero, acceleration greatest"),
 ("Accelerates toward equilibrium","Restoring force acts toward the centre"),
 ("Passes through equilibrium","x = 0; maximum speed, zero acceleration"),
 ("Decelerates beyond the centre","Restoring force now opposes the motion"),
 ("Reaches the opposite extreme","x = −A; momentarily at rest after half a period"),
 ("Returns to the start","One full oscillation completed in period T"),
],
P+'edexcel-space-adventure-1': [
 ("Nebula","Gravity pulls a cloud of gas and dust together"),
 ("Protostar","Collapsing core heats up before fusion begins"),
 ("Main sequence star","Stable hydrogen fusion, like our Sun now"),
 ("Red giant","Sun-like star swells once core hydrogen is spent"),
 ("Planetary nebula","Outer layers drift away into space"),
 ("White dwarf","Hot dense core remnant slowly cooling"),
],
P+'edexcel-thermodynamics-adventure-1': [
 ("Absolute zero","0 K: minimum internal energy"),
 ("Helium boils","About 4.2 K"),
 ("Nitrogen boils","77 K"),
 ("Ice melts","273 K (0 °C)"),
 ("Water boils","373 K (100 °C)"),
 ("Sun's surface","About 5800 K"),
],
P+'edexcel-waves-particle-nature-of-light-adventure-1': [
 ("Photon strikes the metal","A single quantum of energy E = hf arrives"),
 ("One electron absorbs it","All-or-nothing transfer to a surface electron"),
 ("Work function paid","Energy φ spent escaping the surface"),
 ("Photoelectron emitted","Leaves with KE_max = hf − φ"),
 ("Stopping potential measured","eVₛ = KE_max confirms Einstein's equation"),
],
P+'edexcel-working-as-a-physicist-adventure-1': [
 ("Proton","About 10⁻¹⁵ m across"),
 ("Atom","About 10⁻¹⁰ m across"),
 ("Virus","About 10⁻⁷ m across"),
 ("Human","Order of 10⁰ m (a couple of metres)"),
 ("Earth's diameter","About 1.3 × 10⁷ m"),
 ("Sun's diameter","About 1.4 × 10⁹ m"),
],
P+'fields-adventure-1': [
 ("Pluto","Surface gravitational field strength about 0.6 N/kg"),
 ("Moon","Surface g about 1.6 N/kg"),
 ("Mars","Surface g about 3.7 N/kg"),
 ("Earth","Surface g about 9.8 N/kg"),
 ("Jupiter","Surface g about 24.8 N/kg"),
 ("Sun","Surface g about 274 N/kg"),
],
P+'further-mechanics--shm-adventure-1': [
 ("Mass pulled to +A","Maximum extension; elastic store full, v = 0"),
 ("Released and accelerates","Restoring force F = −kx pulls it back"),
 ("Maximum speed at the centre","x = 0; energy is all kinetic"),
 ("Slows past equilibrium","Restoring force now decelerates the mass"),
 ("Momentarily at rest at −A","Velocity zero; acceleration maximum toward centre"),
],
P+'gravitational-fields-adventure-1': [
 ("ISS, low Earth orbit","About 400 km up; period roughly 92 minutes"),
 ("GPS satellites","About 20,200 km altitude; 12-hour period"),
 ("Geostationary orbit","35,786 km altitude; 24-hour period over the equator"),
 ("The Moon","About 384,000 km away; 27.3-day orbit"),
 ("Earth–Sun distance","1 AU, about 1.5 × 10⁸ km"),
],
P+'mechanics-adventure-1': [
 ("Projectile launched","Velocity resolved into horizontal and vertical parts"),
 ("Rising: vertical speed falls","Gravity decelerates the upward motion at 9.81 m/s²"),
 ("Apex of the flight","Vertical velocity zero; horizontal velocity unchanged"),
 ("Falling: vertical speed grows","Gravity now accelerates it downward"),
 ("Lands at launch height","Same speed as launch; symmetric parabola complete"),
],
P+'nuclear--particle-physics-adventure-1': [
 ("Slow neutron absorbed","A U-235 nucleus captures a thermal neutron"),
 ("Unstable U-236 forms","The nucleus deforms and oscillates"),
 ("Nucleus splits","Two lighter fission fragments form"),
 ("Energy and neutrons released","About 200 MeV plus 2–3 fast neutrons"),
 ("Neutrons moderated","Slowed so they can cause further fissions"),
 ("Chain reaction sustained","Control rods keep one fission triggering the next"),
],
P+'ocr-development-of-practical-skills-adventure-1': [
 ("Define the question","State the aim and the variables involved"),
 ("Design the experiment","Apparatus, method, ranges and risk assessment"),
 ("Collect the data","Repeat readings across the whole range"),
 ("Process the results","Means calculated; anomalies identified"),
 ("Graph and analyse","Best-fit line; gradient or intercept extracted"),
 ("Evaluate and conclude","Uncertainties estimated; validity judged"),
],
P+'ocr-electrons-waves-photons-adventure-1': [
 ("Filament heated","Current warms the cathode"),
 ("Thermionic emission","Electrons gain enough energy to leave the metal"),
 ("Accelerated by the pd","Work eV becomes kinetic energy ½mv²"),
 ("Beam passes the anode","Electrons emerge through a small hole at high speed"),
 ("Beam strikes the screen","Kinetic energy transferred to light at the phosphor"),
],
P+'ocr-forces-motion-adventure-1': [
 ("Exit: weight dominates","Skydiver jumps; little drag, acceleration is g"),
 ("Drag grows with speed","Resultant force and acceleration shrink"),
 ("First terminal velocity","Drag equals weight near 50–60 m/s; no acceleration"),
 ("Parachute opens","Drag now exceeds weight; rapid deceleration"),
 ("Second terminal velocity","Forces balance again at a much lower speed"),
 ("Touchdown","Lands at a safe, constant speed"),
],
P+'ocr-foundations-of-physics-adventure-1': [
 ("pico (p)","10⁻¹²"),
 ("nano (n)","10⁻⁹"),
 ("micro (μ)","10⁻⁶"),
 ("centi (c)","10⁻²"),
 ("kilo (k)","10³"),
 ("giga (G)","10⁹"),
],
P+'ocr-newtonian-world-astrophysics-adventure-1': [
 ("Earth–Moon distance","About 3.8 × 10⁸ m"),
 ("Astronomical unit (AU)","Earth–Sun distance, 1.5 × 10¹¹ m"),
 ("Light-year (ly)","9.46 × 10¹⁵ m travelled by light in a year"),
 ("Parsec (pc)","3.09 × 10¹⁶ m, about 3.26 light-years"),
 ("Kiloparsec (kpc)","One thousand parsecs; galactic scales"),
 ("Megaparsec (Mpc)","One million parsecs; distances between galaxies"),
],
P+'ocr-particles-medical-physics-adventure-1': [
 ("Tracer injected","Positron-emitting isotope such as F-18 enters the body"),
 ("Positron emitted","Beta-plus decay occurs in active tissue"),
 ("Annihilation","Positron meets an electron; mass becomes energy"),
 ("Two gamma photons leave","511 keV each, in opposite directions"),
 ("Detector ring records hits","Coincident photons fix the decay line"),
 ("Image reconstructed","Computer maps the tracer concentration"),
],
P+'particle-physics--quarks-adventure-1': [
 ("Up quark","Mass about 2.2 MeV/c² — the lightest quark"),
 ("Down quark","About 4.7 MeV/c²"),
 ("Strange quark","About 95 MeV/c²"),
 ("Charm quark","About 1.3 GeV/c²"),
 ("Bottom quark","About 4.2 GeV/c²"),
 ("Top quark","About 173 GeV/c² — heaviest known particle"),
],
P+'quantum-phenomena-adventure-1': [
 ("Photon of energy hf arrives","Light behaves as discrete quanta"),
 ("Single electron absorbs it","One-to-one, all-or-nothing interaction"),
 ("Work function φ overcome","Minimum energy to escape the metal surface"),
 ("Electron emitted instantly","No delay, provided f exceeds f₀"),
 ("KE_max = hf − φ","Einstein's photoelectric equation"),
 ("Stopping potential check","eVₛ equals KE_max in the measuring circuit"),
],
P+'quantum-physics-adventure-1': [
 ("Planck's quanta (1900)","Energy emitted in packets E = hf"),
 ("Einstein's photon (1905)","Explains the photoelectric effect"),
 ("Bohr's atom (1913)","Quantised electron energy levels"),
 ("de Broglie's matter waves (1924)","λ = h/p for particles"),
 ("Schrödinger's equation (1926)","Wave mechanics for the atom"),
 ("Electron diffraction seen (1927)","Davisson–Germer confirm matter waves"),
],
P+'simple-harmonic-motion-adventure-1': [
 ("t = 0: at +A","Maximum displacement; v = 0, a = −ω²A"),
 ("t = T/4: at equilibrium","Maximum speed v = ωA, moving toward −A"),
 ("t = T/2: at −A","Momentarily at rest at the opposite extreme"),
 ("t = 3T/4: equilibrium again","Maximum speed, now moving back toward +A"),
 ("t = T: back at +A","One complete oscillation finished"),
],
P+'thermal-physics-adventure-1': [
 ("Absolute zero","0 K; particles have minimum internal energy"),
 ("Helium boils","About 4.2 K"),
 ("Nitrogen boils","77 K"),
 ("Room temperature","About 293 K (20 °C)"),
 ("Water boils","373 K"),
 ("Sun's surface","About 5800 K"),
],
P+'waves--optics-adventure-1': [
 ("Red","Lowest visible frequency; wavelength about 700 nm"),
 ("Orange","Wavelength about 620 nm"),
 ("Yellow","Wavelength about 580 nm"),
 ("Green","Wavelength about 530 nm"),
 ("Blue","Wavelength about 470 nm"),
 ("Violet","Highest visible frequency; about 410 nm"),
],
}
def apply(seqs):
    n=0
    for stem, items in seqs.items():
        path = os.path.join(ROOT, stem + '.json')
        with open(path) as f: d = json.load(f)
        assert 5 <= len(items) <= 6, (stem, len(items))
        terms = [t for t,_ in items]
        assert len(set(terms)) == len(terms), (stem, 'dup terms')
        for t, df in items:
            assert len(t) <= 55, (stem, 'term too long', t)
            assert len(df) <= 85, (stem, 'def too long', df, len(df))
        d['sequence'] = [{"term": t, "def": df} for t, df in items]
        with open(path, 'w') as f:
            json.dump(d, f, ensure_ascii=False, separators=(',', ': '))
        n += 1
    print('applied', n)
if __name__ == '__main__':
    apply(SEQ)
