#!/usr/bin/env python3
# Batch 6 sequences — part 3: english language (A-level, GCSE, KS3)
import importlib.util, os
spec = importlib.util.spec_from_file_location('p1', os.path.join(os.path.dirname(__file__), 'apply_b6_p1.py'))
p1 = importlib.util.module_from_spec(spec); spec.loader.exec_module(p1)
A = 'english-language-a-level-'
G = 'english-language-gcse-'
K = 'english-language-ks3-'

CLA_STAGES = [
 ("Cooing stage","From about 2 months: open vowel sounds"),
 ("Babbling stage","From about 6 months: 'ba-ba' consonant-vowel strings"),
 ("Holophrastic stage","Around 12 months: single words carry whole meanings"),
 ("Two-word stage","Around 18 months: mini-sentences like 'mummy gone'"),
 ("Telegraphic stage","Around 24 months: 3+ words, function words missing"),
 ("Post-telegraphic stage","From about 36 months: grammar fills toward adult forms"),
]
PRESENT = [
 ("Choose your topic","Pick a subject you can speak on with authority"),
 ("Research and gather content","Collect facts, examples and anecdotes"),
 ("Structure the talk","Plan the opening, development and conclusion"),
 ("Rehearse","Practise timing, pace and Standard English delivery"),
 ("Deliver the presentation","Speak to your audience in a formal register"),
 ("Answer questions","Respond to the audience — required for the award"),
]
READWF = [
 ("Skim for the gist","A fast first read for overall meaning"),
 ("Scan for key details","Hunt for names, numbers and key words"),
 ("Close read the key section","Slow, careful reading of the relevant lines"),
 ("Infer implicit meaning","Work out what is suggested, not stated"),
 ("Select supporting evidence","Choose short quotations that prove the point"),
 ("Synthesise your answer","Combine the points into a focused response"),
]
RESEARCH = [
 ("Frame a research question","A focused, answerable question about language"),
 ("Review existing studies","Read what linguists have already found"),
 ("Design the methodology","Choose data sources and analytic framework"),
 ("Collect data ethically","Gain consent; gather texts or recordings"),
 ("Analyse the data","Apply linguistic frameworks systematically"),
 ("Conclude and evaluate","Answer the question; admit the limitations"),
]
SEQ = {
A+'aqa-non-exam-assessment-language-in-action-adventure-1': [
 ("Choose a focus and question","Pick a language topic you can investigate"),
 ("Plan the data collection","Decide sources and gain consent — ethics first"),
 ("Gather and transcribe data","Record, collect and prepare your texts"),
 ("Analyse with frameworks","Apply lexis, grammar and discourse levels"),
 ("Draw conclusions","Answer your question from the evidence"),
 ("Evaluate and write up","Note limitations; present the investigation"),
],
A+'aqa-paper-1-language-the-individual-and-society-adventure-1': CLA_STAGES,
A+'aqa-paper-2-language-diversity-and-change-adventure-1': [
 ("Old English begins (c.450)","Anglo-Saxon settlers bring Germanic dialects"),
 ("Norman Conquest (1066)","French loanwords flood in; Middle English era"),
 ("Caxton's printing press (1476)","Print starts to standardise spelling"),
 ("Johnson's Dictionary (1755)","Codifies spellings and meanings"),
 ("OED completed (1928)","First full Oxford English Dictionary published"),
 ("Internet English (1990s)","Digital communication accelerates change"),
],
A+'child-language-acquisition-adventure-1': [
 ("Skinner's behaviourism (1957)","Verbal Behavior: imitation and reinforcement"),
 ("Chomsky's nativism (1959)","Review of Skinner; the innate LAD proposed"),
 ("Brown's morpheme stages (1973)","A First Language charts grammar development"),
 ("Halliday's functions (1975)","Learning How to Mean: seven functions of talk"),
 ("Bruner's LASS (1983)","Child's Talk: interaction scaffolds acquisition"),
],
A+'child-language-acquisition-stages-adventure-1': [
 ("Cooing","Around 6–8 weeks: vowel-like sounds begin"),
 ("Babbling","Around 6 months: repeated syllables, 'ma-ma'"),
 ("Holophrastic","Around 12 months: one word = one whole idea"),
 ("Two-word","Around 18 months: subject + verb combinations"),
 ("Telegraphic","Around 2 years: content words, few inflections"),
 ("Post-telegraphic","3 years on: clauses combine; pronouns settle"),
],
A+'discourse-analysis-adventure-1': [
 ("Summons","The phone rings — the channel is requested"),
 ("Answer and identification","'Hello?' opens the channel and identifies speakers"),
 ("Greeting adjacency pair","'Hi!' — 'Hi, how are you?'"),
 ("Topic talk","The business of the call, managed turn by turn"),
 ("Pre-closing","'Anyway...', 'Right then' signal the end is near"),
 ("Closing pair","'Bye' — 'Bye' ends the conversation"),
],
A+'discourse-analysis-tools-adventure-1': [
 ("Turn-constructional unit","Smallest building block — even one word"),
 ("Turn","One speaker's complete contribution up to a TRP"),
 ("Adjacency pair","Two linked turns, e.g. question then answer"),
 ("Sequence","A run of turns managing one action or topic"),
 ("Whole conversation","Opening to closing — the full speech event"),
],
A+'edexcel-coursework-crafting-language-adventure-1': [
 ("Study the style models","Analyse published texts in your target genre"),
 ("Plan for genre and audience","Decide form, purpose and register"),
 ("Write the first draft","Craft the piece using the genre's conventions"),
 ("Redraft and edit","Refine after feedback"),
 ("Write the commentary","Explain choices, linking back to the style models"),
 ("Submit the folder","Final pieces plus commentary together"),
],
A+'edexcel-paper-1-language-variation-adventure-1': [
 ("Old English (c.450)","Germanic dialects arrive with Anglo-Saxons"),
 ("Norman Conquest (1066)","French becomes the prestige language"),
 ("Caxton's press (1476)","Printing pushes toward a standard"),
 ("King James Bible (1611)","Early Modern English reaches every parish"),
 ("Johnson's Dictionary (1755)","Spelling and meanings codified"),
 ("Global English (1990s+)","The internet spreads new varieties"),
],
A+'edexcel-paper-2-child-language-adventure-1': CLA_STAGES,
A+'edexcel-paper-3-investigating-language-adventure-1': RESEARCH,
A+'gender--language-adventure-1': [
 ("Jespersen's 'The Woman' (1922)","Early deficit account of women's language"),
 ("Lakoff's deficit model (1975)","Language and Woman's Place: hedges, tag questions"),
 ("Spender's dominance view (1980)","Man Made Language: language reflects male power"),
 ("Tannen's difference model (1990)","You Just Don't Understand: separate styles"),
 ("Cameron's critique (2007)","The Myth of Mars and Venus challenges them all"),
],
A+'language--gender-adventure-1': [
 ("Early deficit views (1922)","Jespersen calls women's language deficient"),
 ("Deficit model (1975)","Lakoff: hedges and tags signal weak language"),
 ("Dominance model (1980)","Spender: male power built into language"),
 ("Difference model (1990)","Tannen: distinct but equal styles"),
 ("Diversity model (2000s)","Cameron: gender is performed, not fixed"),
],
A+'language--occupation-adventure-1': [
 ("Goffman's face-work (1955)","Foundations of face and self-presentation"),
 ("Brown & Levinson (1987)","Politeness theory: positive and negative face"),
 ("Swales' discourse communities (1990)","Groups with shared goals and genres"),
 ("Drew & Heritage (1992)","Talk at Work defines institutional talk"),
 ("Koester's workplace talk (2004)","The Language of Work: phatic talk matters"),
],
A+'language--power-adventure-1': [
 ("Goffman's face-work (1955)","Face as the basis of interactional power"),
 ("Grice's maxims (1975)","Cooperative principle; flouting for effect"),
 ("Brown & Levinson (1987)","Politeness strategies manage face threats"),
 ("Fairclough's Language and Power (1989)","Critical discourse analysis; synthetic personalisation"),
 ("Wareing's power types (1999)","Political, personal and social group power"),
],
A+'language-change-adventure-1': [
 ("Old English (c.450–1150)","Germanic core vocabulary established"),
 ("Middle English (1150–1500)","French and Latin influence after 1066"),
 ("Early Modern English (1500–1700)","Printing, the Great Vowel Shift, Shakespeare"),
 ("Modern English (1700–1900)","Dictionaries and grammars standardise"),
 ("Present-Day English (1900+)","Global varieties and digital change"),
],
A+'language-change-theories-adventure-1': [
 ("A new need appears","An invention or idea lacks a name"),
 ("Coinage or borrowing","A word is created or taken from another language"),
 ("Early adopters use it","Slow uptake at the foot of the S-curve"),
 ("Rapid diffusion","The steep middle of the S-curve"),
 ("Usage levels off","The form becomes the community norm"),
 ("Codification","Dictionaries record it as standard"),
],
A+'ocr-non-exam-assessment-independent-language-research-adventure-1': RESEARCH,
A+'ocr-paper-1-exploring-language-adventure-1': [
 ("Phoneme","Smallest unit of sound: /k/ in 'cat'"),
 ("Morpheme","Smallest unit of meaning: 'un-', 'kind'"),
 ("Word","One or more morphemes acting as a unit"),
 ("Phrase","A group built around a head word"),
 ("Clause","Contains a subject and a verb"),
 ("Sentence","One or more clauses; complete and punctuated"),
],
A+'ocr-paper-2-dimensions-of-linguistic-variation-adventure-1': CLA_STAGES,
A+'sociolinguistics-adventure-1': [
 ("Labov: Martha's Vineyard (1963)","Vowel changes signal island identity"),
 ("Labov: NYC department stores (1966)","Post-vocalic /r/ stratified by store status"),
 ("Trudgill: Norwich study (1974)","-ing vs -in' varies with class and gender"),
 ("Milroy: Belfast networks (1980)","Dense social networks preserve vernacular"),
 ("Cheshire: Reading study (1982)","Teen grammar tracks peer-group norms"),
],
G+'aqa-non-examination-assessment-spoken-language-endorsement-adventure-1': PRESENT,
G+'aqa-paper-1-explorations-in-creative-reading-and-writing-adventure-1': [
 ("Q1: retrieve information (4 marks)","List four explicit things from the opening"),
 ("Q2: language analysis (8 marks)","How the writer uses words, phrases, devices"),
 ("Q3: structure analysis (8 marks)","How the whole source is organised"),
 ("Q4: evaluation (20 marks)","How far do you agree with the statement?"),
 ("Q5: creative writing (40 marks)","Section B: description or narrative"),
],
G+'aqa-paper-2-writers-viewpoints-and-perspectives-adventure-1': [
 ("Q1: true statements (4 marks)","Choose four true statements about Source A"),
 ("Q2: summary (8 marks)","Synthesise differences across both sources"),
 ("Q3: language (12 marks)","Analyse the writer's language in one source"),
 ("Q4: compare viewpoints (16 marks)","Compare perspectives and methods"),
 ("Q5: viewpoint writing (40 marks)","Section B: present your own perspective"),
],
G+'cambridge-igcse-component-3-coursework-portfolio-adventure-1': [
 ("Understand the assignment brief","Know the task, audience and word count"),
 ("Plan your response","Gather ideas and order them"),
 ("Write the first draft","Full version for review"),
 ("Receive teacher feedback","One marked draft is permitted"),
 ("Produce the final version","Improve accuracy, structure and style"),
 ("Compile the portfolio","All assignments submitted together"),
],
G+'cambridge-igcse-component-4-speaking-and-listening-adventure-1': [
 ("Choose a talk topic","Something you can discuss in depth"),
 ("Prepare and research","Build content and a clear structure"),
 ("Rehearse the timing","The individual talk lasts 3–4 minutes"),
 ("Part 1: individual talk","Speak alone, without interruption"),
 ("Part 2: conversation","Discuss the topic with the examiner, 7–8 minutes"),
],
G+'cambridge-igcse-paper-1-reading-adventure-1': READWF,
G+'cambridge-igcse-paper-2-directed-writing-and-composition-adventure-1': [
 ("Decode the task","Identify form, audience and purpose"),
 ("Read the source texts","Mine them for ideas and evidence"),
 ("Plan your structure","Order the points before writing"),
 ("Write the response","Adapt register to the target audience"),
 ("Proofread and polish","Fix errors; sharpen word choices"),
],
G+'ccea-unit-1-writing-for-purpose-and-audience-and-reading-to-access-non-fiction-and-media-texts-adventure-1': [
 ("Read the questions first","Know what to hunt for before reading"),
 ("Skim the non-fiction texts","Grasp topic, audience and viewpoint"),
 ("Annotate for techniques","Mark facts, opinions and persuasive devices"),
 ("Plan each answer","Match points to the marks available"),
 ("Write using PEE","Point, evidence, explanation"),
 ("Proofread","Check accuracy in the final minutes"),
],
G+'ccea-unit-2-speaking-and-listening-adventure-1': PRESENT,
G+'ccea-unit-3-studying-spoken-and-written-language-adventure-1': [
 ("Collect speech data","Record talk or obtain a transcript"),
 ("Note the context","Who is speaking, where, and for what purpose"),
 ("Mark the spoken features","Fillers, pauses and false starts in the transcript"),
 ("Compare with written language","Standard forms versus spontaneous talk"),
 ("Analyse why features occur","Link choices to context and audience"),
 ("Write up the findings","Conclusions supported by examples"),
],
G+'ccea-unit-4-personal-or-creative-writing-and-reading-literary-and-non-fiction-texts-adventure-1': [
 ("Exposition","Introduce character, setting and mood"),
 ("Inciting incident","The event that sets the story moving"),
 ("Rising action","Tension builds through complications"),
 ("Climax","The peak moment of conflict"),
 ("Falling action","Consequences begin to unfold"),
 ("Resolution","Loose ends tied; the new normal"),
],
G+'edexcel-component-3-spoken-language-endorsement-adventure-1': PRESENT,
G+'edexcel-igcse-component-3-spoken-language-endorsement-adventure-1': PRESENT,
G+'edexcel-igcse-paper-1-non-fiction-texts-and-transactional-writing-adventure-1': [
 ("Identify the form","Letter, article, speech, report or guide"),
 ("Pin down audience and purpose","Who reads it; inform, argue or persuade"),
 ("Plan your points","Order ideas; prepare a counter-argument"),
 ("Open with the right convention","Headline, address or greeting as the form demands"),
 ("Develop body paragraphs","Topic sentence first, then evidence"),
 ("Check and correct","Proofread spelling, punctuation, grammar"),
],
G+'edexcel-igcse-paper-2-poetry-and-prose-texts-and-imaginative-writing-adventure-1': [
 ("Opening hook","Drop the reader straight into the world"),
 ("Build-up","Layer sensory detail and atmosphere"),
 ("Rising tension","Complications push toward crisis"),
 ("Climax","The story's most intense moment"),
 ("Falling action","The dust begins to settle"),
 ("Resolution","A satisfying, controlled ending"),
],
G+'edexcel-paper-1-fiction-and-imaginative-writing-adventure-1': [
 ("Q1: retrieval (1 mark)","Identify a word or phrase from the early lines"),
 ("Q2: short response (2 marks)","Give two examples from the text"),
 ("Q3: language and structure (6 marks)","Analyse the writer's techniques"),
 ("Q4: evaluation (15 marks)","Judge how successfully an effect is created"),
 ("Section B: imaginative writing (40 marks)","Choose one of two narrative tasks"),
],
G+'edexcel-paper-2-non-fiction-and-transactional-writing-adventure-1': [
 ("Unpack the task","Form, audience and purpose underlined"),
 ("Read the source texts","Harvest ideas, facts and angles"),
 ("Plan the structure","Logical order plus a counter-argument"),
 ("Write to the conventions","Greeting, headline or address as required"),
 ("Build persuasive paragraphs","Topic sentences, evidence, rhetorical devices"),
 ("Proofread","Accuracy marks are easy to protect"),
],
G+'language--power-adventure-1': [
 ("Establish the context","Who is speaking to whom, and why"),
 ("Identify the power type","Instrumental (authority) or influential (persuasion)"),
 ("Spot the power markers","Imperatives, pronouns, interruptions, jargon"),
 ("Analyse the effect","How the features position the audience"),
 ("Evaluate the power balance","Judge who holds the floor and how"),
],
G+'language-analysis-adventure-1': [
 ("Read the question","Fix the exact focus before touching the text"),
 ("Annotate the extract","Underline techniques tied to that focus"),
 ("Point","Open the paragraph with a clear idea"),
 ("Evidence","Embed a short quotation"),
 ("Explain","Analyse the effect of the writer's choice"),
 ("Link","Tie the paragraph back to the question"),
],
G+'linguistic-frameworks-adventure-1': [
 ("Phoneme","The smallest sound unit a language uses"),
 ("Morpheme","The smallest unit that carries meaning"),
 ("Word","Free morphemes and their attachments"),
 ("Phrase","A unit built around a head word"),
 ("Clause","A subject-verb unit"),
 ("Sentence","The largest grammatical unit on the page"),
],
G+'ocr-non-exam-assessment-spoken-language-endorsement-adventure-1': PRESENT,
G+'ocr-paper-1-communicating-information-and-ideas-adventure-1': READWF,
G+'ocr-paper-2-exploring-effects-and-impact-adventure-1': [
 ("Skim both texts","First pass for topic and tone"),
 ("Re-read with the question in mind","Slow reading of the key sections"),
 ("Mark the strongest evidence","Short quotations with rich effects"),
 ("Analyse the writers' methods","Language, structure and their impact"),
 ("Compare the two texts","Similarities and differences in effect"),
 ("Write the structured response","Clear paragraphs that answer the question"),
],
G+'rhetorical-devices-adventure-1': [
 ("Invention","Cicero's first canon: find the arguments"),
 ("Arrangement","Order the speech for maximum impact"),
 ("Style","Choose the devices — tripling, anaphora, hyperbole"),
 ("Memory","Learn the speech for performance"),
 ("Delivery","Perform it with voice and gesture"),
],
G+'sentence-structures-adventure-1': [
 ("Minor sentence","No full clause: 'What a day!'"),
 ("Simple sentence","Exactly one main clause"),
 ("Compound sentence","Two main clauses joined by and, but, or"),
 ("Complex sentence","A main clause plus a subordinate clause"),
 ("Compound-complex sentence","Two main clauses and at least one subordinate"),
],
G+'spoken-language-adventure-1': [
 ("Idiolect","The unique language of one individual"),
 ("Sociolect","Shared by a social group"),
 ("Regional dialect","Shared across a whole region"),
 ("Standard English","The national prestige variety"),
 ("Global English","Used by well over a billion speakers worldwide"),
],
G+'spoken-language-features-adventure-1': [
 ("Record the conversation","With the speakers' consent"),
 ("Transcribe with a key","Mark pauses (.) and overlaps"),
 ("Label the features","Fillers, false starts, discourse markers, elision"),
 ("Explain why each occurs","Spontaneity, planning time, relationship"),
 ("Evaluate the speaker's fluency","Judge the effect on the listener"),
],
G+'writers-methods-adventure-1': [
 ("Word level","Single choices of diction and connotation"),
 ("Phrase level","Images and modification built from word groups"),
 ("Sentence level","Syntax, sentence forms and their rhythm"),
 ("Paragraph level","Shifts of focus, contrast and pace"),
 ("Whole-text level","Narrative voice and structural arc"),
],
G+'writing---descriptive--narrative-adventure-1': [
 ("Exposition","Establish voice, character and setting"),
 ("Rising action","Build tension with escalating detail"),
 ("Climax","The single most intense moment"),
 ("Falling action","Release the tension in stages"),
 ("Resolution","Close with a controlled final image"),
],
G+'writing---transactional-adventure-1': [
 ("Sender's address (top right)","Your address opens a formal letter"),
 ("Recipient's address (left, below)","Name and address of who you're writing to"),
 ("Greeting","'Dear Sir/Madam' or a named recipient"),
 ("Opening paragraph states purpose","Say why you are writing immediately"),
 ("Body paragraphs develop points","One clear point per paragraph"),
 ("Formal sign-off","'Yours faithfully' (unnamed) or 'Yours sincerely'"),
],
K+'figurative-language-adventure-1': [
 ("Read the passage","Get the literal meaning first"),
 ("Spot the figurative phrase","Language that isn't meant literally"),
 ("Name the device","Simile ('like'/'as'), metaphor or personification"),
 ("Unpack the comparison","What two things are linked, and which qualities"),
 ("Explain the effect","What the image makes the reader see or feel"),
],
K+'language-variation-adventure-1': [
 ("Idiolect","One person's unique way of speaking"),
 ("Sociolect","The shared style of a social group"),
 ("Regional dialect","Words and grammar of a whole area"),
 ("National standard","Standard English across the country"),
 ("Global Englishes","Varieties used around the world"),
],
K+'media--texts-adventure-1': [
 ("Printed news (1600s)","The first newspapers circulate in Britain"),
 ("Radio broadcasting (1920s)","The BBC begins broadcasts in 1922"),
 ("Television (1936)","The BBC launches regular TV"),
 ("The web (1991)","Websites make news global and instant"),
 ("Social media (2000s)","Facebook 2004: audiences become creators"),
],
K+'persuasive-techniques-adventure-1': [
 ("Hook the audience","Open with a question, anecdote or shocking statistic"),
 ("State your viewpoint","Make your position unmistakable early on"),
 ("Argue with evidence","Facts, statistics and expert opinion"),
 ("Tackle the counter-argument","Acknowledge and defeat the other side"),
 ("Finish with a call to action","Tell the audience exactly what to do"),
],
K+'reading--genre-adventure-1': [
 ("Preview the text","Predict from the title, cover and genre clues"),
 ("Skim for the gist","Rough sense of what it's about"),
 ("Read closely","Follow detail, character and events"),
 ("Infer beyond the lines","Work out what's implied"),
 ("Summarise","Capture the key points briefly"),
 ("Respond","Give your own view, with reasons"),
],
K+'reading-skills--inference-adventure-1': [
 ("Read the passage carefully","A full, attentive first read"),
 ("Retrieve explicit details","Facts stated directly on the page"),
 ("Notice implicit clues","Word choices hinting at something more"),
 ("Make an inference","Read between the lines"),
 ("Check against the evidence","Does the text really support your idea?"),
 ("Refine your interpretation","Adjust the reading as clues accumulate"),
],
K+'sentence-punctuation-adventure-1': [
 ("Open the inverted commas","Speech marks signal that talking begins"),
 ("Capital letter for the first word","Spoken words start with a capital"),
 ("Write the spoken words","The actual speech goes inside"),
 ("Punctuate before closing","Comma, ? or ! sits inside the speech marks"),
 ("Close the inverted commas","Speech marks end the spoken words"),
 ("Add the reporting clause","e.g. said Sam — then a full stop"),
],
K+'spoken-language-adventure-1': [
 ("Slang with close friends","Least formal: in-group words and banter"),
 ("Casual chat at home","Colloquial, relaxed grammar"),
 ("Classroom discussion","Clearer Standard English expected"),
 ("Job interview","Careful, formal Standard English"),
 ("Formal ceremony speech","Most formal: fixed, scripted language"),
],
K+'word-classes-adventure-1': [
 ("Opinion adjective","'lovely' — judgements come first"),
 ("Size adjective","'big' follows opinion"),
 ("Age adjective","'old' comes third"),
 ("Shape adjective","'round' sits before colour"),
 ("Colour adjective","'red' comes next"),
 ("Material adjective","'wooden' sits last: a lovely big old round red wooden table"),
],
K+'word-classes-basics-adventure-1': [
 ("Determiner — 'The'","Opens the noun phrase"),
 ("Adjective — 'sleepy'","Describes the noun that follows"),
 ("Subject noun — 'cat'","Who or what does the action"),
 ("Adverb — 'quietly'","Modifies the verb, placed just before it"),
 ("Verb — 'watched'","The action of the sentence"),
 ("Object noun — 'birds'","Receives the action and ends the sentence"),
],
K+'writing--persuasion-adventure-1': [
 ("Formal greeting","'Dear Headteacher' sets the register"),
 ("Opening states your purpose","Say what you want in the first lines"),
 ("Arguments with AFOREST","Facts, opinions, rhetorical questions, emotive language"),
 ("Deal with the other side","Counter the obvious objection"),
 ("Call to action","Tell the reader exactly what to do next"),
 ("Sign off formally","'Yours sincerely' and your name"),
],
}
if __name__ == '__main__':
    p1.apply(SEQ)
