# Batch 9 sequences, part 2: Business Studies
SEQ2 = {

# ---------- BUSINESS A-LEVEL ----------
"business-studies-a-level-ansoff--porter-adventure-1": [
 ("Set the mission and corporate objectives", "Strategy starts from what the business wants to achieve"),
 ("Analyse the strategic position", "Internal and external analysis precedes any choice"),
 ("Map options on the Ansoff matrix", "Markets and products options follow the analysis"),
 ("Pick a Porter generic strategy", "Cost leadership or differentiation defines how to compete"),
 ("Implement the chosen strategy", "Action follows the strategic decisions"),
 ("Review performance and adjust", "Evaluation closes the strategic cycle"),
],
"business-studies-a-level-aqa-analysing-the-strategic-position-of-a-business-adventure-1": [
 ("Clarify mission and objectives", "Analysis is framed by what the firm is trying to do"),
 ("Scan the macro environment (PESTLE)", "The widest external layer is examined first"),
 ("Analyse the industry (Five Forces)", "Porter's model narrows focus to the market"),
 ("Audit internal resources and finances", "The firm's own capabilities are assessed next"),
 ("Summarise the position in a SWOT", "The grid synthesises all the prior analysis"),
 ("Feed findings into strategic choice", "Position analysis exists to inform decisions"),
],
"business-studies-a-level-aqa-choosing-strategic-direction-adventure-1": [
 ("Review the strategic position findings", "Direction is chosen from the analysis stage"),
 ("Generate options with the Ansoff matrix", "Which markets and which products are listed"),
 ("Assess risk and return of each option", "Diversification carries more risk than penetration"),
 ("Test options for fit and feasibility", "Resources and values screen the shortlist"),
 ("Select the strategic direction", "One direction is committed to"),
 ("Set objectives for the chosen path", "Targets translate the direction into action"),
],
"business-studies-a-level-aqa-decision-making-to-improve-financial-performance-adventure-1": [
 ("Identify total fixed costs", "Break-even starts with costs that do not vary"),
 ("Find the variable cost per unit", "The per-unit cost is needed for contribution"),
 ("Confirm the selling price per unit", "Price completes the data set"),
 ("Calculate contribution per unit", "Price minus variable cost gives contribution"),
 ("Divide fixed costs by contribution", "This yields the break-even output"),
 ("Work out the margin of safety", "Actual sales minus break-even comes last"),
],
"business-studies-a-level-aqa-decision-making-to-improve-human-resource-performance-adventure-1": [
 ("Workforce plan identifies a vacancy", "Recruitment begins when a gap is confirmed"),
 ("Write the job description", "The role is defined before the person"),
 ("Draw up the person specification", "Required skills follow the role definition"),
 ("Advertise the vacancy", "The post goes to market once documents exist"),
 ("Shortlist the applicants", "Applications are sifted against the spec"),
 ("Interview and select", "Appointment is the final stage"),
],
"business-studies-a-level-aqa-decision-making-to-improve-marketing-performance-adventure-1": [
 ("Conduct market research", "Evidence about customers is gathered first"),
 ("Segment the market", "Research reveals the distinct customer groups"),
 ("Target the chosen segments", "Targeting picks from the mapped segments"),
 ("Position the product against rivals", "Positioning follows the choice of target"),
 ("Build the marketing mix", "The 7Ps deliver the chosen position"),
 ("Monitor sales and adjust", "Feedback closes the marketing loop"),
],
"business-studies-a-level-aqa-decision-making-to-improve-operational-performance-adventure-1": [
 ("Forecast demand from sales data", "Operations planning starts with expected demand"),
 ("Set the capacity plan", "Capacity is matched to the forecast"),
 ("Order inventory from suppliers", "Inputs are secured before production"),
 ("Run the production process", "Transformation of inputs follows supply"),
 ("Carry out quality control checks", "Output is inspected after production"),
 ("Distribute to customers", "Delivery is the final operational step"),
],
"business-studies-a-level-aqa-managers-leadership-and-decision-making-adventure-1": [
 ("Set the decision objectives", "Scientific decision-making starts with clear goals"),
 ("Gather data and evidence", "Information is collected before options form"),
 ("Identify the possible options", "Alternatives emerge from the evidence"),
 ("Analyse options with decision trees", "Expected values weigh up the alternatives"),
 ("Make and implement the choice", "Action follows the analysis"),
 ("Review the outcome", "Evaluation completes the cycle"),
],
"business-studies-a-level-aqa-managing-strategic-change-adventure-1": [
 ("Create a sense of urgency", "Kotter's step 1 makes the case for change"),
 ("Build a guiding coalition", "Step 2 assembles powerful backers"),
 ("Form the strategic vision", "Step 3 defines where change leads"),
 ("Communicate the vision widely", "Step 4 spreads the message"),
 ("Empower action and remove barriers", "Step 5 unblocks the change effort"),
 ("Anchor the changes in culture", "Kotter's final step (8) embeds the new ways"),
],
"business-studies-a-level-aqa-strategic-methods-how-to-pursue-strategies-adventure-1": [
 ("Sell only in the domestic market", "The lowest-commitment starting point"),
 ("Begin exporting", "Goods cross borders with little investment"),
 ("License or franchise abroad", "Partners carry more of the operation overseas"),
 ("Form a joint venture", "Shared ownership deepens the commitment"),
 ("Open a wholly owned subsidiary", "Full ownership is the highest-risk, deepest entry"),
],
"business-studies-a-level-aqa-what-is-business?-adventure-1": [
 ("Spot the business idea", "Every venture begins with an opportunity"),
 ("Research the market", "Evidence tests whether the idea can work"),
 ("Write the business plan", "Research findings shape the written plan"),
 ("Secure the finance", "The plan is used to raise funds"),
 ("Launch and start trading", "Operations begin once funded"),
 ("Review against objectives", "Performance is measured after launch"),
],
"business-studies-a-level-bcg--product-portfolio-adventure-1": [
 ("Research and development", "The product exists only as plans and prototypes"),
 ("Introduction and launch", "Sales start low; the BCG question mark stage"),
 ("Growth", "Sales climb fast; stars need heavy investment"),
 ("Maturity", "Sales peak; cash cows are milked for profit"),
 ("Decline", "Sales fall; dogs face divestment or extension"),
],
"business-studies-a-level-business-strategy-adventure-1": [
 ("Define the mission", "The overall purpose anchors everything below it"),
 ("Set corporate objectives", "Measurable goals translate the mission"),
 ("Conduct strategic analysis", "SWOT and PESTLE assess the position"),
 ("Make the strategic choice", "Options are evaluated and one is selected"),
 ("Implement the strategy", "Plans become resourced actions"),
 ("Review and control", "Performance is checked against the objectives"),
],
"business-studies-a-level-change-management-adventure-1": [
 ("Recognise the pressure for change", "Internal or external triggers start the process"),
 ("Run a force field analysis", "Lewin's tool weighs driving against restraining forces"),
 ("Unfreeze existing behaviours", "Lewin's first stage prepares people to move"),
 ("Make the change", "The transition itself is Lewin's second stage"),
 ("Refreeze the new ways", "Lewin's third stage embeds the change"),
 ("Evaluate the change programme", "Review confirms the benefits were delivered"),
],
"business-studies-a-level-edexcel-theme-1-marketing-and-people-adventure-1": [
 ("Set the research objectives", "Market research starts with questions to answer"),
 ("Choose primary and secondary methods", "Methods follow from the objectives"),
 ("Design the sample", "Who to ask is settled before fieldwork"),
 ("Collect the data", "Fieldwork happens once design is complete"),
 ("Analyse and interpret results", "Meaning is extracted from the raw data"),
 ("Present findings to decision-makers", "Reporting turns research into action"),
],
"business-studies-a-level-edexcel-theme-2-managing-business-activities-adventure-1": [
 ("Enter the opening balance", "A cash-flow forecast starts with cash held"),
 ("Add up forecast cash inflows", "Expected receipts are totalled next"),
 ("Total the forecast cash outflows", "Expected payments are summed"),
 ("Calculate net cash flow", "Inflows minus outflows gives the net figure"),
 ("Find the closing balance", "Opening balance plus net cash flow"),
 ("Carry forward to next month's opening", "The closing figure starts the next column"),
],
"business-studies-a-level-edexcel-theme-3-business-decisions-and-strategy-adventure-1": [
 ("Draw the decision tree", "Decision and chance nodes map the problem first"),
 ("Assign probabilities to outcomes", "Each chance branch gets a likelihood"),
 ("Estimate the payoffs", "Financial outcomes are attached to each branch"),
 ("Calculate expected values", "Probability times payoff, summed per option"),
 ("Subtract the option costs", "Net gain = expected value minus cost"),
 ("Choose the highest net gain", "The decision rule is applied last"),
],
"business-studies-a-level-edexcel-theme-4-global-business-adventure-1": [
 ("Assess countries with PESTLE analysis", "Screening markets is the first step abroad"),
 ("Select the target market", "One country is chosen from the assessment"),
 ("Choose the market entry method", "Exporting, licensing or FDI follows the choice"),
 ("Adapt the marketing mix (glocalisation)", "The offer is tailored before launch"),
 ("Launch in the new market", "Entry happens once the offer is ready"),
 ("Review performance and expand", "Results guide further globalisation"),
],
"business-studies-a-level-external-environment-adventure-1": [
 ("Trough - the lowest point", "GDP bottoms out at the slump"),
 ("Recovery begins", "Output starts rising from the trough"),
 ("Sustained growth", "Spending, investment and jobs expand"),
 ("Boom - the peak", "The economy overheats at the top of the cycle"),
 ("Downturn into recession", "Falling GDP follows the boom"),
],
"business-studies-a-level-finance--accounting-adventure-1": [
 ("Record transactions in the accounts", "Bookkeeping is the raw material of finance"),
 ("Produce the trial balance", "Records are checked before statements are built"),
 ("Prepare the income statement", "Profit for the period is calculated"),
 ("Prepare the balance sheet", "Assets and liabilities are stated at year end"),
 ("Calculate the key ratios", "Ratios are computed from the finished statements"),
 ("Interpret for stakeholders", "Analysis turns numbers into decisions"),
],
"business-studies-a-level-global-business-adventure-1": [
 ("Serve the home market only", "Globalisation starts from a domestic base"),
 ("Export through agents and distributors", "Low-commitment sales abroad come first"),
 ("License or franchise to overseas partners", "Contracts extend the brand with limited risk"),
 ("Enter a joint venture", "Shared local ownership deepens involvement"),
 ("Establish wholly owned operations abroad", "Direct investment is the deepest commitment"),
 ("Integrate as a global multinational", "Worldwide coordination is the end state"),
],
"business-studies-a-level-human-resources-adventure-1": [
 ("Identify the vacancy in the workforce plan", "Planning reveals the staffing gap first"),
 ("Carry out a job analysis", "The role's duties are examined"),
 ("Prepare description and person spec", "The documents define role and candidate"),
 ("Advertise internally or externally", "The vacancy is publicised"),
 ("Shortlist and interview", "Candidates are sifted then assessed"),
 ("Appoint and induct the new starter", "Induction completes the recruitment cycle"),
],
"business-studies-a-level-investment-appraisal-adventure-1": [
 ("State the initial outlay", "NPV starts with the cost of the investment"),
 ("Forecast the future net cash flows", "Year-by-year returns are estimated"),
 ("Choose the discount rate", "The rate reflects interest and risk"),
 ("Multiply flows by discount factors", "Future money is converted to present values"),
 ("Sum the discounted flows", "Present values are totalled"),
 ("Subtract the outlay to get NPV", "Invest if the final figure is positive"),
],
"business-studies-a-level-marketing-adventure-1": [
 ("Innovators adopt first (2.5%)", "Risk-takers buy at launch"),
 ("Early adopters follow (13.5%)", "Opinion leaders validate the product"),
 ("Early majority join (34%)", "The mainstream arrives once proof exists"),
 ("Late majority buy in (34%)", "Sceptics purchase after most others"),
 ("Laggards adopt last (16%)", "The final group resists change longest"),
],
"business-studies-a-level-ocr-operating-in-a-local-business-environment-adventure-1": [
 ("Spot a gap in the local market", "Local ventures begin with an unmet need"),
 ("Research local customers and rivals", "Evidence tests the local opportunity"),
 ("Write the business plan", "The plan converts research into a proposal"),
 ("Raise finance and secure premises", "Resources are put in place from the plan"),
 ("Launch and trade locally", "Doors open once resourced"),
 ("Review against the start-up aims", "Performance is judged after trading begins"),
],
"business-studies-a-level-ocr-the-global-business-environment-adventure-1": [
 ("Free trade area", "Members drop tariffs between themselves only"),
 ("Customs union", "A common external tariff is added"),
 ("Single market", "Free movement of goods, services, capital, labour"),
 ("Monetary union", "Members share one currency"),
 ("Full economic union", "Fiscal and economic policy are unified - deepest stage"),
],
"business-studies-a-level-ocr-the-uk-business-environment-adventure-1": [
 ("Sole trader", "One owner with unlimited liability - the smallest form"),
 ("Partnership", "Two or more owners share control and profits"),
 ("Private limited company (Ltd)", "Shareholders gain limited liability; shares stay private"),
 ("Public limited company (plc)", "Shares trade on the stock exchange"),
 ("Multinational corporation", "Operations span many countries - the largest scale"),
],
"business-studies-a-level-operations-management-adventure-1": [
 ("Raw material producers", "The supply chain begins with extraction and growing"),
 ("Component manufacturers", "Materials become parts"),
 ("Final assembly", "Parts become finished products"),
 ("Wholesalers and distributors", "Bulk product moves towards market"),
 ("Retailers", "Goods reach the point of sale"),
 ("The end consumer", "The chain finishes with the customer"),
],
"business-studies-a-level-ratio-analysis-adventure-1": [
 ("Obtain the final accounts", "Ratios need the statements as raw data"),
 ("Select ratios suited to the question", "Profitability, liquidity or gearing focus is chosen"),
 ("Extract the correct figures", "Numbers are pulled from the statements"),
 ("Calculate the ratios", "The formulas are applied"),
 ("Compare with benchmarks and trends", "Results mean little without comparison"),
 ("Recommend action", "Analysis ends with a decision"),
],
"business-studies-a-level-swot--pestle-adventure-1": [
 ("Define the decision being analysed", "Analysis needs a purpose before it starts"),
 ("Run a PESTLE scan of the macro environment", "External forces are mapped first"),
 ("Convert the scan into opportunities and threats", "O and T are drawn from the PESTLE findings"),
 ("Audit internal strengths and weaknesses", "Capabilities are judged against the external picture"),
 ("Compile the full SWOT grid", "The matrix needs all four lists complete"),
 ("Match strengths to opportunities in strategy", "Using the grid is the final purpose"),
],

# ---------- BUSINESS GCSE ----------
"business-studies-gcse-aqa-business-in-the-real-world-adventure-1": [
 ("Identify the business idea", "Enterprise starts with spotting an opportunity"),
 ("Carry out market research", "The idea is tested against real demand"),
 ("Produce the business plan", "Research results are written into a plan"),
 ("Obtain sources of finance", "The plan persuades lenders and investors"),
 ("Choose a location and launch", "Trading begins once funds are in place"),
 ("Measure success against aims", "Review follows the launch"),
],
"business-studies-gcse-aqa-business-operations-adventure-1": [
 ("Customer places an order", "The operations process is triggered by demand"),
 ("Order materials from suppliers", "Inputs are procured to meet the order"),
 ("Run the production process", "Materials are transformed into products"),
 ("Inspect at quality control", "Checking follows production"),
 ("Package the finished goods", "Products are prepared for transit"),
 ("Deliver to the customer", "Logistics completes the process"),
],
"business-studies-gcse-aqa-influences-on-business-adventure-1": [
 ("Bank of England raises the base rate", "The chain starts with the interest rate decision"),
 ("Banks raise loan and mortgage rates", "Borrowing costs follow the base rate"),
 ("Consumers have less disposable income", "Higher repayments squeeze spending power"),
 ("Demand for products falls", "Lower spending hits firms' sales"),
 ("Firms cut output and investment", "Businesses respond to falling demand last"),
],
"business-studies-gcse-break-even-analysis-adventure-1": [
 ("List the total fixed costs", "Rent and salaries are identified first"),
 ("Find the variable cost per unit", "The cost that changes with output comes next"),
 ("Set the selling price per unit", "Price completes the inputs needed"),
 ("Work out contribution per unit", "Selling price minus variable cost"),
 ("Divide fixed costs by contribution", "The result is the break-even point in units"),
 ("Calculate the margin of safety", "Actual output minus break-even output"),
],
"business-studies-gcse-business-basics--startup-adventure-1": [
 ("Come up with the idea", "A start-up begins with a product or service idea"),
 ("Research the market", "Customers and competitors are investigated"),
 ("Write the business plan", "The plan organises the research into a case"),
 ("Raise the start-up finance", "Money is secured using the plan"),
 ("Open for business", "The launch follows the funding"),
 ("Review the first results", "Early performance is checked against aims"),
],
"business-studies-gcse-cambridge-igcse-external-influences-on-business-activity-adventure-1": [
 ("Slump - the bottom of the cycle", "Output and confidence are at their lowest"),
 ("Recovery", "GDP begins to rise again after the slump"),
 ("Growth", "Spending, output and employment expand"),
 ("Boom - the peak", "Demand and inflation pressures hit their height"),
 ("Recession", "Falling GDP follows the boom and closes the loop"),
],
"business-studies-gcse-cambridge-igcse-financial-information-and-decisions-adventure-1": [
 ("Revenue - the top line", "The income statement starts with sales income"),
 ("Subtract cost of sales", "Direct costs are deducted from revenue"),
 ("Gross profit", "Revenue minus cost of sales appears next"),
 ("Subtract expenses and overheads", "Indirect costs are deducted from gross profit"),
 ("Profit for the year", "The bottom line after all costs"),
 ("Retained profit after dividends", "What remains in the business comes last"),
],
"business-studies-gcse-cambridge-igcse-operations-management-adventure-1": [
 ("Purchase the inputs", "Operations begin with buying materials"),
 ("Hold raw material inventory", "Stocks wait ready for production"),
 ("Transform inputs in production", "Making converts materials into products"),
 ("Store finished goods", "Completed output is held before sale"),
 ("Distribute to retailers", "Goods travel toward the market"),
 ("Reach the customer", "The process ends at the point of consumption"),
],
"business-studies-gcse-cambridge-igcse-people-in-business-adventure-1": [
 ("A vacancy arises", "Recruitment starts when a post needs filling"),
 ("Conduct a job analysis", "The role's tasks and skills are studied"),
 ("Write the job description and person spec", "Documents define the role and ideal candidate"),
 ("Advertise the post", "The vacancy reaches potential applicants"),
 ("Shortlist the applications", "Candidates are sifted against the spec"),
 ("Interview and appoint", "Selection finishes the process"),
],
"business-studies-gcse-cambridge-igcse-understanding-business-activity-adventure-1": [
 ("Farmer grows the wheat (primary)", "The chain of production starts with extraction"),
 ("Mill grinds wheat into flour (secondary)", "First-stage processing follows the farm"),
 ("Bakery bakes the bread (secondary)", "Manufacturing turns flour into the product"),
 ("Distributor transports the loaves (tertiary)", "Logistics moves goods to market"),
 ("Supermarket sells the bread (tertiary)", "Retail is the final service stage"),
 ("Consumer buys and eats it", "The chain ends with consumption"),
],
"business-studies-gcse-cash-flow-adventure-1": [
 ("Start with the opening balance", "Cash already held begins the forecast"),
 ("Total the month's cash inflows", "Receipts from sales and loans are added up"),
 ("Total the month's cash outflows", "Payments for wages, stock and rent are summed"),
 ("Net cash flow = inflows - outflows", "The month's net movement is calculated"),
 ("Closing balance = opening + net flow", "The month ends with this figure"),
 ("Use closing as next month's opening", "The forecast rolls forward"),
],
"business-studies-gcse-edexcel-building-a-business-adventure-1": [
 ("Development stage", "The product is designed and tested before sale"),
 ("Introduction", "Launch brings the first, slow sales"),
 ("Growth", "Sales rise quickly as awareness spreads"),
 ("Maturity", "Sales peak and competition intensifies"),
 ("Decline", "Sales fall unless an extension strategy is used"),
],
"business-studies-gcse-edexcel-investigating-small-business-adventure-1": [
 ("Spot a gap in the market", "Small businesses begin with customer needs unmet"),
 ("Test the idea with market research", "Evidence reduces the risk of the idea"),
 ("Draw up the business plan", "Aims, forecasts and finance are written down"),
 ("Secure start-up finance", "Funds are raised on the strength of the plan"),
 ("Launch the small business", "Trading starts after funding"),
 ("Measure performance against aims", "Review completes the start-up journey"),
],
"business-studies-gcse-ethics--sustainability-adventure-1": [
 ("Prevent and reduce waste", "The top of the waste hierarchy: avoid waste first"),
 ("Reuse products and materials", "Second-best: use items again as they are"),
 ("Recycle into new materials", "Reprocessing ranks below reusing"),
 ("Recover energy from waste", "Burning for energy is next to last"),
 ("Dispose to landfill", "The least sustainable option sits at the bottom"),
],
"business-studies-gcse-external-influences-adventure-1": [
 ("The pound appreciates", "The chain starts with a stronger exchange rate"),
 ("UK exports become dearer abroad", "Foreign buyers now pay more for UK goods"),
 ("Overseas demand for exports falls", "Higher prices cut foreign sales"),
 ("Exporters' revenues decline", "Falling sales feed through to income"),
 ("Exporters cut output and jobs", "Firms respond to lost revenue last"),
],
"business-studies-gcse-finance-adventure-1": [
 ("Revenue from sales", "The income statement always starts at the top line"),
 ("Deduct the cost of sales", "Direct costs come off revenue first"),
 ("Gross profit", "What remains after direct costs"),
 ("Deduct operating expenses", "Rent, marketing and admin are taken off next"),
 ("Operating profit", "Profit from normal trading activities"),
 ("Net profit - the bottom line", "After interest and tax, the final figure"),
],
"business-studies-gcse-human-resources-adventure-1": [
 ("Identify the staffing need", "Recruitment begins when a gap is recognised"),
 ("Prepare the job description", "The duties of the role are set out"),
 ("Write the person specification", "The ideal candidate profile follows the role"),
 ("Advertise the job", "The vacancy is publicised to attract applicants"),
 ("Shortlist candidates", "Applications are filtered against the spec"),
 ("Hold interviews and appoint", "Selection ends the process"),
],
"business-studies-gcse-market-research-adventure-1": [
 ("Decide what you need to find out", "Objectives come before any data gathering"),
 ("Choose the research method", "Primary or secondary methods suit the objectives"),
 ("Design the questionnaire and sample", "Questions and respondents are planned"),
 ("Collect the responses", "Fieldwork follows the design"),
 ("Analyse the results", "Patterns are extracted from the data"),
 ("Report findings and decide", "Research ends by informing a decision"),
],
"business-studies-gcse-marketing-adventure-1": [
 ("Research the market", "Customer needs are discovered first"),
 ("Identify the target segment", "Research reveals who to aim at"),
 ("Develop a product to fit the segment", "The offer is built for the chosen customers"),
 ("Decide the launch pricing", "Skimming or penetration is set pre-launch"),
 ("Run the promotion campaign", "Awareness is built for the launch"),
 ("Distribute and monitor sales", "Place and feedback complete the launch"),
],
"business-studies-gcse-marketing-mix-adventure-1": [
 ("Generate new product ideas", "Development begins with many raw ideas"),
 ("Screen out the weak ideas", "Filtering follows idea generation"),
 ("Develop and test the concept", "Surviving ideas are shaped and checked"),
 ("Build the prototype", "A working version is made after concept testing"),
 ("Test market in a small area", "A limited launch checks real demand"),
 ("Launch fully with the marketing mix", "Full roll-out is the final stage"),
],
"business-studies-gcse-motivation-theories-adventure-1": [
 ("Physiological needs", "Maslow's base: pay that covers food and shelter"),
 ("Safety needs", "Job security and safe conditions come second"),
 ("Social needs", "Belonging and teamwork form the middle tier"),
 ("Esteem needs", "Status and recognition sit near the top"),
 ("Self-actualisation", "Fulfilling potential crowns the hierarchy"),
],
"business-studies-gcse-ocr-business-activity-marketing-and-people-adventure-1": [
 ("Gather market research data", "Understanding customers comes before targeting"),
 ("Divide the market into segments", "Groups with shared needs are identified"),
 ("Select the target market", "One or more segments are chosen"),
 ("Position the product", "The brand is placed against competitors"),
 ("Apply the marketing mix", "Product, price, place and promotion deliver it"),
 ("Review and adapt to feedback", "The cycle ends with evaluation"),
],
"business-studies-gcse-ocr-operations-finance-and-influences-on-business-adventure-1": [
 ("Receive the customer order", "Order fulfilment starts with demand"),
 ("Check stock availability", "Inventory is verified before production"),
 ("Manufacture the goods", "Production fills any gap in stock"),
 ("Complete the quality check", "Inspection follows manufacture"),
 ("Dispatch the order", "Packed goods leave for the customer"),
 ("Provide after-sales service", "Support continues after delivery"),
],
"business-studies-gcse-operations-adventure-1": [
 ("Raw materials are sourced", "Every product starts with inputs from suppliers"),
 ("The manufacturer makes the product", "Production transforms the materials"),
 ("Wholesalers buy in bulk", "Breaking bulk moves goods down the chain"),
 ("Retailers stock the shelves", "Shops put products in front of buyers"),
 ("The consumer makes the purchase", "The supply chain ends at the customer"),
],

# ---------- BUSINESS IBDP ----------
"business-studies-ibdp-business-organization--environment-adventure-1": [
 ("Identify a market opportunity", "Setting up a business starts with an unmet need"),
 ("Conduct market research", "Evidence validates the opportunity"),
 ("Write the business plan", "Research becomes a structured proposal"),
 ("Secure the finance", "Capital is raised on the plan"),
 ("Choose and register the legal structure", "The entity is formalised before trading"),
 ("Commence operations", "Trading begins once everything is in place"),
],
"business-studies-ibdp-finance--accounts-adventure-1": [
 ("Record the year's transactions", "Final accounts are built from bookkeeping records"),
 ("Check totals with a trial balance", "Accuracy is verified before statements"),
 ("Draw up the profit and loss account", "The period's profit is established"),
 ("Draw up the balance sheet", "The year-end position statement follows"),
 ("Compute ratios from the statements", "Analysis needs the finished accounts"),
 ("Interpret results for stakeholders", "Judgement is the final purpose"),
],
"business-studies-ibdp-globalization--business-ethics-adventure-1": [
 ("Operate only in the home country", "Internationalisation begins domestically"),
 ("Export to foreign customers", "Selling abroad needs little investment"),
 ("Franchise or license overseas", "Local partners extend the reach"),
 ("Create joint ventures abroad", "Shared ownership raises the stakes"),
 ("Invest in wholly owned foreign units", "FDI is the deepest, riskiest commitment"),
 ("Coordinate as a global multinational", "Worldwide integration completes the journey"),
],
"business-studies-ibdp-hl-finance-and-accounts-adventure-1": [
 ("Identify the initial investment cost", "Appraisal begins with the outlay"),
 ("Estimate the annual net cash flows", "Future returns are forecast"),
 ("Select the discount rate", "The rate prices time and risk"),
 ("Apply discount factors to each year", "Cash flows become present values"),
 ("Total the present values", "Discounted returns are summed"),
 ("Deduct the outlay to find NPV", "A positive NPV supports investing"),
],
"business-studies-ibdp-hl-hl-extension-business-strategy-and-decision-making-adventure-1": [
 ("State the vision and mission", "Strategy flows down from purpose"),
 ("Analyse the internal and external environment", "Position is assessed before objectives"),
 ("Set SMART strategic objectives", "Targets follow the analysis"),
 ("Formulate the strategy", "The route to the objectives is designed"),
 ("Implement through tactics and plans", "Action operationalises the strategy"),
 ("Evaluate and keep contingencies ready", "Control closes the strategic loop"),
],
"business-studies-ibdp-hl-introduction-to-business-management-adventure-1": [
 ("Grower farms the coffee beans (primary)", "Production chains start in the primary sector"),
 ("Processor roasts the beans (secondary)", "Manufacturing adds value to the crop"),
 ("Packager prepares retail products (secondary)", "Further processing readies goods for sale"),
 ("Logistics firm ships the coffee (tertiary)", "Services move the product onward"),
 ("Cafe brews and serves it (tertiary)", "Retail service reaches the customer"),
 ("Consumer drinks the coffee", "Consumption ends the chain"),
],
"business-studies-ibdp-human-resource-management-adventure-1": [
 ("Forecast future staffing demand", "Workforce planning starts with future needs"),
 ("Audit the current workforce supply", "Existing skills and numbers are mapped"),
 ("Identify the workforce gap", "Demand minus supply reveals the shortfall"),
 ("Plan recruitment and training to close it", "Actions are designed for the gap"),
 ("Implement the workforce plan", "Hiring and training are carried out"),
 ("Evaluate against staffing targets", "Review completes the planning cycle"),
],
"business-studies-ibdp-marketing-adventure-1": [
 ("Carry out market research", "Customer insight precedes all targeting"),
 ("Segment the market", "Research splits customers into groups"),
 ("Choose target segments", "Selection follows segmentation"),
 ("Develop the market position", "A distinct place in customers' minds is staked"),
 ("Design the marketing mix", "The 7Ps execute the chosen position"),
 ("Monitor and refine the strategy", "Feedback loops end the process"),
],
"business-studies-ibdp-operations-management-adventure-1": [
 ("Forecast the demand", "Operations plans are sized from expected sales"),
 ("Decide capacity and production method", "Job, batch or flow is matched to demand"),
 ("Procure materials through the supply chain", "Inputs arrive before production"),
 ("Produce the goods or services", "Transformation is the core of operations"),
 ("Apply quality management checks", "Standards are verified after production"),
 ("Deliver to the customer", "Distribution finishes the cycle"),
],
"business-studies-ibdp-sl-finance-and-accounts-adventure-1": [
 ("Establish the fixed costs", "Break-even needs the costs that never vary"),
 ("Establish unit variable cost and price", "Per-unit figures complete the inputs"),
 ("Compute the unit contribution", "Price minus variable cost per unit"),
 ("Divide fixed costs by the contribution", "The quotient is the break-even quantity"),
 ("Mark break-even on the chart", "Where total revenue crosses total cost"),
 ("Read off the margin of safety", "Current output minus break-even comes last"),
],
"business-studies-ibdp-sl-introduction-to-business-management-adventure-1": [
 ("Recognise an unmet customer need", "Every new enterprise begins with a need"),
 ("Research the potential market", "Evidence sizes the opportunity"),
 ("Prepare the business plan", "The venture is set out on paper"),
 ("Raise capital from chosen sources", "Finance follows a convincing plan"),
 ("Set up operations and launch", "The business starts trading"),
 ("Review performance against objectives", "Early results are evaluated"),
],
"business-studies-ibdp-stakeholders--csr-adventure-1": [
 ("List all the stakeholders", "Mapping starts with identifying every group"),
 ("Rate each group's power and interest", "Two dimensions are scored for each stakeholder"),
 ("Plot them on the power-interest grid", "Scores position groups on the matrix"),
 ("Choose a strategy for each quadrant", "Manage closely, keep satisfied, or monitor"),
 ("Engage and communicate accordingly", "The strategies are put into practice"),
 ("Monitor shifts in stakeholder positions", "Review keeps the map current"),
],
"business-studies-ibdp-strategy--decision-making-adventure-1": [
 ("Mission statement", "The broadest statement of purpose comes first"),
 ("Aims", "Long-term ambitions flow from the mission"),
 ("SMART objectives", "Specific measurable targets sharpen the aims"),
 ("Strategy", "The long-term plan to hit the objectives"),
 ("Tactics", "Short-term actions deliver the strategy"),
 ("Review and control", "Checking results closes the planning chain"),
],

# ---------- BUSINESS KS3 ----------
"business-studies-ks3-business-plans-adventure-1": [
 ("Have the business idea", "A plan exists to test an idea, so the idea comes first"),
 ("Research customers and competitors", "Facts are gathered before writing"),
 ("Forecast the costs and sales", "Numbers are estimated from the research"),
 ("Write the business plan", "Idea, research and numbers go into the document"),
 ("Pitch the plan to a bank or investor", "The finished plan is used to raise money"),
 ("Launch and check progress against it", "The plan guides the running business"),
],
"business-studies-ks3-customers--markets-adventure-1": [
 ("Decide what you need to know", "Research starts with clear questions"),
 ("Write the survey questions", "The questionnaire is built from those questions"),
 ("Ask a sample of people", "Data is collected with the survey"),
 ("Tally up the answers", "Responses are counted after collection"),
 ("Look for patterns in the results", "Analysis follows the counting"),
 ("Use the findings to decide", "Decisions are the point of the research"),
],
"business-studies-ks3-enterprise--startup-adventure-1": [
 ("Spot a gap in the market", "Enterprise begins with an unmet need"),
 ("Think up a product idea", "The idea answers the spotted gap"),
 ("Test the idea on possible customers", "Feedback checks the idea before spending"),
 ("Work out costs and set a price", "The numbers must work before launch"),
 ("Launch and start selling", "Trading begins once it all adds up"),
 ("Review how it went", "Looking back ends the start-up journey"),
],
"business-studies-ks3-entrepreneurship-skills-adventure-1": [
 ("Spot an opportunity", "Entrepreneurs start by seeing what others miss"),
 ("Refine the idea creatively", "The raw idea is shaped and improved"),
 ("Plan the time and money needed", "Organisation comes before the leap"),
 ("Take the calculated risk and launch", "Risk-taking turns the plan into a business"),
 ("Review, adapt and improve", "Resilience and learning come after launch"),
],
"business-studies-ks3-finance--profit-adventure-1": [
 ("Revenue: money in from sales", "Counting income is always the first line"),
 ("Take off the cost of making the goods", "Direct costs are subtracted from revenue"),
 ("Gross profit", "What's left after the making costs"),
 ("Take off other costs like rent and wages", "Overheads come off next"),
 ("Net profit: the final figure", "What the business truly keeps, at the bottom"),
],
"business-studies-ks3-goods--services-adventure-1": [
 ("Farmer grows the cocoa beans", "Goods begin as raw materials (primary sector)"),
 ("Factory makes the chocolate bars", "Manufacturing turns beans into goods (secondary)"),
 ("Lorry delivers bars to the shops", "Transport is a service moving goods (tertiary)"),
 ("Shop sells the chocolate", "Retail is the service at the end of the chain"),
 ("Customer buys and enjoys it", "Consumption finishes the journey"),
],
"business-studies-ks3-marketing--customers-adventure-1": [
 ("Find out what customers want", "Listening comes before any designing"),
 ("Choose which customers to aim at", "A target group is picked from the research"),
 ("Design a product they will like", "The product is made to fit the target group"),
 ("Set a fair price", "Pricing follows the product decisions"),
 ("Advertise to spread the word", "Promotion announces the finished offer"),
 ("Sell and collect feedback", "Customer reactions complete the loop"),
],
"business-studies-ks3-people--operations-adventure-1": [
 ("Order the raw materials", "Making anything starts with the inputs"),
 ("Make the product", "Production turns materials into goods"),
 ("Check the quality", "Inspection follows the making"),
 ("Package the product", "Packing protects the checked goods"),
 ("Deliver to the shop", "Distribution moves goods to the seller"),
 ("Serve the customer", "The sale is the final step"),
],
"business-studies-ks3-types-of-business-adventure-1": [
 ("Sole trader", "One person owns it all - the smallest business type"),
 ("Partnership", "Two or more partners share the business"),
 ("Private limited company (Ltd)", "Shares are owned privately; owners get limited liability"),
 ("Public limited company (plc)", "Anyone can buy shares on the stock market"),
 ("Multinational", "A giant operating in many countries"),
],
"business-studies-ks3-workplace-roles-adventure-1": [
 ("Apprentice or trainee", "The starting rung: learning the job"),
 ("Team member", "Day-to-day workers carry out the tasks"),
 ("Supervisor or team leader", "First level of responsibility over others"),
 ("Manager", "Runs a department and its supervisors"),
 ("Director", "Sets strategy for a whole area of the business"),
 ("Chief executive (CEO)", "The top of the hierarchy, leading everything"),
],
}
