# Batch 9 sequences, part 1: Art & Design
SEQ1 = {

# ---------- ART & DESIGN A-LEVEL ----------
"art-design-a-level-aqa-art-craft-and-design-adventure-1": [
 ("Choose a theme and starting points", "Every project opens by defining the focus all later work grows from"),
 ("Research artists and contexts", "Sources are gathered next so ideas develop from informed study"),
 ("Record observations from primary sources", "Drawings and photos collect raw material before experiments begin"),
 ("Experiment with media and techniques", "Trials test how the recorded material can be handled"),
 ("Develop and refine selected ideas", "The strongest experiments are pushed towards resolution"),
 ("Produce the final resolved outcome", "The finished piece concludes the project journey"),
],
"art-design-a-level-aqa-component-1-personal-investigation-practical-and-written-element-adventure-1": [
 ("Select a personal line of enquiry", "The investigation starts with a question or theme to pursue"),
 ("Gather artist, contextual and source research", "Research must inform the enquiry before practical work develops"),
 ("Develop practical studies and experiments", "Making explores the enquiry once research gives direction"),
 ("Draft the related written study (1,000-3,000 words)", "AQA's essay is drafted once practical enquiry gives it substance"),
 ("Refine work towards resolved outcomes", "Refinement follows drafting as ideas consolidate"),
 ("Present outcomes with the written element", "Submission of practical plus writing ends Component 1"),
],
"art-design-a-level-aqa-component-2-externally-set-assignment-adventure-1": [
 ("Exam paper issued from 1 February", "AQA releases the A-level starting points on or after 1 Feb"),
 ("Choose one starting point", "A single question is selected from the paper"),
 ("Preparatory period: research and develop", "Supporting studies are made in the weeks before the exam"),
 ("Plan the final piece", "Composition and materials are decided before timed work"),
 ("15 hours of supervised time", "The final outcome is made in sustained focus sessions"),
 ("Work submitted for marking", "All prep work and the outcome go forward together"),
],
"art-design-a-level-aqa-fine-art-adventure-1": [
 ("Prime the canvas with gesso", "A prepared ground must exist before any paint is applied"),
 ("Sketch the underdrawing", "Light drawing maps the composition on the dry ground"),
 ("Block in the underpainting", "Thin lean layers establish tone before colour builds"),
 ("Build colour layers, fat over lean", "Oilier paint must sit on leaner layers to avoid cracking"),
 ("Add final details and highlights", "Fine work sits on top of the built-up layers"),
 ("Varnish once fully dry", "Varnish is always the last step, after months of drying for oils"),
],
"art-design-a-level-aqa-graphic-communication-adventure-1": [
 ("Receive and analyse the client brief", "Design work cannot start until requirements are understood"),
 ("Research and build a moodboard", "Visual research informs the ideas stage"),
 ("Sketch thumbnail concepts", "Quick roughs explore many options cheaply on paper"),
 ("Develop the chosen concept digitally", "One route is refined in design software"),
 ("Present for feedback and revise", "Client comments drive amendments before sign-off"),
 ("Deliver final artwork files", "Print-ready or screen-ready files end the job"),
],
"art-design-a-level-aqa-photography-adventure-1": [
 ("Load film and set exposure", "The shoot begins with film in the camera and metered settings"),
 ("Compose and shoot the frames", "Images are captured before any processing can happen"),
 ("Process film in developer", "Developer is always the first chemical bath"),
 ("Transfer to stop bath", "Stop halts development immediately after the developer"),
 ("Fix the negatives", "Fixer makes the image permanent after the stop bath"),
 ("Wash, dry and print", "Cleaned negatives are dried, then enlarged into prints"),
],
"art-design-a-level-aqa-textile-design-adventure-1": [
 ("Design the motif and cut the stencil", "Screen printing starts with the design to be printed"),
 ("Prepare the screen", "The stencil is fixed to the mesh before any ink is used"),
 ("Mix the fabric inks", "Inks are prepared before printing can begin"),
 ("Pull prints with the squeegee", "Ink is forced through the screen onto the cloth"),
 ("Heat-set the printed fabric", "Heat fixes the ink so it survives washing"),
 ("Finish and present the textile piece", "Hemming and finishing complete the work"),
],
"art-design-a-level-aqa-three-dimensional-design-adventure-1": [
 ("Wedge the clay", "Air bubbles are removed first or the piece can explode in the kiln"),
 ("Build the basic form", "Construction follows once the clay is prepared"),
 ("Join and refine at leather-hard", "Slip-and-score joins only work at the leather-hard stage"),
 ("Dry to bone dry", "Clay must be fully dry before it can be fired safely"),
 ("Bisque fire the piece", "The first firing around 1000C hardens the dry clay"),
 ("Glaze and glaze fire", "Glaze goes on bisque ware; the second firing melts it to glass"),
],
"art-design-a-level-ccea-unit-a2-1-personal-and-critical-investigation-adventure-1": [
 ("Define the personal investigation theme", "The unit opens by fixing a line of enquiry"),
 ("Carry out critical and contextual research", "Artists and contexts are studied to inform the work"),
 ("Explore the theme through practical work", "Making responds to the research findings"),
 ("Draft the written investigation", "The critical writing develops from research and practice"),
 ("Refine practical and written elements", "Both strands are polished together near the end"),
 ("Present the completed investigation", "Submission closes Unit A2 1"),
],
"art-design-a-level-ccea-unit-a2-2-thematic-outcome-adventure-1": [
 ("Review the A2 1 investigation", "A2 2 must build on the personal and critical investigation"),
 ("Identify ideas to take forward", "Selection narrows the investigation into a direction"),
 ("Produce planning and preparatory studies", "Studies test how the outcome will work"),
 ("Trial materials and compositions", "Final decisions are checked before committing"),
 ("Create the thematic outcome", "The resolved piece is made from the tested plan"),
 ("Present the outcome for assessment", "Submission completes the A2 year"),
],
"art-design-a-level-ccea-unit-as-1-experimental-portfolio-adventure-1": [
 ("Engage with the chosen theme", "The portfolio starts from a theme or stimulus"),
 ("Research sources and artists", "Investigation feeds the experiments that follow"),
 ("Experiment broadly across media", "Wide-ranging trials are the heart of this unit"),
 ("Review and select promising directions", "Evaluation picks which experiments to pursue"),
 ("Develop the selected ideas further", "Chosen routes are pushed in more depth"),
 ("Present the experimental portfolio", "The assembled portfolio is submitted"),
],
"art-design-a-level-ccea-unit-as-2-personal-response-adventure-1": [
 ("Review the AS 1 experimental portfolio", "AS 2 grows directly out of the AS 1 experiments"),
 ("Define the intention for a personal response", "A clear direction is set from the strongest ideas"),
 ("Make preparatory and planning studies", "Studies resolve composition and materials"),
 ("Produce the personal response outcome", "The resolved work is made from the plan"),
 ("Evaluate and present for assessment", "Presentation closes the AS year"),
],
"art-design-a-level-critical--contextual-studies-adventure-1": [
 ("First impressions", "Initial gut response is noted before structured study begins"),
 ("Description: what can be seen", "Feldman's method lists literal content before judging anything"),
 ("Formal analysis: how it is made", "Line, colour and composition are examined after describing"),
 ("Research the context", "Artist, period and purpose deepen the analysis"),
 ("Interpretation: what it means", "Meaning is argued from the evidence gathered"),
 ("Judgement: how successful it is", "Evaluation comes last, once evidence supports it"),
],
"art-design-a-level-curating--exhibitions-adventure-1": [
 ("Define the curatorial concept", "A show begins with the idea that links the works"),
 ("Select the artworks", "Works are chosen to serve the concept"),
 ("Design the layout and hang plan", "The space is planned around the chosen works"),
 ("Install the exhibition", "Works are hung and lit following the plan"),
 ("Open with the private view", "The launch event happens once installation is complete"),
 ("De-install and return the works", "Take-down is always the final stage of a show"),
],
"art-design-a-level-drawing--painting-adventure-1": [
 ("Thumbnail the composition", "Small studies settle the design before committing"),
 ("Lay a light underdrawing", "The drawing maps the image onto the support"),
 ("Block in a tonal underpainting", "Broad tones are set before colour detail"),
 ("Build up the colour layers", "Colour develops over the established tonal base"),
 ("Add details and highlights", "Fine marks sit on top of the layers"),
 ("Assess, adjust and finish", "Final corrections complete the painting"),
],
"art-design-a-level-edexcel-component-1-personal-investigation-adventure-1": [
 ("Choose the theme of the investigation", "Component 1 starts with a personal line of enquiry"),
 ("Research artists, contexts and sources", "Critical understanding is built before development"),
 ("Record and experiment from the theme", "Practical exploration responds to the research"),
 ("Write the personal study (min 1,000 words)", "Edexcel's continuous prose grows from the enquiry so far"),
 ("Refine ideas towards resolution", "Development tightens once research and writing inform it"),
 ("Present resolved practical and written work", "Submission completes the component"),
],
"art-design-a-level-edexcel-component-2-externally-set-assignment-adventure-1": [
 ("Theme paper released on 1 February", "Edexcel issues the A-level externally set theme on 1 Feb"),
 ("Select a starting point to pursue", "One response route is chosen from the theme"),
 ("Develop preparatory studies", "Research and development fill the prep period"),
 ("Resolve the plan for the final piece", "Intentions are fixed before timed conditions"),
 ("Complete 15 hours of sustained focus", "The outcome is made under supervised timed conditions"),
 ("Submit prep work and outcome", "Everything is handed in for marking"),
],
"art-design-a-level-edexcel-fine-art-adventure-1": [
 ("Degrease and polish the metal plate", "Etching starts with a clean plate or the ground will not stick"),
 ("Apply the acid-resistant ground", "The waxy ground must coat the plate before drawing"),
 ("Draw through the ground with a needle", "Lines expose bare metal where the acid will bite"),
 ("Etch the plate in the acid bath", "Acid bites the drawn lines into the metal"),
 ("Ink the plate and wipe the surface", "Ink is pushed into the bitten lines after etching"),
 ("Print through the etching press", "Damp paper and pressure lift the image last"),
],
"art-design-a-level-edexcel-graphic-communication-adventure-1": [
 ("Take the design brief", "A logo job opens with the client's requirements"),
 ("Research the market and competitors", "Existing identities are studied before sketching"),
 ("Sketch rough concept ideas", "Many quick pencil routes are explored first"),
 ("Develop chosen marks as vectors", "Selected ideas are rebuilt precisely in software"),
 ("Present options and gather feedback", "The client responds before finalising"),
 ("Supply final brand files", "Approved artwork is exported and delivered"),
],
"art-design-a-level-edexcel-photography-adventure-1": [
 ("Plan the shoot and storyboard ideas", "Intentions and shot lists come before the camera"),
 ("Set up camera, exposure and lighting", "Technical settings are fixed before shooting"),
 ("Shoot the planned images", "Capture happens once planning and setup are done"),
 ("Import, back up and select images", "Files are secured and edited down after the shoot"),
 ("Edit the selected images", "Post-production refines the chosen frames"),
 ("Print or present the final set", "Output is the last stage of the workflow"),
],
"art-design-a-level-edexcel-textile-design-adventure-1": [
 ("Draw the batik design on cloth", "The design guides where wax will be placed"),
 ("Apply hot wax to areas staying pale", "Wax resists dye, so it must go on before dyeing"),
 ("Dye the fabric in the lightest colour", "Batik always dyes light colours before dark ones"),
 ("Re-wax and dye progressively darker", "Each wax layer protects the colour beneath"),
 ("Remove the wax by boiling or ironing", "The resist comes off only when dyeing is finished"),
 ("Finish and present the textile", "Hemming and mounting complete the piece"),
],
"art-design-a-level-edexcel-three-dimensional-design-adventure-1": [
 ("Sculpt the original model", "Lost-wax casting begins with the form to reproduce"),
 ("Make a mould of the model", "The mould captures the original's surface"),
 ("Cast a wax replica in the mould", "A hollow wax copy is produced from the mould"),
 ("Invest the wax in a ceramic shell", "The wax is coated to form the casting mould"),
 ("Burn out the wax and pour the bronze", "Molten metal fills the space the lost wax leaves"),
 ("Break out, chase and patinate", "Finishing the cast surface is the final stage"),
],
"art-design-a-level-ethics--theory-adventure-1": [
 ("Plato questions art as imitation (c.375 BC)", "The Republic attacks mimesis in ancient Greece"),
 ("Kant's Critique of Judgement (1790)", "Enlightenment aesthetics defines disinterested beauty"),
 ("Tolstoy's What Is Art? (1897)", "Art judged by sincere transmission of feeling"),
 ("Benjamin on mechanical reproduction (1936)", "Photography and film said to strip the artwork's aura"),
 ("Barthes declares the death of the author (1967)", "Meaning shifts from artist's intent to the viewer"),
 ("Berger's Ways of Seeing (1972)", "TV series and book popularise critical looking"),
],
"art-design-a-level-mixed-media--installation-adventure-1": [
 ("Picasso glues caning into a painting (1912)", "Still Life with Chair Caning pioneers fine-art collage"),
 ("Duchamp submits Fountain (1917)", "The readymade urinal redefines what art can be"),
 ("Schwitters begins the Merzbau (1923)", "A whole room becomes a growing assemblage"),
 ("Rauschenberg starts his Combines (1954)", "Painting and found objects merge mid-century"),
 ("Kusama's Infinity Mirror Room (1965)", "Immersive installation envelops the viewer"),
 ("Tate Turbine Hall commissions begin (2000)", "Vast installations reach mass audiences"),
],
"art-design-a-level-modernism--avant-garde-adventure-1": [
 ("Impressionism's first exhibition (1874)", "Monet and friends show loose, light-led painting in Paris"),
 ("Post-Impressionism emerges (1880s)", "Cezanne, Van Gogh and Seurat push beyond Impressionism"),
 ("Fauvism shocks the Salon (1905)", "Matisse's wild colour earns the name 'wild beasts'"),
 ("Cubism begins with Les Demoiselles (1907)", "Picasso fractures form into multiple viewpoints"),
 ("Dada erupts at Cabaret Voltaire (1916)", "Anti-art protest born amid the First World War"),
 ("Surrealist Manifesto published (1924)", "Breton launches the art of dreams and the unconscious"),
],
"art-design-a-level-ocr-component-01-personal-investigation-adventure-1": [
 ("Agree a personal line of enquiry", "OCR's investigation opens with a chosen focus"),
 ("Investigate artists and contexts", "Critical research underpins the developing work"),
 ("Record and experiment from sources", "Practical exploration follows the research"),
 ("Produce the related study", "The extended written element grows from the enquiry"),
 ("Refine towards resolved outcomes", "Ideas consolidate as the deadline nears"),
 ("Submit practical work and related study", "Both elements are presented for assessment"),
],
"art-design-a-level-ocr-component-02-externally-set-task-adventure-1": [
 ("OCR releases the set task themes (1 February)", "The early-February paper starts the component"),
 ("Choose one theme to answer", "A single starting point is selected"),
 ("Carry out preparatory studies", "Research and development precede timed work"),
 ("Finalise the plan for the outcome", "Decisions are fixed before the exam sessions"),
 ("Work 15 hours under supervision", "The final piece is made in timed conditions"),
 ("Hand in all work for marking", "Prep studies and outcome are assessed together"),
],
"art-design-a-level-ocr-critical-and-contextual-studies-adventure-1": [
 ("Record first impressions", "An honest initial response is captured before analysis"),
 ("Describe the work objectively", "Listing what is visible comes before explaining it"),
 ("Analyse the formal elements", "How line, tone and colour behave is studied next"),
 ("Investigate context and influences", "When, where and why the work was made adds depth"),
 ("Interpret the meaning", "An argued reading follows the evidence"),
 ("Evaluate and form a judgement", "Critical verdict is the final step of the method"),
],
"art-design-a-level-ocr-fine-art-adventure-1": [
 ("Stretch the canvas over its frame", "A painting support is built before priming"),
 ("Prime with layers of gesso", "Sealing the surface comes before any paint"),
 ("Map the underdrawing", "Composition is drawn onto the dry primed canvas"),
 ("Lay the underpainting", "Thin tonal paint establishes the structure"),
 ("Develop glazes and thicker layers", "Colour builds over the underpainting"),
 ("Varnish the finished painting", "Protection is applied only when work is complete and dry"),
],
"art-design-a-level-ocr-graphic-communication-adventure-1": [
 ("Analyse the poster brief", "Audience, message and format are clarified first"),
 ("Research the target audience", "Insight shapes the visual direction"),
 ("Generate concept sketches", "Rough visuals test possible routes"),
 ("Build the layout digitally", "The chosen route is set in design software"),
 ("Proof, check and amend", "Errors are corrected before output"),
 ("Send print-ready files", "Final delivery closes the project"),
],
"art-design-a-level-ocr-photography-adventure-1": [
 ("Plan the studio concept", "A portrait shoot starts with a clear intention"),
 ("Set the background and lighting", "The set is built before the sitter is posed"),
 ("Take metered test shots", "Tests confirm exposure before the real frames"),
 ("Adjust lighting from the tests", "Refinements respond to what the tests reveal"),
 ("Shoot the final portraits", "The proper take happens once setup is proven"),
 ("Edit and retouch the selects", "Post-production is the final stage"),
],
"art-design-a-level-ocr-textile-design-adventure-1": [
 ("Choose and prepare the dyestuff", "Natural dyeing starts with the plant material"),
 ("Scour the fabric clean", "Oils and dirt must be removed or dye takes unevenly"),
 ("Mordant the fabric", "The fixative must bond to fibres before the dye bath"),
 ("Simmer the dye bath", "Colour is extracted ready for the cloth"),
 ("Dye the fabric", "The mordanted cloth takes up the colour"),
 ("Rinse, dry and finish", "Excess dye is washed out at the end"),
],
"art-design-a-level-ocr-three-dimensional-design-adventure-1": [
 ("Sculpt the master model", "Slip casting begins with the form to reproduce"),
 ("Cast a plaster mould around it", "The mould is made from the master"),
 ("Pour slip into the dry mould", "Liquid clay fills the plaster cavity"),
 ("Drain the excess slip", "A wall thickness forms before pouring out the rest"),
 ("Demould and fettle the seams", "The leather-hard cast is cleaned of mould lines"),
 ("Bisque and glaze fire", "Two kiln firings complete the ceramic piece"),
],
"art-design-a-level-photography-history-adventure-1": [
 ("Niepce makes the first photograph (1826)", "View from the Window at Le Gras, an 8-hour exposure"),
 ("Daguerreotype announced (1839)", "Daguerre's process makes photography public in Paris"),
 ("Kodak roll-film camera launches (1888)", "'You press the button, we do the rest'"),
 ("Leica popularises 35mm (1925)", "Small cameras free photographers to roam"),
 ("Polaroid instant photography (1948)", "Land's camera develops pictures in minutes"),
 ("First digital camera built (1975)", "Sasson's Kodak prototype starts the digital era"),
],
"art-design-a-level-postmodern--contemporary-adventure-1": [
 ("Hamilton's pop collage (1956)", "Just What Is It... heralds British Pop Art"),
 ("Warhol's Campbell's Soup Cans (1962)", "Mass-produced imagery enters the gallery"),
 ("Sherman begins Untitled Film Stills (1977)", "Staged self-images question identity"),
 ("Hirst's shark in formaldehyde (1991)", "The YBAs make death a spectacle"),
 ("Emin's My Bed shown for the Turner Prize (1999)", "Confessional installation divides Britain"),
 ("Banksy shreds Girl with Balloon (2018)", "An auction-room stunt becomes the artwork"),
],
"art-design-a-level-renaissance-masters-adventure-1": [
 ("Giotto paints the Arena Chapel (c.1305)", "Padua frescoes bring new naturalism to painting"),
 ("Van Eyck's Arnolfini Portrait (1434)", "Northern oil technique stuns with detail"),
 ("Botticelli's Birth of Venus (c.1485)", "Florentine mythology blooms under the Medici"),
 ("Leonardo completes The Last Supper (1498)", "Milan mural perfects composition and drama"),
 ("Michelangelo's David unveiled (1504)", "The colossal marble defines High Renaissance sculpture"),
 ("Sistine Chapel ceiling finished (1512)", "Four years of frescoes crown the High Renaissance"),
],

# ---------- ART & DESIGN GCSE ----------
"art-design-gcse-3d--mixed-media-adventure-1": [
 ("Sketch the design and maquette ideas", "Planning on paper comes before any building"),
 ("Build the wire armature", "The skeleton must exist before bulk is added"),
 ("Bulk out with newspaper and tape", "Mass is added over the armature"),
 ("Apply modroc plaster bandage", "The wet plaster layer wraps the bulked form"),
 ("Smooth and let it dry", "Surfaces are refined while workable, then hardened"),
 ("Paint and seal the sculpture", "Decoration is only possible on the dry surface"),
],
"art-design-gcse-annotation--analysis-adventure-1": [
 ("Caption the source: artist, title, date", "Annotation starts by recording what you are studying"),
 ("Describe what you can see", "Objective description comes before any opinion"),
 ("Analyse the formal elements", "Explain how colour, line and composition work"),
 ("Interpret the artist's intentions", "Meaning is suggested after the evidence"),
 ("Evaluate and link to your own work", "Annotation ends by feeding your own project"),
],
"art-design-gcse-aqa-component-1-portfolio-personal-investigation-adventure-1": [
 ("Launch the portfolio theme", "Component 1 (60% of GCSE) opens with a theme"),
 ("Research relevant artists", "Artist studies inform the developing ideas"),
 ("Record from primary observation", "Drawings and photographs gather source material"),
 ("Experiment with media", "Techniques are trialled using the recorded sources"),
 ("Develop ideas towards an outcome", "The strongest route is pushed forward"),
 ("Complete the portfolio outcome", "A resolved piece concludes the project"),
],
"art-design-gcse-aqa-component-2-externally-set-assignment-adventure-1": [
 ("AQA issues the exam paper from 2 January", "GCSE starting points are released early in January"),
 ("Pick one starting point", "Students choose a single question to answer"),
 ("Use the preparatory period", "Research, recording and development fill the weeks before"),
 ("Plan the final response", "Composition and materials are settled in advance"),
 ("Sit the 10-hour supervised exam", "The final piece is made in timed sessions"),
 ("Submit prep work and exam piece", "Everything goes forward for marking"),
],
"art-design-gcse-aqa-drawing-and-visual-recording-adventure-1": [
 ("Sketch basic shapes lightly", "Faint simple forms map the subject first"),
 ("Check proportions and angles", "Measurements are corrected while marks are still light"),
 ("Refine the outlines", "Accurate contours firm up the corrected drawing"),
 ("Block in the mid-tones", "Working light to dark, middle values come first"),
 ("Deepen the darkest tones", "Darks are pushed once mid-tones sit correctly"),
 ("Add details and highlights", "Finishing touches complete the study"),
],
"art-design-gcse-aqa-graphic-communication-adventure-1": [
 ("Unpack the design brief", "Purpose and audience are defined before designing"),
 ("Build research and moodboards", "Influences are collected to spark ideas"),
 ("Thumbnail many quick ideas", "Rough small sketches explore the options"),
 ("Develop the chosen idea digitally", "One concept is refined on screen"),
 ("Test against the brief and tweak", "The design is checked against requirements"),
 ("Produce the final outcome", "Finished artwork answers the brief"),
],
"art-design-gcse-aqa-painting-and-mixed-media-adventure-1": [
 ("Prepare and tone the ground", "A coloured ground readies the surface first"),
 ("Sketch the composition", "The drawing goes onto the prepared surface"),
 ("Block in big shapes with thin paint", "Broad areas are laid before detail"),
 ("Build thicker layers over thin", "Paint strengthens gradually, thick over thin"),
 ("Add collage and surface textures", "Mixed-media elements sit on the built layers"),
 ("Finish with details and edges", "Final refinement completes the piece"),
],
"art-design-gcse-aqa-photography-and-lens-based-media-adventure-1": [
 ("Collect objects for the photogram", "Interesting silhouettes are gathered first"),
 ("Arrange objects on photo paper in the darkroom", "Composition happens under safelight"),
 ("Expose to the enlarger light", "Light prints the shadows of the objects"),
 ("Slide the paper into developer", "The image appears in the first chemical tray"),
 ("Stop and fix the print", "Stop bath then fixer make the image permanent"),
 ("Wash and dry the photogram", "Rinsing chemicals away is the final step"),
],
"art-design-gcse-aqa-sculpture-and-three-dimensional-studies-adventure-1": [
 ("Wedge and prepare the clay", "Air pockets are removed before building"),
 ("Form the base of the pot", "Construction starts from the bottom"),
 ("Build the walls up with coils", "Coils are added row by row above the base"),
 ("Blend and refine at leather-hard", "Smoothing works best at the leather-hard stage"),
 ("Dry the pot completely", "Bone-dry clay is required before firing"),
 ("Bisque fire, then glaze fire", "Two kiln firings finish the ceramic"),
],
"art-design-gcse-aqa-textile-design-adventure-1": [
 ("Wash and prepare the fabric", "Clean cloth takes tie-dye evenly"),
 ("Fold and bind with bands", "The resist pattern is created by the binding"),
 ("Apply the dye", "Colour goes on only after the cloth is bound"),
 ("Leave the dye to set", "Time lets the colour bond with the fibres"),
 ("Rinse and remove the bindings", "Excess dye is washed out before the reveal"),
 ("Unfold, dry and press the pattern", "The finished design appears at the end"),
],
"art-design-gcse-art-movements-overview-adventure-1": [
 ("Renaissance (from c.1400)", "Perspective and naturalism revive classical ideals"),
 ("Baroque (from c.1600)", "Drama and intense light follow the Renaissance"),
 ("Romanticism (early 1800s)", "Emotion and wild nature answer the industrial age"),
 ("Impressionism (1870s)", "Painters chase fleeting light outdoors in France"),
 ("Cubism (from 1907)", "Picasso and Braque fracture form into facets"),
 ("Pop Art (1950s-60s)", "Advertising and mass culture enter the gallery"),
],
"art-design-gcse-cambridge-igcse-component-1-observational-interpretative-assignment-adventure-1": [
 ("Select the subject or still life", "The assignment opens with a chosen source to study"),
 ("Make observational studies", "Direct recording builds understanding of the subject"),
 ("Trial different media", "Experiments find the best way to interpret the source"),
 ("Develop compositional ideas", "Studies are arranged into possible final designs"),
 ("Refine the chosen composition", "The selected design is resolved in detail"),
 ("Produce the final piece", "The resolved outcome completes the assignment"),
],
"art-design-gcse-cambridge-igcse-component-2-design-assignment-adventure-1": [
 ("Read and analyse the design brief", "Requirements are understood before designing"),
 ("Research the problem and influences", "Investigation grounds the ideas stage"),
 ("Sketch initial thumbnail ideas", "Many quick options are generated first"),
 ("Develop the chosen design", "One route is taken forward in depth"),
 ("Test materials and refine", "Trials polish the design before the final"),
 ("Realise the final design", "The finished design answers the brief"),
],
"art-design-gcse-cambridge-igcse-component-3-coursework-adventure-1": [
 ("Establish the coursework theme", "A personal focus launches the project"),
 ("Gather research and references", "Sources and artists inform the work"),
 ("Record from first-hand sources", "Observation supplies original material"),
 ("Experiment and take risks with media", "Trials expand the visual language"),
 ("Develop a sustained line of ideas", "The project deepens towards resolution"),
 ("Present the final coursework outcome", "A resolved piece ends the project"),
],
"art-design-gcse-cambridge-igcse-graphic-communication-adventure-1": [
 ("Define the packaging brief", "Product, audience and format are set first"),
 ("Research existing packaging", "Competitor analysis informs the design"),
 ("Sketch concepts and the net", "Ideas and the box net are roughed out on paper"),
 ("Create the artwork digitally", "Graphics are built in software"),
 ("Make a physical mock-up", "A prototype tests the design in 3D"),
 ("Finalise print-ready files", "Production files complete the job"),
],
"art-design-gcse-cambridge-igcse-painting-and-related-media-adventure-1": [
 ("Draw a light pencil plan", "Watercolour starts over a faint drawing"),
 ("Reserve or mask the highlights", "Whites must be protected before any wash"),
 ("Lay the palest washes first", "Watercolour always works light to dark"),
 ("Build the mid-tone washes", "Stronger colour goes over dry pale layers"),
 ("Paint the darkest details last", "Deep accents come at the end of the build-up"),
 ("Remove masking and finish", "Final touches reveal the protected lights"),
],
"art-design-gcse-cambridge-igcse-photography-and-digital-media-adventure-1": [
 ("Plan the shoot and shot list", "Intent is decided before picking up the camera"),
 ("Set exposure and camera settings", "Technical choices precede shooting"),
 ("Shoot the images", "Capture follows the plan"),
 ("Import and back up the files", "Images are secured straight after the shoot"),
 ("Edit and enhance the selects", "Post-production refines the best frames"),
 ("Export and present the final set", "Output for display ends the workflow"),
],
"art-design-gcse-cambridge-igcse-textiles-adventure-1": [
 ("Lay out the wool fibres in layers", "Felt begins with crossed layers of loose fibre"),
 ("Wet with warm soapy water", "Moisture and soap prepare the fibres to bond"),
 ("Rub and roll to felt the fibres", "Agitation locks the fibres into fabric"),
 ("Rinse the felt clean", "Soap is washed out once the felt holds"),
 ("Shape and dry the felt", "The damp fabric is formed and left to dry"),
 ("Embellish with stitch or applique", "Decoration is added to the finished felt"),
],
"art-design-gcse-cambridge-igcse-three-dimensional-design-adventure-1": [
 ("Produce design drawings", "Ideas are resolved on paper before making"),
 ("Build a small maquette", "A scale model tests the design cheaply"),
 ("Select and prepare materials", "Materials are chosen from what the maquette shows"),
 ("Construct the main structure", "The full piece is built from the tested plan"),
 ("Apply the surface finish", "Finishing goes onto the completed structure"),
 ("Evaluate against the intention", "Review closes the design cycle"),
],
"art-design-gcse-ccea-component-1-exploratory-portfolio-adventure-1": [
 ("Respond to the given theme", "The portfolio opens with the chosen stimulus"),
 ("Research artists and contexts", "Sources are investigated to fuel exploration"),
 ("Record from observation", "First-hand studies gather material"),
 ("Explore media experimentally", "Broad trials are the core of this component"),
 ("Review and develop the best ideas", "Selection focuses the exploration"),
 ("Present the exploratory portfolio", "The assembled portfolio is submitted"),
],
"art-design-gcse-ccea-component-2-investigating-the-creative-and-cultural-industries-adventure-1": [
 ("Choose an industry or practitioner focus", "The investigation starts with a chosen subject"),
 ("Research roles, products and practices", "Finding out how the industry works comes next"),
 ("Analyse examples of professional work", "Close study deepens the research"),
 ("Develop a creative response", "Own work grows out of the investigation"),
 ("Refine the response", "The outcome is polished before presenting"),
 ("Present findings and outcome", "Submission completes the component"),
],
"art-design-gcse-ccea-component-3-externally-set-assignment-adventure-1": [
 ("CCEA releases the stimulus paper", "The externally set theme starts the component"),
 ("Choose a response route", "One direction is selected from the stimulus"),
 ("Research and develop ideas", "Preparatory work explores the chosen route"),
 ("Plan the final outcome", "Decisions are fixed before supervised time"),
 ("Make the outcome in supervised sessions", "The piece is completed under controlled conditions"),
 ("Submit all work for assessment", "Preparation and outcome are marked together"),
],
"art-design-gcse-critical-analysis-terms-adventure-1": [
 ("Content: identify what is shown", "Analysis begins with the subject matter itself"),
 ("Describe the key features", "Objective description precedes explanation"),
 ("Analyse form and process", "How the work is composed and made comes next"),
 ("Consider mood and meaning", "Interpretation builds on the evidence gathered"),
 ("Set the work in context", "Artist, time and place frame the reading"),
 ("Judge its success", "Evaluation is the final step of analysis"),
],
"art-design-gcse-drawing--composition-adventure-1": [
 ("Make thumbnail sketches", "Tiny roughs test arrangements before committing"),
 ("Choose format and viewpoint", "Landscape or portrait, high or low, is decided next"),
 ("Place the focal point on the thirds", "The rule of thirds positions the key element"),
 ("Draw light construction lines", "The full drawing is mapped faintly first"),
 ("Build the tonal structure", "Light and dark develop over the mapping"),
 ("Refine the final details", "Finishing marks complete the composition"),
],
"art-design-gcse-edexcel-art-craft-and-design-mixed-media-adventure-1": [
 ("Choose a theme and gather materials", "Papers, fabrics and ephemera are collected first"),
 ("Lay the background collage layers", "The base layer must go down before anything on top"),
 ("Add the main imagery over the base", "Mid layers build on the background"),
 ("Work surface details and stitch on top", "Fine elements sit above the imagery"),
 ("Unify with washes or glazes", "Linking layers pull the surface together"),
 ("Seal and present the piece", "Protection and mounting finish the work"),
],
"art-design-gcse-edexcel-component-1-personal-portfolio-adventure-1": [
 ("Begin the personal portfolio theme", "Component 1 (60% of the GCSE) starts with a theme"),
 ("Investigate artists and sources", "Research feeds the developing ideas"),
 ("Record observations and insights", "First-hand material is gathered next"),
 ("Experiment with techniques", "Media trials test the gathered material"),
 ("Develop and refine a direction", "The strongest idea is pushed to resolution"),
 ("Realise the portfolio outcome", "A finished response completes the project"),
],
"art-design-gcse-edexcel-component-2-externally-set-assignment-adventure-1": [
 ("Edexcel releases the theme paper in January", "The externally set theme opens the component"),
 ("Select a starting point", "One route into the theme is chosen"),
 ("Build preparatory studies", "Research and development fill the prep weeks"),
 ("Settle the final plan", "The outcome is designed before timed work"),
 ("Complete 10 hours of sustained focus", "The piece is made under supervised conditions"),
 ("Hand in prep and outcome", "All work is submitted for marking"),
],
"art-design-gcse-edexcel-fine-art-drawing-painting-printmaking-sculpture-adventure-1": [
 ("Set the project theme", "A fine art project begins with its focus"),
 ("Study relevant artists", "Research shapes the visual direction"),
 ("Record through drawing", "Observational drawing gathers source material"),
 ("Trial paint, print and 3D media", "Experiments test which discipline serves the idea"),
 ("Develop the strongest route", "One direction is refined in depth"),
 ("Resolve the final piece", "The finished work concludes the project"),
],
"art-design-gcse-edexcel-graphic-communication-adventure-1": [
 ("Receive the album cover brief", "The job starts with artist, genre and format"),
 ("Research the genre and audience", "Visual codes of the genre are studied"),
 ("Sketch cover concepts", "Quick roughs explore type and image ideas"),
 ("Develop the design digitally", "The chosen concept is built on screen"),
 ("Review against the brief", "The design is checked with fresh eyes"),
 ("Export the final artwork", "Print-ready files complete the commission"),
],
"art-design-gcse-edexcel-igcse-drawing-and-painting-adventure-1": [
 ("Plan the composition with studies", "Preparatory sketches settle the design"),
 ("Draw the image lightly onto the support", "Faint mapping precedes any paint"),
 ("Underpaint the broad tones", "Big tonal areas are established first"),
 ("Develop colour over the underpainting", "Colour layers build on the tonal base"),
 ("Strengthen darks and details", "Depth and precision come late in the build"),
 ("Add final highlights", "The lightest accents finish the painting"),
],
"art-design-gcse-edexcel-igcse-mixed-media-adventure-1": [
 ("Collect papers, fabrics and found media", "Materials are sourced before layering starts"),
 ("Prepare the support surface", "A sound base is readied for collage"),
 ("Glue down the background layers", "The lowest layers must be fixed first"),
 ("Layer imagery and texture above", "Each new layer sits on the one before"),
 ("Add drawn and stitched details on top", "Fine marks belong on the upper surface"),
 ("Seal and mount the finished piece", "Finishing protects the layered work"),
],
"art-design-gcse-edexcel-igcse-paper-1-personal-portfolio-adventure-1": [
 ("Choose the portfolio focus", "Paper 1 begins with a personal theme"),
 ("Carry out artist research", "Investigation informs the work to come"),
 ("Record from primary sources", "Observed material anchors the project"),
 ("Experiment across techniques", "Trials open up the possibilities"),
 ("Develop ideas with intent", "A clear direction is refined"),
 ("Present the resolved portfolio", "The finished body of work is submitted"),
],
"art-design-gcse-edexcel-igcse-paper-2-externally-set-assignment-adventure-1": [
 ("Externally set theme released", "Paper 2 starts when the theme arrives"),
 ("Pick an angle on the theme", "A personal route is chosen"),
 ("Research and develop responses", "Preparatory studies explore the route"),
 ("Plan the final outcome", "The timed piece is designed in advance"),
 ("Make the outcome in the timed exam", "Supervised sessions produce the final work"),
 ("Submit preparation and outcome", "Marking covers the whole journey"),
],
"art-design-gcse-edexcel-igcse-photography-and-digital-imagery-adventure-1": [
 ("Import and back up the shoot", "Files are secured before any editing"),
 ("Cull and select the best frames", "Editing starts by choosing what to keep"),
 ("Make global corrections first", "Exposure and white balance fix the whole image"),
 ("Retouch local areas", "Targeted fixes follow the global pass"),
 ("Apply creative grading", "The look is styled once the image is corrected"),
 ("Sharpen and export for output", "Output sharpening is always the last step"),
],
"art-design-gcse-edexcel-igcse-three-dimensional-studies-adventure-1": [
 ("Roll an even clay slab", "The relief tile starts from a flat slab"),
 ("Cut the tile to size", "The format is fixed before modelling"),
 ("Build up and carve the relief", "Adding and cutting create the design"),
 ("Refine at leather-hard", "Crisp finishing works at the leather-hard stage"),
 ("Dry the tile fully", "Bone-dry clay is needed for safe firing"),
 ("Bisque fire, then glaze", "Kiln firings complete the tile"),
],
"art-design-gcse-edexcel-photography-adventure-1": [
 ("Make a contact sheet of the film", "Every frame is reviewed in miniature first"),
 ("Select the negative to print", "The best frame is chosen from the contacts"),
 ("Expose a test strip", "Strips reveal the correct exposure time"),
 ("Expose the full print", "The print uses the time the test proved"),
 ("Develop, stop and fix", "Chemistry processes the print in strict order"),
 ("Wash and dry the print", "Cleaning chemicals away finishes the job"),
],
"art-design-gcse-edexcel-textile-design-adventure-1": [
 ("Design the applique motif", "The pattern is planned on paper first"),
 ("Select and prepare the fabrics", "Cloth choices serve the design"),
 ("Cut out the fabric shapes", "Pieces are cut from the chosen fabrics"),
 ("Pin and tack the shapes in place", "Temporary fixing precedes permanent stitch"),
 ("Stitch the shapes down", "Machine or hand stitch makes it permanent"),
 ("Press and finish the piece", "A final press completes the textile"),
],
"art-design-gcse-edexcel-three-dimensional-design-adventure-1": [
 ("Sketch design ideas", "Drawing resolves the concept before making"),
 ("Model a quick maquette", "A test model checks the idea in 3D"),
 ("Mark out and cut the materials", "Accurate parts are prepared from the plan"),
 ("Assemble the structure", "Parts join into the full form"),
 ("Sand and apply the finish", "Surface treatment follows construction"),
 ("Evaluate the outcome", "Review against the design intent comes last"),
],
"art-design-gcse-final-outcome-adventure-1": [
 ("Review all development work", "The outcome grows from everything in the sketchbook"),
 ("Select the strongest idea", "One direction is chosen from the development"),
 ("Plan with a mock-up or study", "A final rehearsal removes surprises"),
 ("Prepare materials and surface", "Everything is readied before the final make"),
 ("Create the final piece", "Sustained focused work realises the plan"),
 ("Evaluate against your intentions", "Reflection closes the project"),
],
"art-design-gcse-ocr-component-01-portfolio-adventure-1": [
 ("Start the portfolio project theme", "Component 01 (60%) opens with a chosen focus"),
 ("Research artists and contexts", "Sources guide the developing ideas"),
 ("Record ideas and observations", "First-hand material is collected"),
 ("Experiment with materials", "Trials test the possibilities"),
 ("Develop a personal response", "Refinement targets a resolved outcome"),
 ("Present the completed portfolio", "Submission ends the component"),
],
"art-design-gcse-ocr-component-02-externally-set-task-adventure-1": [
 ("OCR releases the set task in January", "Themes arrive early in the year"),
 ("Choose one starting point", "A single theme is selected"),
 ("Develop preparatory studies", "Research and planning fill the prep period"),
 ("Finalise the outcome plan", "Decisions are locked before timed work"),
 ("Work 10 hours under supervision", "The final piece is made in exam sessions"),
 ("Submit everything for marking", "Prep and outcome are assessed together"),
],
"art-design-gcse-ocr-critical-and-contextual-studies-adventure-1": [
 ("Note your first response", "Gut reaction is recorded before close study"),
 ("Describe what the work shows", "Plain description comes before analysis"),
 ("Analyse the visual elements", "Colour, line, tone and form are unpicked"),
 ("Research the context", "Artist and era explain choices in the work"),
 ("Interpret the message", "Meaning is proposed from the evidence"),
 ("Evaluate the work's success", "Judgement concludes the study"),
],
"art-design-gcse-ocr-fine-art-adventure-1": [
 ("Set up the still life", "Objects and lighting are arranged before drawing"),
 ("Sketch the arrangement lightly", "A faint accurate drawing maps the scene"),
 ("Block in the underpainting", "Thin paint sets the broad tones"),
 ("Develop the colour layers", "Colour builds over the tonal base"),
 ("Sharpen details and edges", "Precision comes after the layers settle"),
 ("Add final highlights", "The brightest accents finish the painting"),
],
"art-design-gcse-ocr-graphic-communication-adventure-1": [
 ("Analyse the magazine cover brief", "Title, audience and issue focus are set first"),
 ("Research masthead and cover conventions", "Existing covers reveal the genre rules"),
 ("Sketch layout grids and roughs", "Composition options are tried on paper"),
 ("Source or shoot the cover image", "The lead image is produced for the layout"),
 ("Assemble the cover digitally", "Type and image combine in software"),
 ("Proof and export the final cover", "Checking and output close the job"),
],
"art-design-gcse-ocr-photography-adventure-1": [
 ("Develop the shoot concept", "Ideas and references come before the camera"),
 ("Choose location, light and settings", "The technical setup follows the concept"),
 ("Carry out the shoot", "Frames are captured to the plan"),
 ("Review on a contact sheet", "The full take is assessed in miniature"),
 ("Edit the selected images", "Chosen frames are refined in post"),
 ("Present the final series", "Sequencing and display finish the project"),
],
"art-design-gcse-ocr-textile-design-adventure-1": [
 ("Set up the warp threads on the loom", "Weaving cannot start without a warp"),
 ("Begin weaving the weft over and under", "The weft crosses the prepared warp"),
 ("Beat each row down firmly", "Compacting rows keeps the weave even"),
 ("Build the pattern row by row", "The design grows as rows accumulate"),
 ("Remove the weaving from the loom", "The finished length is released"),
 ("Knot and finish the edges", "Securing ends stops the weave unravelling"),
],
"art-design-gcse-ocr-three-dimensional-design-adventure-1": [
 ("Draw the design proposals", "Ideas are fixed on paper before building"),
 ("Test with a card or clay maquette", "A model proves the design works"),
 ("Prepare materials and tools", "Making is set up from the tested plan"),
 ("Construct the main form", "The piece is built to the design"),
 ("Refine surfaces and joins", "Finishing improves the constructed form"),
 ("Present and evaluate the design", "Review against the brief comes last"),
],
"art-design-gcse-painting-techniques-adventure-1": [
 ("Prime the surface", "A sound ground comes before everything"),
 ("Lay a thin tonal imprimatura", "A wash sets the key before painting proper"),
 ("Underpaint lean and thin", "Early layers must stay lean"),
 ("Build fatter, richer layers", "Fat over lean prevents later cracking"),
 ("Apply impasto highlights last", "The thickest paint sits on the very top"),
 ("Varnish when fully dry", "Varnish always finishes a painting"),
],
"art-design-gcse-photography--digital-adventure-1": [
 ("Build a light-tight box", "A pinhole camera needs a sealed body first"),
 ("Pierce the pinhole aperture", "The tiny hole becomes the lens"),
 ("Load photo paper in the darkroom", "Paper must go in under safelight only"),
 ("Expose the scene for minutes", "The long exposure captures the image"),
 ("Develop the paper negative", "Chemistry reveals a reversed image"),
 ("Contact print to make the positive", "Printing the negative gives the final photo"),
],
"art-design-gcse-printmaking-methods-adventure-1": [
 ("Draw the design in reverse", "Lino prints mirror, so the design flips first"),
 ("Transfer the design to the lino", "The image goes onto the block"),
 ("Carve away the non-printing areas", "Cut surfaces stay paper-white"),
 ("Roll ink evenly over the block", "Ink coats only the raised surface"),
 ("Press paper on and burnish", "Pressure transfers the image"),
 ("Peel the print and leave to dry", "The reveal is the final step"),
],
"art-design-gcse-sculpture--3d-adventure-1": [
 ("Wedge the clay thoroughly", "Trapped air must go before any making"),
 ("Build the sculptural form", "Construction follows preparation"),
 ("Hollow and refine at leather-hard", "Thick walls are hollowed while semi-firm"),
 ("Dry slowly to bone dry", "Complete drying prevents kiln blow-ups"),
 ("Bisque fire around 1000C", "The first firing makes the clay ceramic"),
 ("Glaze and fire again", "The glaze firing completes the surface"),
],
"art-design-gcse-sketchbook-development-adventure-1": [
 ("Open with a theme mind-map", "The first pages set out the project focus"),
 ("Add artist research pages", "Influences are studied early to guide work"),
 ("Fill pages with observational studies", "Recording from life supplies material"),
 ("Experiment with media across pages", "Trials grow from the recorded sources"),
 ("Develop compositions for an outcome", "Ideas converge towards a final design"),
 ("Conclude with the final design plan", "The sketchbook ends ready for the outcome"),
],

# ---------- ART & DESIGN IBDP ----------
"art-design-ibdp-hl-communicating-visual-arts-adventure-1": [
 ("Review the whole body of work", "Curation starts from everything made on the course"),
 ("Select the works that communicate best", "Choice serves the intended audience experience"),
 ("Write exhibition texts for each work", "Each selected piece gets its own statement"),
 ("Compose the curatorial rationale", "One argument draws the selected works together"),
 ("Arrange and photograph the exhibition", "Physical presentation realises the rationale"),
 ("Submit the documented exhibition", "Assessment uses the photographed show"),
],
"art-design-ibdp-hl-comparative-study-hl-extension-adventure-1": [
 ("Select works by different artists and cultures", "The CS opens by choosing works from contrasting contexts"),
 ("Analyse formal qualities (criterion A)", "Criterion A is the first lens applied"),
 ("Interpret function and purpose (criterion B)", "Criterion B follows the formal analysis"),
 ("Evaluate cultural significance (criterion C)", "Criterion C sets the works in context"),
 ("Make comparisons and connections (criterion D)", "Criterion D links the works together"),
 ("Connect to your own art (HL criterion F)", "The HL extension screens come last"),
],
"art-design-ibdp-hl-exhibition-hl-extension-adventure-1": [
 ("Create the body of work over the course", "Two years of making come before any curating"),
 ("Select 8-11 resolved works (HL)", "HL students choose from their strongest pieces"),
 ("Write an exhibition text for each work", "Short texts explain each selected piece"),
 ("Write the curatorial rationale (700 words)", "HL's longer rationale frames the whole show"),
 ("Install and photograph the exhibition", "The hung show is documented for assessors"),
 ("Submit for assessment", "Upload completes the component"),
],
"art-design-ibdp-hl-process-portfolio-hl-extension-adventure-1": [
 ("Investigate artists and techniques", "The portfolio documents enquiry from the start"),
 ("Experiment across art-making forms", "HL requires at least three forms explored"),
 ("Develop ideas through making", "Sustained development follows experimentation"),
 ("Review, refine and reflect", "Critical reflection shapes the later work"),
 ("Select 13-25 screens (HL)", "The HL submission range frames the final edit"),
 ("Submit the process portfolio", "Upload closes the component"),
],
"art-design-ibdp-hl-visual-arts-in-context-adventure-1": [
 ("Lascaux cave paintings (c.15,000 BC)", "Prehistoric images open the human visual record"),
 ("Parthenon sculptures (c.440 BC)", "Classical Greece sets ideals of form"),
 ("Book of Kells (c.800 AD)", "Medieval illumination flourishes in monasteries"),
 ("Mona Lisa (c.1503)", "Renaissance mastery of oil and sfumato"),
 ("Hokusai's Great Wave (c.1831)", "Japanese prints later sweep into Western art"),
 ("Picasso's Guernica (1937)", "Modern art confronts twentieth-century war"),
],
"art-design-ibdp-hl-visual-arts-methods-adventure-1": [
 ("Research sources and inspiration", "Enquiry precedes the forming of an idea"),
 ("Conceptualise the artwork's intention", "A clear concept directs technical choices"),
 ("Select media and processes", "Materials are chosen to serve the concept"),
 ("Test and experiment with the media", "Trials prove the techniques work"),
 ("Create the resolved artwork", "The full piece follows successful tests"),
 ("Reflect and document the process", "Recording the journey completes the method"),
],
"art-design-ibdp-sl-communicating-visual-arts-adventure-1": [
 ("Audit the artworks you have made", "Curating begins with the available body of work"),
 ("Choose pieces for a coherent show", "Selection builds the intended viewer journey"),
 ("Draft a text for each chosen piece", "Statements clarify each work's intention"),
 ("Write the unifying rationale", "The curatorial argument binds the selection"),
 ("Set out and document the display", "Arrangement and photos realise the plan"),
 ("Present the exhibition for assessment", "Submission concludes the task"),
],
"art-design-ibdp-sl-comparative-study-adventure-1": [
 ("Choose works from two or more artists", "Contrasting cultural contexts are required from the start"),
 ("Analyse the formal qualities", "Criterion A examines how each work is built"),
 ("Interpret function and purpose", "Criterion B asks what each work is for"),
 ("Evaluate cultural significance", "Criterion C weighs context and meaning"),
 ("Compare and connect the works", "Criterion D synthesises the study"),
 ("Present the 10-15 screens", "The finished SL study is submitted"),
],
"art-design-ibdp-sl-exhibition-adventure-1": [
 ("Build a body of work across the course", "Making comes long before selecting"),
 ("Select 4-7 resolved works (SL)", "The SL range guides the final choice"),
 ("Write exhibition texts for the works", "Each piece is introduced to the viewer"),
 ("Write the curatorial rationale (400 words)", "SL's rationale explains the show's intent"),
 ("Install and photograph the show", "Documentation captures the presentation"),
 ("Upload for assessment", "Submission ends the component"),
],
"art-design-ibdp-sl-process-portfolio-adventure-1": [
 ("Investigate artists and ideas", "Enquiry seeds the experiments to come"),
 ("Experiment with media and techniques", "SL explores at least two art-making forms"),
 ("Develop ideas in sustained work", "Depth follows the breadth of trials"),
 ("Review and refine with reflection", "Critique improves the developing work"),
 ("Edit down to 9-18 screens (SL)", "The SL range shapes the final selection"),
 ("Submit the portfolio", "Upload completes the assessment"),
],
"art-design-ibdp-sl-visual-arts-in-context-adventure-1": [
 ("Egyptian tomb painting (c.1400 BC)", "Ancient conventions encode status and belief"),
 ("Greek red-figure vases (c.500 BC)", "Classical narrative painting on ceramics"),
 ("Byzantine mosaics of Ravenna (c.550 AD)", "Sacred golden imagery of early Christendom"),
 ("Benin Bronzes cast (1500s)", "West African court art at its height"),
 ("Impressionism emerges (1870s)", "Modern life and light transform painting"),
 ("Warhol's Pop Art (1960s)", "Mass culture becomes gallery art"),
],
"art-design-ibdp-sl-visual-arts-methods-adventure-1": [
 ("Gather research and stimulus", "Looking and reading precede making"),
 ("Form the idea and intention", "Concept crystallises from the research"),
 ("Choose appropriate media", "Materials follow the idea, not the reverse"),
 ("Run experiments and studies", "Testing proves the approach"),
 ("Produce the resolved work", "The final piece applies what testing showed"),
 ("Reflect on process and outcome", "Evaluation closes the cycle"),
],

# ---------- ART & DESIGN KS3 ----------
"art-design-ks3-art-movements-adventure-1": [
 ("Renaissance (1400s-1500s)", "Lifelike art and perspective begin the story"),
 ("Baroque (1600s)", "Dramatic light and movement come next"),
 ("Romanticism (early 1800s)", "Feeling and wild nature take over"),
 ("Impressionism (1870s)", "Quick outdoor paintings of light and weather"),
 ("Cubism (from 1907)", "Shapes split into angles and facets"),
 ("Pop Art (1950s-60s)", "Comics and adverts become art"),
],
"art-design-ks3-colour--tone-adventure-1": [
 ("Highlight - the lightest tone", "Where light hits directly; nothing is paler"),
 ("Light tone", "Just darker than the highlight"),
 ("Mid tone", "Halfway between light and dark"),
 ("Dark tone", "The shadowed side, darker than mid tone"),
 ("Core shadow - the darkest tone", "The deepest dark on the tonal scale"),
],
"art-design-ks3-colour-theory-basics-adventure-1": [
 ("Red - longest wavelength (~700nm)", "Red light has the longest visible wavelength"),
 ("Orange (~620nm)", "Slightly shorter waves than red"),
 ("Yellow (~580nm)", "Shorter again, between orange and green"),
 ("Green (~530nm)", "Mid-spectrum wavelength"),
 ("Blue (~470nm)", "Shorter waves than green"),
 ("Violet - shortest wavelength (~400nm)", "Violet ends the visible spectrum"),
],
"art-design-ks3-composition--pattern-adventure-1": [
 ("Design a simple motif", "Every repeat pattern starts with one unit"),
 ("Transfer the motif to the block", "The design goes onto the printing block"),
 ("Carve the block", "Cut areas will stay the paper colour"),
 ("Ink the block", "Colour is rolled onto the raised design"),
 ("Print the first motif", "One clean print tests the block"),
 ("Repeat to build the pattern", "Rows of prints create the repeat"),
],
"art-design-ks3-cultural-art-forms-adventure-1": [
 ("Lascaux cave paintings (c.15,000 BC)", "Prehistoric hunters paint animals in France"),
 ("Egyptian tomb paintings (c.1400 BC)", "Ancient Egypt decorates tombs for the afterlife"),
 ("Greek painted vases (c.500 BC)", "Stories circle classical pottery"),
 ("Benin Bronzes (1500s)", "West African casts celebrate the royal court"),
 ("Hokusai's Great Wave print (c.1831)", "Japanese woodblock art reaches its peak"),
 ("Papunya dot painting movement (1971)", "Aboriginal artists bring Dreaming designs to canvas"),
],
"art-design-ks3-drawing-materials-adventure-1": [
 ("4H pencil - hardest and lightest", "Hard graphite leaves the faintest line"),
 ("2H pencil", "Still hard and pale, softer than 4H"),
 ("HB pencil - the middle grade", "The balance point between hard and black"),
 ("2B pencil", "Softer and darker than HB"),
 ("4B pencil", "Rich dark marks, smudges easily"),
 ("6B pencil - softest and darkest", "The blackest, crumbliest grade here"),
],
"art-design-ks3-drawing-skills-adventure-1": [
 ("Sketch big basic shapes lightly", "Faint simple shapes block in the subject first"),
 ("Check sizes and proportions", "Fix mistakes while lines are still light"),
 ("Firm up the outlines", "Confident contours follow the corrections"),
 ("Shade the mid tones", "Work light to dark: middle values first"),
 ("Push the darkest shadows", "Deep darks come once mid tones are placed"),
 ("Finish with details and highlights", "Small touches complete the drawing"),
],
"art-design-ks3-famous-artworks-adventure-1": [
 ("Mona Lisa (c.1503)", "Leonardo's Renaissance portrait comes first"),
 ("Girl with a Pearl Earring (c.1665)", "Vermeer paints in the Dutch Golden Age"),
 ("The Great Wave (c.1831)", "Hokusai's Japanese woodblock print"),
 ("The Starry Night (1889)", "Van Gogh's swirling night sky"),
 ("The Scream (1893)", "Munch's icon of anxiety"),
 ("Guernica (1937)", "Picasso's protest at the bombing of Guernica"),
],
"art-design-ks3-formal-elements-adventure-1": [
 ("Line - the first marks", "Drawing begins with lines on the page"),
 ("Shape - lines join up", "When a line closes, it encloses a flat shape"),
 ("Tone - light and dark added", "Shading is applied across the shapes"),
 ("Form - tone makes it look 3D", "Tone turns flat shapes into solid-looking forms"),
 ("Texture - the surface finish", "Surface marks are added over the modelled form"),
],
"art-design-ks3-line-shape--form-adventure-1": [
 ("Dot - zero dimensions", "Everything starts from a single point"),
 ("Line - one dimension", "A dot that moves becomes a line"),
 ("Shape - two dimensions", "A line that closes makes a flat shape"),
 ("Form - three dimensions", "A shape given depth becomes a form"),
 ("Composition - forms arranged in space", "Finished elements are arranged last"),
],
}
