# Batch 11 sequences: design-technology + sociology
# Each value: list of (term, def) in TRUE ascending order (earliest/smallest/first at index 0)

SEQ = {
# ===================== D&T A-LEVEL =====================
"design-technology-a-level-aqa-design-communication-adventure-1": [
 ("Freehand 2D sketches", "Quick rough drawings explore many first ideas before any detail is fixed"),
 ("Annotated development sketches", "Notes on materials, sizes and function are added to the chosen ideas"),
 ("Isometric 3D drawing", "Chosen design drawn formally at 30 degrees to show its full form"),
 ("Rendered presentation drawing", "Colour and texture added so the client can approve the final look"),
 ("Orthographic working drawing", "Dimensioned third-angle views give makers exact manufacturing data"),
 ("CAD data sent to manufacturer", "Final digital model carries the approved design into production"),
],
"design-technology-a-level-aqa-design-for-manufacturing-project-management-adventure-1": [
 ("Design brief agreed with client", "Project starts by stating the problem, users and constraints"),
 ("Specification written", "Measurable criteria are drawn up from the brief before designing"),
 ("Gantt chart plans the schedule", "Tasks and deadlines are mapped before development work begins"),
 ("Prototype made and tested", "Design is proved to work before money is spent on production"),
 ("Tooling, jigs and fixtures produced", "Production equipment is built once the design is frozen"),
 ("Full production with quality control", "Manufacture runs at volume, checked against the specification"),
],
"design-technology-a-level-aqa-designing-making-principles-adventure-1": [
 ("Investigate context and user needs", "Designing starts by researching the problem and its users"),
 ("Write brief and specification", "Findings are turned into a brief and measurable criteria"),
 ("Generate initial ideas", "A wide range of concepts is sketched against the specification"),
 ("Develop ideas through modelling", "Promising ideas are refined with models and material tests"),
 ("Manufacture the final prototype", "The developed design is made accurately in chosen materials"),
 ("Test and evaluate against the spec", "Finished prototype is judged point by point against criteria"),
],
"design-technology-a-level-aqa-digital-design-manufacture-adventure-1": [
 ("3D CAD model created", "Digital workflow begins with the part modelled on screen"),
 ("Virtual testing and simulation", "FEA and simulation check the model before anything is cut"),
 ("CAM generates toolpaths", "Software converts the proven model into machine code (G-code)"),
 ("CNC machine set up", "Material is clamped and the machine zeroed before cutting"),
 ("Machine cuts the part", "CNC router, mill or laser follows the toolpaths automatically"),
 ("Part inspected and finished", "Output is checked against CAD dimensions, then finished"),
],
"design-technology-a-level-aqa-enterprise-marketing-adventure-1": [
 ("Research and development", "Product designed and tested; high costs, no sales yet"),
 ("Introduction (launch)", "Product enters the market; sales low, promotion heavy"),
 ("Growth", "Sales climb quickly as the product catches on"),
 ("Maturity", "Sales peak and level off; competition is strongest"),
 ("Decline", "Sales fall as the market moves on; product withdrawn or updated"),
],
"design-technology-a-level-aqa-materials-applications-adventure-1": [
 ("Tin", "Lowest melting point here: melts at 232°C"),
 ("Zinc", "Melts at 420°C; used for die casting and galvanising"),
 ("Aluminium", "Melts at 660°C; lightweight non-ferrous metal"),
 ("Copper", "Melts at 1085°C; ductile electrical conductor"),
 ("Mild steel", "Melts at about 1500°C; common ferrous alloy"),
 ("Tungsten", "Highest melting point of any metal: 3422°C"),
],
"design-technology-a-level-aqa-national-international-standards-adventure-1": [
 ("BSI founded (1901)", "The world's first national standards body is set up in London"),
 ("BSI Kitemark introduced (1903)", "Quality certification mark first applied to tram rails"),
 ("ISO founded (1947)", "International Organization for Standardization starts in Geneva"),
 ("ISO 9000 quality standards published (1987)", "First international quality management standards issued"),
 ("UKCA marking introduced (2021)", "Post-Brexit UK conformity mark begins replacing CE in Great Britain"),
],
"design-technology-a-level-aqa-performance-characteristics-of-materials-adventure-1": [
 ("LDPE (low-density polythene)", "Weakest here: tensile strength roughly 10 MPa"),
 ("Acrylic (PMMA)", "Tensile strength around 70 MPa; stiff but brittle"),
 ("Aluminium alloy", "Tensile strength about 300 MPa at low weight"),
 ("Mild steel", "Tensile strength around 400-500 MPa"),
 ("Titanium alloy (Ti-6Al-4V)", "Tensile strength about 950 MPa; aerospace grade"),
 ("Carbon fibre composite (along fibres)", "Strongest here: about 1500 MPa or more in fibre direction"),
],
"design-technology-a-level-aqa-processes-manufacture-adventure-1": [
 ("Granules fed into the hopper", "Injection moulding starts with thermoplastic pellets loaded"),
 ("Screw melts granules in heated barrel", "Rotating Archimedean screw carries and melts the plastic"),
 ("Melt injected into clamped mould", "Molten polymer is forced under pressure into the cavity"),
 ("Part cools and solidifies in mould", "Plastic hardens, taking the exact shape of the cavity"),
 ("Mould opens; ejector pins push part out", "Solidified moulding is released from the tool"),
 ("Sprues trimmed and part finished", "Excess runner material is removed from the moulding"),
],
"design-technology-a-level-aqa-technical-principles-adventure-1": [
 ("Iron ore mined", "Steel production begins with extracting ore from the ground"),
 ("Blast furnace smelts ore into pig iron", "Ore, coke and limestone react at about 1500°C"),
 ("Oxygen converter turns pig iron to steel", "Blown oxygen burns off excess carbon from the iron"),
 ("Steel cast into slabs and ingots", "Liquid steel is solidified into workable shapes"),
 ("Rolled into stock forms", "Slabs become sheet, bar, tube and other standard sections"),
 ("Stock machined into components", "Manufacturers convert stock forms into finished parts"),
],
"design-technology-a-level-design-movements--influential-designers-adventure-1": [
 ("Arts and Crafts movement (1860s)", "William Morris champions handcraft against industrial goods"),
 ("Art Nouveau (1890s)", "Organic whiplash lines flourish across Europe"),
 ("Bauhaus founded (1919)", "Gropius opens the Weimar school; form follows function"),
 ("Art Deco (1925)", "Paris Exposition names the geometric, luxurious style"),
 ("Mid-Century Modern (1945-60s)", "Eames and others bring moulded ply and organic modernism"),
 ("Memphis Group (1981)", "Sottsass launches playful postmodernism in Milan"),
],
"design-technology-a-level-design-process--ethics-adventure-1": [
 ("Identify the problem and who it affects", "Process opens by defining the need and stakeholders"),
 ("Research users, market and ethical issues", "Evidence is gathered, including moral and social impacts"),
 ("Write the design specification", "Research becomes measurable, justifiable criteria"),
 ("Generate and select ideas", "Concepts are created and screened against the specification"),
 ("Prototype and test", "Chosen design is made and trialled with users"),
 ("Evaluate against spec and ethics", "Final judgement covers performance and responsibility"),
],
"design-technology-a-level-digital-technologies-adventure-1": [
 ("Numerically controlled milling (1952)", "MIT demonstrates the first NC machine tool"),
 ("Sketchpad, first CAD program (1963)", "Ivan Sutherland draws on screen with a light pen"),
 ("Microprocessor launched (1971)", "Intel 4004 puts a computer on one chip"),
 ("Stereolithography patented (1986)", "Chuck Hull patents the first 3D printing process"),
 ("RepRap project begins (2005)", "Open-source movement makes 3D printing affordable"),
 ("'Industrie 4.0' coined (2011)", "Hannover Messe names the smart-factory revolution"),
],
"design-technology-a-level-edexcel-current-legislation-adventure-1": [
 ("Registered Designs Act (1949)", "UK law protecting the appearance of products"),
 ("Trade Descriptions Act (1968)", "Bans false claims about goods and services"),
 ("Health and Safety at Work Act (1974)", "Core duty of care for employers and employees"),
 ("Consumer Protection Act (1987)", "Liability for damage caused by defective products"),
 ("Trade Marks Act (1994)", "Modern UK registration and protection of trade marks"),
 ("Consumer Rights Act (2015)", "Goods must be of satisfactory quality and fit for purpose"),
],
"design-technology-a-level-edexcel-designing-for-cleaner-environment-adventure-1": [
 ("Raw material extraction", "Life cycle starts at the cradle: mining, drilling, logging"),
 ("Material processing", "Raw inputs are refined into usable stock materials"),
 ("Manufacture of the product", "Energy and waste impacts of making the product itself"),
 ("Distribution and transport", "Product miles add packaging and fuel impacts"),
 ("Use phase", "Energy and consumables consumed across the product's life"),
 ("End of life", "Grave stage: landfill, recycling or recovery"),
],
"design-technology-a-level-edexcel-effects-of-technological-developments-adventure-1": [
 ("Steam-powered factories (1780s)", "First industrial revolution mechanises production"),
 ("Moving assembly line (1913)", "Ford slashes Model T build time with flow production"),
 ("First industrial robot, Unimate (1961)", "Robot arm starts work at a General Motors plant"),
 ("First PLC, Modicon (1969)", "Programmable logic controllers automate factory lines"),
 ("Internet commerce spreads (1990s)", "Online ordering reshapes manufacturing and retail"),
 ("Industry 4.0 era (2011 onwards)", "Smart, connected factories use IoT, AI and big data"),
],
"design-technology-a-level-edexcel-factors-influencing-product-development-adventure-1": [
 ("Idea generation", "Development funnel opens with many possible concepts"),
 ("Idea screening", "Weak or unprofitable ideas are filtered out early"),
 ("Concept development and testing", "Surviving concepts are detailed and tried with users"),
 ("Prototype development", "Physical or digital prototypes prove the design works"),
 ("Test marketing", "Limited release checks real demand before full commitment"),
 ("Commercialisation", "Full launch: production, distribution and promotion at scale"),
],
"design-technology-a-level-edexcel-features-of-manufacturing-industries-adventure-1": [
 ("Design specification frozen", "Production planning can only start once the design is fixed"),
 ("Process planning", "Engineers choose processes and their sequence for each part"),
 ("Tooling, jigs and fixtures made", "Dedicated production equipment is built and proved"),
 ("Pilot run tests the line", "A small trial batch checks quality and cycle times"),
 ("Full-scale production begins", "Volume manufacture starts once the pilot passes"),
 ("Continuous improvement monitoring", "Output data drives ongoing quality and efficiency gains"),
],
"design-technology-a-level-edexcel-further-processes-techniques-adventure-1": [
 ("Pattern made of the part", "Sand casting starts with a replica, often wood or resin"),
 ("Sand rammed around pattern", "Pattern is removed, leaving a mould cavity with runners"),
 ("Metal melted in the furnace", "Charge is heated past its melting point ready to pour"),
 ("Molten metal poured into the mould", "Liquid metal fills the cavity through the runner system"),
 ("Casting solidifies and cools", "Metal hardens into the shape of the cavity"),
 ("Sand broken away; casting fettled", "Runners and rough edges are removed from the casting"),
],
"design-technology-a-level-edexcel-information-handling-modelling-adventure-1": [
 ("Collect data", "Surveys, tests and anthropometrics gather raw information first"),
 ("Sort and organise the data", "Raw figures are cleaned and structured into tables"),
 ("Model the data", "Charts, graphs and simulations make patterns visible"),
 ("Analyse for patterns and limits", "Trends, percentiles and anomalies are interpreted"),
 ("Present the findings", "Clear visuals communicate conclusions to stakeholders"),
 ("Apply conclusions to design decisions", "Evidence finally drives choices in the product"),
],
"design-technology-a-level-edexcel-materials-adventure-1": [
 ("Balsa wood", "Least dense here: about 0.16 g/cm3"),
 ("Oak", "Density about 0.7 g/cm3; dense hardwood that still floats"),
 ("Acrylic (PMMA)", "Density about 1.2 g/cm3; just denser than water"),
 ("Aluminium", "Density 2.7 g/cm3; the classic lightweight metal"),
 ("Mild steel", "Density 7.85 g/cm3; nearly three times aluminium"),
 ("Lead", "Densest here at 11.34 g/cm3"),
],
"design-technology-a-level-edexcel-performance-characteristics-of-materials-adventure-1": [
 ("Rubber", "Least stiff: Young's modulus around 0.05 GPa"),
 ("Polypropylene", "Stiffness about 1.5 GPa; flexible thermoplastic"),
 ("Oak (along the grain)", "Young's modulus around 12 GPa"),
 ("Aluminium", "Young's modulus 69 GPa"),
 ("Titanium", "Young's modulus about 114 GPa"),
 ("Steel", "Stiffest here: Young's modulus about 210 GPa"),
],
"design-technology-a-level-edexcel-potential-hazards-risk-assessment-adventure-1": [
 ("Identify the hazards", "HSE step 1: spot anything with potential to cause harm"),
 ("Decide who might be harmed and how", "Step 2: consider workers, visitors and vulnerable groups"),
 ("Evaluate risks and decide precautions", "Step 3: judge likelihood and severity, set controls"),
 ("Record findings and implement them", "Step 4: write up the assessment and apply the controls"),
 ("Review and update regularly", "Step 5: revisit after changes, incidents or over time"),
],
"design-technology-a-level-edexcel-processes-techniques-adventure-1": [
 ("Parison extruded", "Blow moulding starts with a hollow tube of molten plastic"),
 ("Mould halves clamp the parison", "The tube is sealed inside the bottle-shaped mould"),
 ("Compressed air inflates the parison", "Plastic balloons out against the cold mould walls"),
 ("Plastic cools against the mould", "The thin wall hardens into the container shape"),
 ("Mould opens and part is ejected", "Finished hollow container is released"),
 ("Flash trimmed from neck and base", "Excess pinched material is cut away"),
],
"design-technology-a-level-iterative-design-cycle-adventure-1": [
 ("Identify the problem and requirements", "Each cycle begins by defining what must be solved"),
 ("Generate ideas", "Possible solutions are sketched and explored"),
 ("Make a prototype", "The most promising idea is built quickly for testing"),
 ("Test with users", "The prototype is trialled against real needs"),
 ("Analyse the feedback", "Results show what worked and what failed"),
 ("Refine the design and repeat", "Improvements feed straight into the next loop"),
],
"design-technology-a-level-manufacturing--systems-adventure-1": [
 ("Customer order received", "In a JIT system, demand triggers everything downstream"),
 ("Production scheduled; materials called in", "Just-in-time deliveries avoid storing stock"),
 ("Components manufactured", "Parts are made to the schedule, not for a warehouse"),
 ("Product assembled", "Components come together on the assembly line"),
 ("Quality inspection", "Output is checked against specification before release"),
 ("Packaging and dispatch", "Finished goods leave for the customer"),
],
"design-technology-a-level-materials--composites-adventure-1": [
 ("Mould polished; release agent applied", "GRP lay-up starts by preparing the mould surface"),
 ("Gel coat brushed on", "First resin layer forms the smooth outer surface"),
 ("Glass fibre mat laid in", "Reinforcement is placed onto the tacky gel coat"),
 ("Resin rolled through the fibres", "Laminate is wetted out layer by layer, air removed"),
 ("Laminate cures", "Resin hardens, bonding fibres into a stiff shell"),
 ("Part demoulded and trimmed", "Cured moulding is released and edges cut clean"),
],
"design-technology-a-level-modern-composites--technical-textiles-adventure-1": [
 ("Bakelite (1907)", "First fully synthetic plastic opens the polymer age"),
 ("Commercial glass fibre (1936)", "Fibreglass arrives, enabling GRP composites"),
 ("Kevlar invented (1965)", "Stephanie Kwolek's aramid fibre is five times stronger than steel"),
 ("Gore-Tex launched (1976)", "Expanded PTFE membrane makes breathable waterproofs"),
 ("Boeing 787 first flight (2009)", "Airliner with about 50% composite structure by weight"),
],
"design-technology-a-level-ocr-critical-analysis-evaluation-adventure-1": [
 ("Define criteria from the specification", "Evaluation starts by fixing what success looks like"),
 ("Test the prototype with users in context", "Trials and stakeholder feedback gather evidence"),
 ("Analyse results against each criterion", "Data is compared point by point with the spec"),
 ("Identify strengths and weaknesses", "Analysis is summarised into clear judgements"),
 ("Recommend and justify modifications", "Findings end as proposed design improvements"),
],
"design-technology-a-level-ocr-design-for-manufacture-project-management-adventure-1": [
 ("Define project scope and deliverables", "Planning starts by agreeing exactly what will be made"),
 ("Break the work into tasks", "A work breakdown lists every job required"),
 ("Sequence tasks and find the critical path", "Dependencies show which delays would delay everything"),
 ("Build the Gantt chart and assign resources", "Tasks get dates, people and equipment"),
 ("Monitor progress and adjust", "Actual progress is tracked against the plan"),
 ("Review the project at completion", "Lessons are recorded once deliverables are handed over"),
],
"design-technology-a-level-ocr-design-production-capabilities-adventure-1": [
 ("Working prototype", "A single unit proves the design before any production"),
 ("Pilot pre-production run", "Small trial checks tooling and quality procedures"),
 ("Batch production", "Set quantities made in groups; machines switched between jobs"),
 ("Mass production", "Dedicated line turns out high volumes of identical products"),
 ("Continuous production", "Plant runs 24/7 at the highest volumes, e.g. plastics, paper"),
],
"design-technology-a-level-ocr-identifying-design-possibilities-adventure-1": [
 ("Explore the context", "Designers first observe the situation and its problems"),
 ("Identify stakeholders and users", "Everyone affected by a solution is mapped"),
 ("Research stakeholder needs and wants", "Interviews and observation gather requirements"),
 ("Analyse the research findings", "Data is interpreted to reveal real problems"),
 ("Define the design opportunity", "Analysis becomes a clear, justified design possibility"),
],
"design-technology-a-level-ocr-manufacturing-processes-techniques-adventure-1": [
 ("Mould on platen; sheet clamped", "Vacuum forming starts with set-up of mould and plastic"),
 ("Heater softens the sheet", "Thermoplastic is warmed until pliable"),
 ("Platen raised into the sheet", "Mould is pushed up into the softened plastic"),
 ("Vacuum pulls the sheet onto the mould", "Air is sucked out so pressure forms the shape"),
 ("Sheet cools and hardens", "Plastic sets in the moulded form"),
 ("Forming removed and trimmed", "Excess material around the shape is cut away"),
],
"design-technology-a-level-ocr-product-development-iterative-design-adventure-1": [
 ("Design brief defines the need", "Development starts from the agreed problem"),
 ("Initial concepts sketched", "A range of ideas responds to the brief"),
 ("First prototype made", "The chosen concept becomes a testable model"),
 ("User testing gives feedback", "Real users expose faults and opportunities"),
 ("Design refined from results", "Feedback drives the next, improved version"),
 ("Refined prototype retested and approved", "The loop closes when the spec is fully met"),
],
"design-technology-a-level-ocr-properties-of-materials-adventure-1": [
 ("Lead", "Softest here: about 1.5 on the Mohs hardness scale"),
 ("Copper", "Mohs hardness about 3; can be scratched by a knife"),
 ("Glass", "Mohs hardness about 5.5"),
 ("Hardened steel file", "Mohs hardness about 6.5; scratches glass"),
 ("Tungsten carbide", "Mohs hardness about 9; used for cutting tool tips"),
 ("Diamond", "Hardest natural material: Mohs 10"),
],
"design-technology-a-level-ocr-sustainability-ethics-adventure-1": [
 ("Prevention and reduction", "Top of the waste hierarchy: avoid creating waste at all"),
 ("Reuse", "Second best: products or parts used again as they are"),
 ("Recycling", "Materials reprocessed into new products"),
 ("Energy recovery", "Waste incinerated to capture useful energy"),
 ("Disposal to landfill", "Bottom of the hierarchy: the last resort"),
],
"design-technology-a-level-programmable-components--mechatronics-adventure-1": [
 ("Define system inputs and outputs", "Embedded design starts by listing sensors and actuators"),
 ("Plan the algorithm as a flowchart", "Program logic is mapped before any code is written"),
 ("Write the program code", "Flowchart is translated into instructions"),
 ("Simulate the program on screen", "Software testing catches errors before hardware is used"),
 ("Download code to the microcontroller", "Working program is flashed onto the chip"),
 ("Test in the real circuit and debug", "System is proved with actual sensors and outputs"),
],
"design-technology-a-level-smart-manufacturing--industry-40-adventure-1": [
 ("Steam mechanisation (1780s)", "Industry 1.0: water and steam power the first factories"),
 ("Ford's moving assembly line (1913)", "Industry 2.0 era: electricity enables mass production"),
 ("Unimate, first industrial robot (1961)", "Automation begins on a General Motors line"),
 ("First PLC, Modicon (1969)", "Industry 3.0: electronics and computers control production"),
 ("'Industrie 4.0' coined (2011)", "Hannover Messe names the cyber-physical, IoT factory era"),
],
"design-technology-a-level-sustainable-design--lifecycle-analysis-adventure-1": [
 ("Raw material extraction", "LCA's cradle: impacts of mining, drilling and harvesting"),
 ("Material processing", "Refining ores and crude oil into usable stock"),
 ("Product manufacture", "Energy, water and waste used in making the item"),
 ("Distribution and transport", "Packaging and product miles to reach the user"),
 ("Use and maintenance", "Lifetime energy and consumables in service"),
 ("End of life", "The grave: reuse, recycling, recovery or landfill"),
],

# ===================== D&T GCSE =====================
"design-technology-gcse-aqa-core-technical-principles-adventure-1": [
 ("Wrought iron", "Lowest carbon here: under 0.1% carbon"),
 ("Mild steel", "0.1-0.3% carbon; tough, ductile general-purpose steel"),
 ("Medium-carbon steel", "0.3-0.6% carbon; springs and some tools"),
 ("High-carbon (tool) steel", "0.6-1.4% carbon; hard enough for cutting tools"),
 ("Cast iron", "Highest carbon here: 2-4%; hard, brittle, good in compression"),
],
"design-technology-gcse-aqa-designing-making-principles-adventure-1": [
 ("Investigate the context", "Designing starts with research into the problem and users"),
 ("Write brief and specification", "Findings become a brief and measurable criteria"),
 ("Generate design ideas", "A range of concepts is sketched and annotated"),
 ("Develop and model the best idea", "Modelling refines the chosen concept"),
 ("Manufacture the prototype", "The developed design is made in real materials"),
 ("Test and evaluate", "The prototype is judged against the specification"),
],
"design-technology-gcse-aqa-electronic-systems-adventure-1": [
 ("Input sensor detects a change", "An LDR or thermistor turns conditions into a signal"),
 ("Signal sent to the process block", "Input voltage travels to the controller"),
 ("Microcontroller makes the decision", "The program compares the input with set values"),
 ("Driver amplifies the output signal", "A transistor boosts current for bigger devices"),
 ("Output device responds", "Lamp, buzzer or motor finally acts on the decision"),
],
"design-technology-gcse-aqa-energy-generation-storage-adventure-1": [
 ("Chemical energy stored in fuel", "Generation starts with energy locked in coal or gas"),
 ("Combustion boils water to steam", "Burning fuel releases heat in the boiler"),
 ("Steam spins the turbine", "Thermal energy becomes kinetic rotation"),
 ("Generator produces electricity", "Rotation is converted by electromagnetic induction"),
 ("Transformer steps up the voltage", "High voltage cuts losses for transmission"),
 ("National Grid delivers power", "Electricity reaches homes and factories"),
],
"design-technology-gcse-aqa-materials-their-working-properties-adventure-1": [
 ("Balsa", "Softest here: Janka hardness about 70 lbf; model making"),
 ("Pine", "Softwood, Janka roughly 400-700 lbf"),
 ("Oak", "Hardwood, Janka about 1300 lbf"),
 ("Hickory", "Janka about 1800 lbf; tool handles"),
 ("Ebony", "Hardest here: Janka about 3200 lbf"),
],
"design-technology-gcse-aqa-new-emerging-technologies-adventure-1": [
 ("3D printing patented (1986)", "Chuck Hull's stereolithography starts additive manufacture"),
 ("World Wide Web goes public (1991)", "Online communication transforms design and commerce"),
 ("Graphene isolated (2004)", "Manchester scientists extract the one-atom-thick material"),
 ("iPhone launches (2007)", "Smartphones reshape products and user expectations"),
 ("ChatGPT released (2022)", "Generative AI enters mainstream design work"),
],
"design-technology-gcse-aqa-specialist-technical-principles-adventure-1": [
 ("Layout paper", "Lightest here at about 50 gsm; thin and translucent"),
 ("Copier paper", "Standard 80 gsm office paper"),
 ("Cartridge paper", "About 130 gsm; takes pencil and ink well"),
 ("Card", "About 230 gsm; greetings cards and simple models"),
 ("Mounting board", "Heaviest here, around 1000+ gsm; rigid presentation board"),
],
"design-technology-gcse-cad-cam-adventure-1": [
 ("Design drawn in CAD", "The product is modelled accurately on screen first"),
 ("Design checked and simulated", "Dimensions and fit are verified digitally"),
 ("CAM converts the file to toolpaths", "Software writes the machine instructions"),
 ("Material clamped; machine set up", "Workpiece secured and datum set before cutting"),
 ("Machine manufactures the part", "Laser cutter or CNC router follows the code"),
 ("Part removed and finished", "Edges cleaned and the part checked against the CAD"),
],
"design-technology-gcse-cambridge-igcse-electronic-systems-adventure-1": [
 ("Circuit diagram designed", "The schematic fixes components and connections first"),
 ("Circuit simulated in software", "Virtual testing finds faults before building"),
 ("Prototype built on breadboard", "Solder-free build allows quick changes"),
 ("Tested with a multimeter", "Voltages and currents are checked against predictions"),
 ("Components soldered onto PCB", "The proven circuit is made permanent"),
 ("Final product tested in its case", "Complete assembly is verified before use"),
],
"design-technology-gcse-cambridge-igcse-graphic-communication-adventure-1": [
 ("A6 paper", "Smallest here: 105 x 148 mm, postcard size"),
 ("A5 paper", "148 x 210 mm; double the area of A6"),
 ("A4 paper", "210 x 297 mm; standard office sheet"),
 ("A3 paper", "297 x 420 mm; common for design work"),
 ("A2 paper", "420 x 594 mm; flip-chart scale"),
 ("A1 paper", "Largest here: 594 x 841 mm, poster size"),
],
"design-technology-gcse-cambridge-igcse-manufacturing-techniques-adventure-1": [
 ("Mark out from the working drawing", "Rule, try square and scriber transfer the dimensions"),
 ("Cut to size", "Sawing removes waste outside the marked lines"),
 ("Shape and smooth", "Planes and files refine the parts to the line"),
 ("Drill the holes", "Holes are made before parts are joined"),
 ("Assemble the components", "Joints, screws or adhesive bring parts together"),
 ("Apply the finish", "Paint, varnish or oil protects the completed product"),
],
"design-technology-gcse-cambridge-igcse-materials-components-adventure-1": [
 ("Expanded polystyrene foam", "Least dense here: about 0.03 g/cm3"),
 ("Balsa wood", "Density about 0.16 g/cm3"),
 ("Pine", "Density about 0.5 g/cm3"),
 ("Acrylic", "Density about 1.2 g/cm3; sinks in water"),
 ("Aluminium", "Density 2.7 g/cm3"),
 ("Steel", "Densest here: about 7.85 g/cm3"),
],
"design-technology-gcse-cambridge-igcse-mechanisms-adventure-1": [
 ("Rider pushes the pedals", "Input force enters the bicycle drive system"),
 ("Cranks rotate the chainring", "Levers convert leg force into rotary motion"),
 ("Chain transfers drive to the sprocket", "Chain and sprocket carry motion to the rear"),
 ("Sprocket turns the rear wheel", "Gear ratio sets the speed of rotation"),
 ("Wheel grips the road; bike moves", "Output motion finally propels the rider"),
],
"design-technology-gcse-cambridge-igcse-product-design-principles-adventure-1": [
 ("Identify the need", "Design begins when a problem or want is recognised"),
 ("Write the design brief", "A short statement sets out what must be designed"),
 ("Draw up the specification", "Measurable criteria expand the brief"),
 ("Sketch concept ideas", "A range of possible solutions is generated"),
 ("Develop the chosen idea into a prototype", "Modelling and making refine one concept"),
 ("Evaluate against the specification", "The result is judged point by point"),
],
"design-technology-gcse-cambridge-igcse-structures-adventure-1": [
 ("Beam bridge", "Shortest spans, typically up to about 80 m per beam"),
 ("Cantilever truss bridge", "Record span 549 m (Quebec Bridge, 1917)"),
 ("Arch bridge", "Record span 575 m (Chaotianmen Bridge, 2009)"),
 ("Cable-stayed bridge", "Record span 1104 m (Russky Bridge, 2012)"),
 ("Suspension bridge", "Longest spans: 2023 m (Canakkale Bridge, 2022)"),
],
"design-technology-gcse-design-process-adventure-1": [
 ("Identify the problem or need", "The process starts by recognising what must be solved"),
 ("Write the design brief", "A clear statement of the task and its constraints"),
 ("Research the market and users", "Existing products and user needs are investigated"),
 ("Write the specification", "Research becomes measurable design criteria"),
 ("Generate and develop ideas", "Concepts are sketched, selected and refined"),
 ("Make and evaluate the prototype", "The design is built and tested against the spec"),
],
"design-technology-gcse-edexcel-core-knowledge-understanding-adventure-1": [
 ("Stone Age flint tools", "Earliest manufacturing: shaped stone, before metals"),
 ("Bronze Age begins (c.3000 BC)", "First alloy: copper and tin cast into tools"),
 ("Iron Age begins (c.1200 BC)", "Stronger, more abundant metal replaces bronze"),
 ("Bessemer process (1856)", "Cheap mass-produced steel powers industry"),
 ("Bakelite invented (1907)", "The first fully synthetic plastic"),
 ("Carbon fibre developed (1960s)", "High-strength composites enter aerospace"),
],
"design-technology-gcse-edexcel-design-influences-adventure-1": [
 ("Art Nouveau (1890s)", "Flowing organic lines inspired by nature"),
 ("De Stijl founded (1917)", "Mondrian and Rietveld reduce design to grids and primaries"),
 ("Bauhaus founded (1919)", "German school unites art and industrial production"),
 ("Streamlining (1930s)", "Aerodynamic teardrop styling sweeps American products"),
 ("Memphis Group (1981)", "Postmodern colour and pattern challenge good taste"),
 ("Apple iMac minimalism (1998)", "Jony Ive's translucent iMac revives minimal design"),
],
"design-technology-gcse-edexcel-designing-making-principles-adventure-1": [
 ("Study the working drawing", "Making starts by reading sizes and details to plan work"),
 ("Select materials and tools", "Correct stock and equipment are gathered"),
 ("Mark out the components", "Measurements are transferred onto the material"),
 ("Cut and shape the parts", "Wastage processes remove material to the line"),
 ("Assemble the components", "Parts are joined with joints, fixings or adhesive"),
 ("Finish and quality-check", "Surface finish applied; product checked against spec"),
],
"design-technology-gcse-edexcel-electronic-systems-programmable-components-adventure-1": [
 ("START terminal", "Every flowchart begins at the start symbol"),
 ("INPUT: read the sensor", "The program first collects data, e.g. a switch state"),
 ("DECISION: compare the value", "Diamond symbol branches yes/no on a condition"),
 ("OUTPUT: switch the device", "LED, buzzer or motor is turned on or off"),
 ("Loop back or STOP", "Flow returns for the next reading or the program ends"),
],
"design-technology-gcse-edexcel-industry-manufacturing-adventure-1": [
 ("Cottage industry (pre-1750s)", "Goods made by hand at home before factories"),
 ("Steam-powered factories (1780s)", "The Industrial Revolution centralises production"),
 ("Ford assembly line (1913)", "Flow production makes cars affordable"),
 ("First industrial robot (1961)", "Unimate begins factory automation at GM"),
 ("Lean and JIT spread (1970s)", "Toyota's methods cut waste and stock worldwide"),
 ("Mass customisation (2010s)", "Industry 4.0 tailors products at volume"),
],
"design-technology-gcse-edexcel-materials-their-properties-adventure-1": [
 ("Rubber", "An insulator: effectively zero electrical conductivity"),
 ("Silicon", "A semiconductor: conducts far less than any metal"),
 ("Mild steel", "Conducts, but only weakly for a metal (about 6 MS/m)"),
 ("Aluminium", "Good conductor: about 38 MS/m; used for power lines"),
 ("Copper", "About 59 MS/m; standard for electrical wiring"),
 ("Silver", "Best conductor of all metals: about 63 MS/m"),
],
"design-technology-gcse-manufacturing-processes-adventure-1": [
 ("Cut acrylic to size", "Line bending starts with the blank cut and edges cleaned"),
 ("Mark the bend line", "The fold position is measured and marked"),
 ("Heat along the line on the strip heater", "Localised heat softens just the bend zone"),
 ("Bend to the angle in a jig", "Softened plastic is folded against a former"),
 ("Hold until cool and check the angle", "Plastic sets rigid in its new shape"),
],
"design-technology-gcse-materials--manufacturing-adventure-1": [
 ("Crude oil extracted", "Most plastics begin as oil drilled from the ground"),
 ("Fractional distillation separates naphtha", "Refinery splits crude into useful fractions"),
 ("Cracking produces monomers", "Naphtha is broken into small molecules like ethene"),
 ("Polymerisation forms polymer granules", "Monomers join into long chains, sold as pellets"),
 ("Granules moulded into products", "Injection or blow moulding shapes the final item"),
],
"design-technology-gcse-mechanical--electronic-systems-adventure-1": [
 ("Sensor measures the condition", "Closed-loop control starts with an input reading"),
 ("Signal compared with the set point", "The system checks reading against the target"),
 ("Controller decides the response", "Process block computes what to change"),
 ("Actuator produces the output", "Motor, heater or valve acts on the decision"),
 ("Feedback: sensor re-checks the result", "New reading closes the loop for the next cycle"),
],
"design-technology-gcse-mechanical-devices-adventure-1": [
 ("Intake stroke", "Piston moves down, drawing in the fuel-air mixture"),
 ("Compression stroke", "Piston rises, squeezing the mixture"),
 ("Spark ignites the mixture", "Spark plug fires at maximum compression"),
 ("Power stroke", "Expanding gases force the piston down, doing work"),
 ("Exhaust stroke", "Piston rises again, pushing burnt gases out"),
],
"design-technology-gcse-ocr-design-thinking-communication-adventure-1": [
 ("Mind map the problem", "Thinking opens out with a quick map of the context"),
 ("Freehand idea sketches", "Many rough concepts are drawn fast"),
 ("Annotated development drawings", "Notes refine the strongest ideas"),
 ("3D isometric presentation drawing", "The chosen design is shown in full form"),
 ("Orthographic working drawing", "Dimensioned views communicate exact sizes"),
 ("CAD model shared for manufacture", "Digital file carries the design to production"),
],
"design-technology-gcse-ocr-identifying-requirements-adventure-1": [
 ("Explore the context", "Designers first observe the situation and its problems"),
 ("Identify users and stakeholders", "Everyone affected by a solution is listed"),
 ("Research needs and wants", "Interviews and observation gather requirements"),
 ("Analyse the findings", "Research is interpreted to find the real problem"),
 ("Write the design brief", "The opportunity is stated clearly"),
 ("Write the specification", "The brief becomes measurable criteria"),
],
"design-technology-gcse-ocr-implications-of-wider-issues-adventure-1": [
 ("Raw material extraction", "A product's footprint starts at the cradle"),
 ("Processing and manufacture", "Energy and waste in turning materials into products"),
 ("Distribution", "Product miles: packaging and transport impacts"),
 ("Use phase", "Energy and consumables across the product's life"),
 ("Disposal at end of life", "Landfill, recycling or recovery at the grave stage"),
],
"design-technology-gcse-ocr-learning-from-existing-products-adventure-1": [
 ("Select a product to study", "Analysis starts by choosing a relevant existing design"),
 ("Disassemble the product", "A teardown reveals how it is put together"),
 ("Identify materials and components", "Each part's material and purpose is recorded"),
 ("Work out the manufacturing processes", "Mould lines and finishes show how it was made"),
 ("Evaluate strengths and weaknesses", "The design is judged against user needs"),
 ("Apply the lessons to your own design", "Findings finally inform new design work"),
],
"design-technology-gcse-ocr-manufacturing-processes-techniques-adventure-1": [
 ("CAD model created", "3D printing starts with a digital design"),
 ("Model exported as an STL file", "Geometry is converted to a printable mesh"),
 ("Slicer generates the layers", "Software turns the mesh into G-code layer paths"),
 ("Printer builds layer by layer", "Material is deposited from the bottom upwards"),
 ("Supports removed", "Temporary structures are broken or dissolved away"),
 ("Surface finished", "Sanding or sealing completes the part"),
],
"design-technology-gcse-ocr-material-considerations-adventure-1": [
 ("Expanded polystyrene", "Best insulator here: about 0.03 W/mK"),
 ("Pine wood", "Thermal conductivity about 0.12 W/mK"),
 ("Glass", "About 1 W/mK"),
 ("Steel", "About 50 W/mK"),
 ("Aluminium", "About 237 W/mK; used for heat sinks"),
 ("Copper", "Best conductor here: about 400 W/mK"),
],
"design-technology-gcse-ocr-viability-of-design-solutions-adventure-1": [
 ("Calculate the manufacturing cost per unit", "Viability starts with what each item costs to make"),
 ("Set the selling price and margin", "Price must cover cost and return a profit"),
 ("Estimate market demand", "Likely sales volumes are forecast"),
 ("Calculate the break-even point", "Cost, price and demand show units needed to profit"),
 ("Make the go/no-go decision", "All the evidence finally supports a judgement"),
],
"design-technology-gcse-polymers--plastics-adventure-1": [
 ("PET", "Recycling code 1: drinks bottles"),
 ("HDPE", "Recycling code 2: milk bottles and pipes"),
 ("PVC", "Recycling code 3: window frames and pipes"),
 ("LDPE", "Recycling code 4: carrier bags and films"),
 ("PP (polypropylene)", "Recycling code 5: food tubs and bottle caps"),
 ("PS (polystyrene)", "Recycling code 6: yoghurt pots and foam packaging"),
],
"design-technology-gcse-smart--modern-materials-adventure-1": [
 ("Nitinol discovered (1959)", "Shape memory alloy found at the US Naval Ordnance Lab"),
 ("LCD demonstrated (1968)", "RCA shows the first liquid crystal display"),
 ("Thermochromic mood ring (1975)", "Colour-change novelty popularises thermochromics"),
 ("QTC invented (1996)", "Quantum tunnelling composite conducts when squeezed"),
 ("Graphene isolated (2004)", "One-atom-thick carbon extracted in Manchester"),
],
"design-technology-gcse-sustainability--6-rs-adventure-1": [
 ("Bottle used and put in the recycling bin", "The recycling loop starts with the consumer"),
 ("Collected and sorted at the recovery facility", "Plastics are separated by polymer type"),
 ("Washed and shredded into flakes", "Clean PET flakes are produced"),
 ("Melted into pellets", "Flakes become raw material for manufacturers"),
 ("Made into new products", "Recycled pellets re-enter manufacturing, closing the loop"),
],
"design-technology-gcse-timbers--manufactured-boards-adventure-1": [
 ("Tree felled", "Timber production starts in the forest"),
 ("Log converted into boards", "Sawmill cuts the trunk into planks"),
 ("Boards seasoned", "Drying to around 10-12% moisture stops warping"),
 ("Planed square and smooth", "Rough-sawn boards become PSE stock"),
 ("Marked out and cut into components", "Stock is machined into project parts"),
 ("Assembled and finished", "Parts are joined and the surface protected"),
],

# ===================== D&T IBDP =====================
"design-technology-ibdp-hl-classic-design-adventure-1": [
 ("Thonet No.14 chair (1859)", "Bentwood cafe chair, an early mass-produced classic"),
 ("Coca-Cola contour bottle (1915)", "Instantly recognisable form, even in the dark"),
 ("Anglepoise lamp (1932)", "Carwardine's spring-balanced task light"),
 ("Vespa scooter (1946)", "Post-war Italian mobility icon"),
 ("Eames Lounge Chair (1956)", "Moulded plywood and leather mid-century landmark"),
 ("Apple iPod (2001)", "Digital-age classic: 1000 songs in your pocket"),
],
"design-technology-ibdp-hl-commercial-production-adventure-1": [
 ("Receive the final design specification", "Commercial production starts from a frozen design"),
 ("Select the manufacturing processes", "Processes are matched to material, volume and cost"),
 ("Design and make tooling and jigs", "Dedicated equipment is produced and proved"),
 ("Run a pilot production batch", "A trial run validates quality and cycle times"),
 ("Begin full-scale production", "Volume manufacture starts after the pilot passes"),
 ("Monitor with quality assurance", "Ongoing checks keep output within specification"),
],
"design-technology-ibdp-hl-final-production-adventure-1": [
 ("Finalise the working drawings", "Making starts only when every dimension is fixed"),
 ("Order materials and components", "Everything needed is sourced before manufacture"),
 ("Manufacture the individual parts", "Components are made to the drawings"),
 ("Assemble the product", "Parts come together in the planned order"),
 ("Apply finishes", "Surface treatments protect and complete the product"),
 ("Test against the specification", "The finished item is verified point by point"),
],
"design-technology-ibdp-hl-human-factors-ergonomics-adventure-1": [
 ("Define the user population", "Ergonomic design starts by fixing who will use it"),
 ("Collect anthropometric data", "Body measurements of that population are gathered"),
 ("Calculate the 5th-95th percentile range", "Statistics define the spread to design for"),
 ("Size the design to the range", "Dimensions are set so the target users fit"),
 ("Run user trials", "Real users test comfort, reach and usability"),
 ("Refine the dimensions", "Trial feedback fine-tunes the final sizes"),
],
"design-technology-ibdp-hl-innovation-design-adventure-1": [
 ("Concept sketch", "An invention starts as a recorded idea"),
 ("Scale model", "A cheap model tests proportion and form"),
 ("Working prototype", "A functional version proves the principle"),
 ("Pilot production", "Small-scale manufacture tests processes"),
 ("Market launch", "The invention becomes an innovation when it sells"),
 ("Mass adoption", "Diffusion spreads the product through society"),
],
"design-technology-ibdp-hl-innovation-markets-adventure-1": [
 ("Innovators (2.5%)", "First to buy: risk-takers who try unproven products"),
 ("Early adopters (13.5%)", "Opinion leaders whose approval drives the market"),
 ("Early majority (34%)", "Deliberate buyers join once benefits are proven"),
 ("Late majority (34%)", "Sceptics buy only when most people already have"),
 ("Laggards (16%)", "Last to adopt, often only when alternatives vanish"),
],
"design-technology-ibdp-hl-modelling-adventure-1": [
 ("Conceptual model", "Lowest fidelity: the idea expressed in words or thought"),
 ("Graphical model", "Sketches and diagrams put the concept on paper"),
 ("Physical mock-up", "Cheap materials show form and scale, no function"),
 ("Working prototype", "A functional model proves the design operates"),
 ("Pre-production prototype", "Final materials and processes, ready to validate production"),
],
"design-technology-ibdp-hl-resource-management-sustainable-production-adventure-1": [
 ("Raw material extraction", "LCA's cradle: mining, drilling and harvesting"),
 ("Material processing", "Refining raw inputs into usable stock"),
 ("Manufacturing", "Making the product consumes energy and creates waste"),
 ("Distribution", "Packaging and transport to the point of sale"),
 ("Use and operation", "Impacts across the product's working life"),
 ("End of life", "The grave: reuse, recycling, recovery or disposal"),
],
"design-technology-ibdp-hl-sustainability-adventure-1": [
 ("Prevention and reduction", "Most preferred: design out waste at source"),
 ("Reuse", "Products or components used again unchanged"),
 ("Recycling", "Materials reprocessed into new feedstock"),
 ("Energy recovery", "Incineration captures energy from residual waste"),
 ("Disposal to landfill", "Least preferred option in the waste hierarchy"),
],
"design-technology-ibdp-hl-user-centred-design-adventure-1": [
 ("Empathise with users", "UCD starts by observing and interviewing real users"),
 ("Define the problem", "Insights become a clear user-centred problem statement"),
 ("Ideate solutions", "Many ideas are generated against the defined need"),
 ("Prototype", "Quick models make the best ideas testable"),
 ("Test with users", "Users trial the prototypes in context"),
 ("Iterate from feedback", "Results refine the design through further cycles"),
],
"design-technology-ibdp-sl-classic-design-adventure-1": [
 ("Coca-Cola contour bottle (1915)", "Bottle designed to be recognised by touch alone"),
 ("Barcelona chair (1929)", "Mies van der Rohe's steel-and-leather icon"),
 ("London Underground diagram (1933)", "Harry Beck's schematic map redefines wayfinding"),
 ("Mini car (1959)", "Issigonis packs space efficiency into a small car"),
 ("Sony Walkman (1979)", "Portable music changes listening habits"),
 ("Apple iPod (2001)", "Digital music player becomes a design classic"),
],
"design-technology-ibdp-sl-final-production-adventure-1": [
 ("Confirm drawings and plan of making", "Production starts from finalised drawings and a plan"),
 ("Gather materials and components", "Everything is sourced before work begins"),
 ("Make the component parts", "Each part is manufactured to the drawings"),
 ("Assemble the product", "Parts are joined in the planned sequence"),
 ("Finish and test against the spec", "Surface finish applied, then final verification"),
],
"design-technology-ibdp-sl-human-factors-ergonomics-adventure-1": [
 ("Identify the user group", "Design for people starts by defining the users"),
 ("Gather anthropometric data", "Relevant body measurements are collected"),
 ("Choose the percentile range", "Typically 5th to 95th percentile is selected"),
 ("Apply the dimensions to the design", "Sizes are set from the percentile data"),
 ("Test the design with real users", "User trials confirm fit and comfort"),
],
"design-technology-ibdp-sl-innovation-design-adventure-1": [
 ("Development", "Pre-launch stage: design and testing, costs but no sales"),
 ("Introduction", "Product launches; sales start low with heavy promotion"),
 ("Growth", "Sales rise rapidly as adoption spreads"),
 ("Maturity", "Sales peak and plateau; competition is fiercest"),
 ("Decline", "Sales fall; the product is updated or withdrawn"),
],
"design-technology-ibdp-sl-modelling-adventure-1": [
 ("Idea described and sketched", "Modelling starts with the concept on paper"),
 ("Card or foam mock-up", "Quick cheap model explores form and scale"),
 ("Developed appearance model", "Refined model shows the intended look"),
 ("Working prototype", "Functional model proves the design works"),
 ("Final prototype in real materials", "Highest fidelity before any production"),
],
"design-technology-ibdp-sl-resource-management-sustainable-production-adventure-1": [
 ("Raw material extraction", "The life cycle's cradle stage"),
 ("Manufacture", "Materials are processed and the product is made"),
 ("Distribution", "Packaging and transport to the user"),
 ("Use", "Energy and resources consumed in service"),
 ("Disposal at end of life", "The grave: recycle, recover or landfill"),
],

# ===================== D&T KS3 =====================
"design-technology-ks3-designing--drawing-adventure-1": [
 ("Mind map first thoughts", "Designing starts by opening out lots of directions"),
 ("Quick freehand sketches", "Many rough ideas are drawn fast"),
 ("Annotate the best idea", "Notes explain materials, sizes and how it works"),
 ("Draw it in 3D (isometric)", "The chosen idea is shown in proper form"),
 ("Final rendered drawing with sizes", "Colour and dimensions complete the design"),
],
"design-technology-ks3-designing-for-users-adventure-1": [
 ("Identify the user", "User-centred design starts with who it is for"),
 ("Find out the user's needs", "Interviews and observation reveal requirements"),
 ("Write design criteria", "Needs become a checklist for the design"),
 ("Sketch ideas for the user", "Concepts respond directly to the criteria"),
 ("Make a simple model", "The best idea becomes something testable"),
 ("Get user feedback", "The user judges the model so it can improve"),
],
"design-technology-ks3-electronics--smart-materials-adventure-1": [
 ("Draw the circuit diagram", "Building starts with a plan using symbols"),
 ("Collect the components", "Resistors, LEDs and battery gathered from the diagram"),
 ("Build the circuit on a breadboard", "Components connected without solder first"),
 ("Check connections against the diagram", "Errors are found before power is applied"),
 ("Connect the battery and test", "The circuit is finally powered and checked"),
],
"design-technology-ks3-food-preparation--nutrition-adventure-1": [
 ("Weigh the ingredients", "Bread making starts with accurate measuring"),
 ("Mix and knead the dough", "Kneading develops the stretchy gluten"),
 ("Prove the dough", "Yeast makes carbon dioxide so the dough rises"),
 ("Knock back and shape", "Risen dough is shaped into loaves or rolls"),
 ("Bake in a hot oven", "Heat sets the structure and browns the crust"),
 ("Cool on a wire rack", "Air circulation stops the base going soggy"),
],
"design-technology-ks3-graphics--presentation-techniques-adventure-1": [
 ("Thumbnail sketches", "Tiny quick drawings explore lots of layouts first"),
 ("Draw the chosen idea in outline", "The best idea is drawn up cleanly"),
 ("Add colour rendering", "Marker or pencil colour shows materials"),
 ("Add tone, shadows and highlights", "Light effects make the drawing look 3D"),
 ("Lay out the final presentation board", "Finished visuals and labels are arranged"),
],
"design-technology-ks3-hand-tools--workshop-safety-adventure-1": [
 ("Put on apron and safety goggles", "PPE always comes before any work starts"),
 ("Mark out with rule and try square", "Accurate lines guide all the cutting"),
 ("Clamp the wood in the vice", "Work must be secure before sawing"),
 ("Cut with the tenon saw", "Sawing on the waste side of the line"),
 ("Smooth with file and glasspaper", "Edges are refined down to the line"),
 ("Sweep the bench and return tools", "The job ends with a safe, tidy workshop"),
],
"design-technology-ks3-iterative-design-process-adventure-1": [
 ("Understand the problem", "Each cycle starts by exploring the need"),
 ("Generate ideas", "Lots of possible solutions are sketched"),
 ("Make a prototype", "The best idea is built quickly and cheaply"),
 ("Test the prototype", "Trying it out shows what works and what fails"),
 ("Improve from the feedback", "Changes are made based on the results"),
 ("Repeat the loop", "The improved design goes round the cycle again"),
],
"design-technology-ks3-materials--properties-adventure-1": [
 ("Polystyrene foam", "Least dense here: about 0.03 g/cm3"),
 ("Cork", "Density about 0.24 g/cm3; floats high in water"),
 ("Pine", "Density about 0.5 g/cm3"),
 ("Acrylic", "Density about 1.2 g/cm3; just sinks in water"),
 ("Aluminium", "Density 2.7 g/cm3; a light metal"),
 ("Steel", "Densest here: about 7.9 g/cm3"),
],
"design-technology-ks3-mechanisms--forces-adventure-1": [
 ("Handle is turned", "Input: the user supplies rotary motion"),
 ("Axle and cam rotate", "The cam spins with the axle inside the toy"),
 ("Follower rides up the cam lobe", "Rotary motion starts becoming up-and-down motion"),
 ("Push rod rises in its guide", "The follower lifts the rod vertically"),
 ("Toy figure on top moves", "Output: reciprocating motion animates the figure"),
],
"design-technology-ks3-textiles--fibres-adventure-1": [
 ("Cotton fibres harvested", "Textiles start with raw fibre from the plant"),
 ("Fibres cleaned and carded", "Tangles are combed into straight, soft strands"),
 ("Spun into yarn", "Twisting binds short fibres into continuous thread"),
 ("Woven or knitted into fabric", "Yarns interlace to make cloth"),
 ("Fabric dyed and finished", "Colour and treatments are applied to the cloth"),
 ("Cut and sewn into a garment", "The fabric finally becomes a product"),
],

# ===================== SOCIOLOGY A-LEVEL =====================
"sociology-a-level-aqa-crime-deviance-with-theory-methods-adventure-1": [
 ("Durkheim: crime is normal (1895)", "Functionalist claim that crime exists in every society"),
 ("Merton's strain theory (1938)", "Blocked goals push people to innovate or rebel"),
 ("Cohen: status frustration (1955)", "Delinquent Boys explains subcultural crime"),
 ("Becker's labelling theory (1963)", "Outsiders: deviance is created by societal reaction"),
 ("Hall: Policing the Crisis (1978)", "Neo-Marxist study of the mugging moral panic"),
 ("Wilson & Kelling: broken windows (1982)", "Right realist case for tackling minor disorder"),
],
"sociology-a-level-aqa-education-with-theory-methods-adventure-1": [
 ("Forster Education Act (1870)", "State elementary schooling introduced in England"),
 ("Butler Education Act (1944)", "Tripartite system and the 11-plus exam"),
 ("Comprehensivisation begins (1965)", "Circular 10/65 pushes non-selective schools"),
 ("Education Reform Act (1988)", "National Curriculum, league tables, marketisation"),
 ("Academies introduced (2000)", "State schools independent of local authorities"),
 ("Free schools launched (2010)", "Coalition lets parents and groups open schools"),
],
"sociology-a-level-aqa-families-households-adventure-1": [
 ("Married Women's Property Act (1882)", "Wives gain the right to own property"),
 ("Divorce Reform Act (1969)", "'Irretrievable breakdown' makes divorce far easier"),
 ("Children Act (1989)", "Child welfare made paramount in family law"),
 ("Civil Partnership Act (2004)", "Legal recognition for same-sex couples"),
 ("Same-sex marriage legalised (2013)", "Marriage (Same Sex Couples) Act passes"),
],
"sociology-a-level-aqa-global-development-adventure-1": [
 ("Traditional society", "Rostow's stage 1: subsistence farming, limited technology"),
 ("Preconditions for take-off", "Stage 2: infrastructure, trade and elites emerge"),
 ("Take-off", "Stage 3: industrialisation and self-sustained growth begin"),
 ("Drive to maturity", "Stage 4: economy diversifies; technology spreads"),
 ("Age of high mass consumption", "Stage 5: consumer society, like the modern West"),
],
"sociology-a-level-aqa-health-adventure-1": [
 ("Beveridge Report (1942)", "Blueprint for the welfare state attacks the five giants"),
 ("NHS founded (1948)", "Free healthcare at the point of use begins"),
 ("Black Report (1980)", "Documents persistent class inequalities in health"),
 ("Acheson Report (1998)", "Confirms widening health inequalities"),
 ("Marmot Review (2010)", "Links health gaps to the social gradient"),
],
"sociology-a-level-aqa-the-media-adventure-1": [
 ("BBC radio broadcasts begin (1922)", "British broadcasting starts with the wireless"),
 ("BBC television service starts (1936)", "First regular high-definition TV broadcasts"),
 ("ITV launches (1955)", "Commercial television ends the BBC monopoly"),
 ("Sky satellite TV launches (1989)", "Multi-channel era and media conglomeration"),
 ("Facebook founded (2004)", "Social media shifts audiences from passive to active"),
],
"sociology-a-level-aqa-work-poverty-welfare-adventure-1": [
 ("Poor Law Amendment Act (1834)", "Workhouses make relief deliberately harsh"),
 ("Rowntree's York poverty study (1901)", "Scientific poverty line distinguishes primary poverty"),
 ("Liberal reforms: old age pensions (1908)", "First state pensions for the elderly poor"),
 ("Beveridge Report (1942)", "Plan to defeat want, disease, squalor, ignorance, idleness"),
 ("Welfare state launched (1948)", "NHS and national insurance cradle-to-grave system"),
 ("Universal Credit rollout begins (2013)", "Six benefits merged into one payment"),
],
"sociology-a-level-beliefs--secularisation-adventure-1": [
 ("Marx: religion as opium (1844)", "Religion soothes exploitation and delays change"),
 ("Weber: Protestant Ethic (1905)", "Calvinism linked to the spirit of capitalism"),
 ("Durkheim: Elementary Forms (1912)", "Religion as worship of society through the sacred"),
 ("Wilson's secularisation thesis (1966)", "Religion's social significance is declining"),
 ("Stark & Bainbridge: religious market (1985)", "Compensators keep demand for religion constant"),
 ("Davie: believing without belonging (1994)", "Faith persists while churchgoing falls"),
],
"sociology-a-level-beliefs-in-society-adventure-1": [
 ("Church of England established (1534)", "Henry VIII's break with Rome creates a state church"),
 ("Quakers founded (1650s)", "George Fox's movement begins as a radical sect"),
 ("Methodism emerges (1730s)", "Wesley's revival becomes a major denomination"),
 ("Salvation Army founded (1865)", "Booth's mission targets the urban poor"),
 ("Pentecostalism born at Azusa Street (1906)", "Revival launches a global charismatic movement"),
 ("Scientology founded (1954)", "Hubbard's organisation, a classic new religious movement"),
],
"sociology-a-level-crime--deviance-adventure-1": [
 ("Lombroso's 'born criminal' (1876)", "Early biological positivism on criminal types"),
 ("Merton's strain theory (1938)", "Anomie: gap between goals and legitimate means"),
 ("Becker's labelling theory (1963)", "Deviance is behaviour that others label so"),
 ("Foucault: Discipline and Punish (1975)", "Surveillance and self-discipline replace spectacle"),
 ("Lea & Young's left realism (1984)", "Relative deprivation, subculture, marginalisation"),
],
"sociology-a-level-crime--subcultures-adventure-1": [
 ("Thrasher: The Gang (1927)", "Chicago School maps 1,313 youth gangs"),
 ("Cohen: Delinquent Boys (1955)", "Status frustration drives an alternative status hierarchy"),
 ("Cloward & Ohlin (1960)", "Criminal, conflict and retreatist illegitimate opportunities"),
 ("Matza: Delinquency and Drift (1964)", "Youths drift in and out using techniques of neutralisation"),
 ("CCCS: Resistance through Rituals (1975)", "Subcultures as symbolic working-class resistance"),
],
"sociology-a-level-edexcel-education-adventure-1": [
 ("Forster Education Act (1870)", "First state elementary schools in England"),
 ("Balfour Education Act (1902)", "Local education authorities created"),
 ("Butler Education Act (1944)", "Free secondary education; tripartite system"),
 ("Comprehensivisation begins (1965)", "Circular 10/65 promotes non-selective schooling"),
 ("Education Reform Act (1988)", "National Curriculum and league tables arrive"),
 ("Academies Act (2010)", "Mass academisation of English schools begins"),
],
"sociology-a-level-edexcel-families-households-adventure-1": [
 ("Murdock: nuclear family universal (1949)", "Four functions claimed from a 250-society survey"),
 ("Parsons: functional fit (1955)", "Warm bath theory; family fits industrial society"),
 ("Young & Willmott: symmetrical family (1973)", "Joint conjugal roles seen as spreading"),
 ("Oakley: Sociology of Housework (1974)", "Feminist evidence housework remains women's work"),
 ("Giddens: Transformation of Intimacy (1992)", "Pure relationships based on confluent love"),
],
"sociology-a-level-edexcel-globalisation-the-digital-social-world-adventure-1": [
 ("Bretton Woods institutions (1944)", "IMF and World Bank frame the global economy"),
 ("McLuhan coins 'global village' (1962)", "Media shrink the world into one community"),
 ("Berners-Lee proposes the Web (1989)", "The World Wide Web is invented at CERN"),
 ("Facebook founded (2004)", "Social networking goes global"),
 ("iPhone launches (2007)", "Smartphones put the digital world in every pocket"),
 ("TikTok goes international (2017)", "Algorithmic short video reshapes youth culture"),
],
"sociology-a-level-edexcel-social-stratification-differentiation-adventure-1": [
 ("Marx: Capital published (1867)", "Class conflict between bourgeoisie and proletariat"),
 ("Weber: class, status and party (1922)", "Economy and Society adds status and power to class"),
 ("Goldthorpe's class scheme (1980)", "Occupational classes ground UK mobility research"),
 ("Murray on the underclass (1984)", "New Right blames welfare dependency"),
 ("Great British Class Survey (2013)", "Savage's seven classes use Bourdieu's capitals"),
],
"sociology-a-level-edexcel-socialisation-culture-youth-culture-adventure-1": [
 ("Teddy Boys (early 1950s)", "First celebrated post-war British youth subculture"),
 ("Mods and Rockers clash (1964)", "Seaside fights spark Cohen's moral panic study"),
 ("Hippies' Summer of Love (1967)", "Counterculture rejects mainstream values"),
 ("Punk explodes (1976)", "Sex Pistols era of DIY rebellion"),
 ("Acid house rave scene (1988)", "Second Summer of Love alarms media and law"),
 ("Grime emerges (early 2000s)", "London scene goes mainstream with Boy in da Corner (2003)"),
],
"sociology-a-level-education--class-adventure-1": [
 ("Douglas: The Home and the School (1964)", "Parental interest linked to attainment"),
 ("Lacey: Hightown Grammar (1970)", "Streaming produces polarised pupil subcultures"),
 ("Willis: Learning to Labour (1977)", "The lads' counter-school culture leads to working-class jobs"),
 ("Mac an Ghaill: The Making of Men (1994)", "Masculinities and class identities in school"),
 ("Reay: Miseducation (2017)", "Working-class students still get less from education"),
],
"sociology-a-level-functionalism-in-education-adventure-1": [
 ("Comte founds positivist sociology (1838)", "Coins 'sociology'; society studied scientifically"),
 ("Spencer's organic analogy (1876)", "Society compared to a body of interdependent parts"),
 ("Durkheim on moral education (1902)", "School transmits shared norms and social solidarity"),
 ("Davis & Moore: role allocation (1945)", "Stratification sifts people into suitable roles"),
 ("Parsons: school as bridge (1959)", "School moves children from particularistic to universal values"),
],
"sociology-a-level-methods--methodology-adventure-1": [
 ("Choose the research topic", "Interests, funding and values shape what is studied"),
 ("Review the existing literature", "Previous findings sharpen the focus"),
 ("Formulate the hypothesis or aim", "A testable statement guides the design"),
 ("Select method and sample", "Practical, ethical, theoretical factors fix the design"),
 ("Collect the data", "Fieldwork: surveys, interviews or observation"),
 ("Analyse data and report findings", "Results are interpreted and published for scrutiny"),
],
"sociology-a-level-methods-in-context-adventure-1": [
 ("Identify the education issue to research", "The study starts with a focused question in schools"),
 ("Operationalise the key concepts", "Abstract ideas become measurable indicators"),
 ("Negotiate access through gatekeepers", "Heads, teachers and parents must consent"),
 ("Run a pilot study", "A small trial irons out problems with the method"),
 ("Collect data in the school", "Main fieldwork with pupils and teachers"),
 ("Analyse and report the findings", "Results are interpreted with school contexts in mind"),
],
"sociology-a-level-ocr-debates-in-contemporary-society-families-relationships-youth-media-adventure-1": [
 ("An act of deviance occurs", "Cohen's moral panic model starts with an initial event"),
 ("Media exaggerate the threat", "Sensational reporting distorts and amplifies"),
 ("Public concern grows", "Audiences accept the exaggerated picture"),
 ("Moral entrepreneurs demand action", "Campaigners and politicians call for a crackdown"),
 ("Authorities respond with tougher control", "Policing and sentencing intensify"),
 ("Folk devils confirmed; deviance amplified", "Reaction produces more of the labelled deviance"),
],
"sociology-a-level-ocr-education-adventure-1": [
 ("Forster Education Act (1870)", "State elementary schooling begins in England"),
 ("Fisher Education Act (1918)", "School leaving age raised to 14"),
 ("Butler Education Act (1944)", "Tripartite system; free secondary education"),
 ("Leaving age raised to 16 (1972)", "ROSLA keeps pupils in school longer"),
 ("Education Reform Act (1988)", "Marketisation: league tables, National Curriculum"),
 ("Participation age reaches 18 (2015)", "Education or training compulsory to 18 in England"),
],
"sociology-a-level-ocr-globalisation-the-digital-social-world-adventure-1": [
 ("Electric telegraph (1837)", "First near-instant long-distance communication"),
 ("Telephone patented (1876)", "Bell's invention links distant voices"),
 ("ARPANET goes live (1969)", "The internet's military-academic ancestor"),
 ("World Wide Web invented (1989)", "Berners-Lee makes the internet usable for all"),
 ("Facebook founded (2004)", "Social media age of networked selves begins"),
],
"sociology-a-level-ocr-religion-belief-faith-in-contemporary-society-adventure-1": [
 ("Tylor defines animism (1871)", "Primitive Culture launches the anthropology of religion"),
 ("Weber: Protestant Ethic (1905)", "Religious ideas linked to capitalism's rise"),
 ("Niebuhr on denominations (1929)", "Sects cool into denominations within a generation"),
 ("Wilson's secularisation thesis (1966)", "Religion losing social significance in the West"),
 ("Kendal Project published (2005)", "Heelas & Woodhead chart a holistic spiritual turn"),
],
"sociology-a-level-ocr-researching-understanding-social-inequalities-adventure-1": [
 ("Define the research question", "Inequality research starts with a precise question"),
 ("Operationalise the concepts", "Class, gender or ethnicity become measurable indicators"),
 ("Design the questionnaire", "Questions are written to capture the indicators"),
 ("Pilot the questionnaire", "A small trial finds confusing or leading items"),
 ("Administer it to the sample", "Main data collection across the chosen sample"),
 ("Analyse the statistics", "Patterns of inequality are drawn from the data"),
],
"sociology-a-level-ocr-socialisation-culture-identity-adventure-1": [
 ("Primary socialisation in the family", "Infancy: first norms, values and language at home"),
 ("School begins secondary socialisation", "Childhood: hidden curriculum and formal rules"),
 ("Peer group influence peaks", "Adolescence: friends shape identity and status"),
 ("Workplace resocialisation", "Adulthood: occupational norms and identities"),
 ("Later-life role transitions", "Retirement brings new identities and statuses"),
],
"sociology-a-level-sociological-perspectives-adventure-1": [
 ("Comte coins 'sociology' (1838)", "Positivism: society can be studied scientifically"),
 ("Communist Manifesto (1848)", "Marx and Engels set out class conflict theory"),
 ("Durkheim's Suicide (1897)", "Functionalist method: social facts explain rates"),
 ("Weber: Protestant Ethic (1905)", "Interpretivism: meanings drive social action"),
 ("Mead: Mind, Self and Society (1934)", "Foundations of symbolic interactionism published"),
 ("Lyotard: postmodern condition (1979)", "Incredulity toward grand narratives declared"),
],
"sociology-a-level-stratification--differentiation-adventure-1": [
 ("Marx: Capital (1867)", "Class defined by relationship to the means of production"),
 ("Weber: class, status, party (1922)", "Three dimensions of stratification published"),
 ("Davis & Moore (1945)", "Functionalist claim that stratification is necessary"),
 ("Goldthorpe: Affluent Worker study (1968)", "Tests embourgeoisement among Luton car workers"),
 ("NS-SEC adopted (2001)", "Official UK class schema replaces Registrar General's"),
 ("Great British Class Survey (2013)", "Seven-class model based on three capitals"),
],
"sociology-a-level-theory--methods-adventure-1": [
 ("Comte's positivism (1838)", "Sociology proposed as a science of society"),
 ("Durkheim's Suicide (1897)", "First great statistical study of social facts"),
 ("Weber: Economy and Society (1922)", "Verstehen and social action theory systematised"),
 ("Popper: falsification (1934)", "Science advances by testing and refuting theories"),
 ("Glaser & Strauss: grounded theory (1967)", "Theory built up from qualitative data"),
 ("Oakley's feminist interviewing (1981)", "Critique of detached, 'masculine' research methods"),
],

# ===================== SOCIOLOGY GCSE =====================
"sociology-gcse-aqa-sociological-research-methods-adventure-1": [
 ("Choose the topic and aim", "Research starts by deciding what to investigate"),
 ("Write the hypothesis", "A testable prediction focuses the study"),
 ("Select the method and sample", "Questionnaire, interview or observation is chosen"),
 ("Carry out a pilot study", "A small trial checks the method works"),
 ("Collect the main data", "The full study gathers the evidence"),
 ("Analyse data and draw conclusions", "Findings are interpreted against the hypothesis"),
],
"sociology-gcse-aqa-sociological-theories-approaches-adventure-1": [
 ("Communist Manifesto (1848)", "Marx's conflict view of class society"),
 ("Durkheim: Division of Labour (1893)", "Functionalist study of social solidarity"),
 ("Weber: Protestant Ethic (1905)", "Social action: meanings behind behaviour"),
 ("Parsons: The Social System (1951)", "Functionalism systematised in America"),
 ("Becker: Outsiders (1963)", "Interactionist labelling theory published"),
 ("Oakley: Sociology of Housework (1974)", "Feminist sociology challenges the malestream"),
],
"sociology-gcse-aqa-the-sociology-of-crime-deviance-adventure-1": [
 ("Durkheim: crime is inevitable (1895)", "Functionalists argue crime exists in all societies"),
 ("Merton's strain theory (1938)", "Blocked opportunities produce deviant adaptations"),
 ("Cohen: status frustration (1955)", "Boys denied status form delinquent subcultures"),
 ("Becker's labelling theory (1963)", "Deviance is created by society's reaction"),
 ("Heidensohn on gender and crime (1985)", "Feminist account of women's control and conformity"),
],
"sociology-gcse-aqa-the-sociology-of-education-adventure-1": [
 ("Forster Education Act (1870)", "State elementary schools introduced"),
 ("Butler Education Act (1944)", "11-plus exam and the tripartite system"),
 ("Comprehensive schools promoted (1965)", "Circular 10/65 spreads non-selective schooling"),
 ("Education Reform Act (1988)", "National Curriculum, SATs and league tables"),
 ("Academies expansion (2010)", "Academies Act converts schools en masse"),
],
"sociology-gcse-aqa-the-sociology-of-families-adventure-1": [
 ("Married Women's Property Act (1882)", "Wives gain rights over their own property"),
 ("Matrimonial Causes Act (1923)", "Women get equal grounds for divorce"),
 ("Divorce Reform Act (1969)", "Irretrievable breakdown becomes the only ground"),
 ("Child Benefit introduced (1977)", "Payment to mothers replaces family allowance"),
 ("Civil Partnership Act (2004)", "Same-sex couples gain legal recognition"),
 ("Same-sex marriage legalised (2013)", "Marriage opened to all couples in England and Wales"),
],
"sociology-gcse-aqa-the-sociology-of-social-stratification-adventure-1": [
 ("Rowntree's first York study (1899)", "Poverty measured scientifically with a poverty line"),
 ("Registrar General's class scale (1911)", "Official occupational classes introduced"),
 ("Welfare state founded (1948)", "NHS and benefits attack the five giants"),
 ("Townsend: Poverty in the UK (1979)", "Relative deprivation redefines poverty"),
 ("National Minimum Wage (1999)", "Legal wage floor introduced in the UK"),
 ("Great British Class Survey (2013)", "Seven classes mapped from economic, social, cultural capital"),
],
"sociology-gcse-cambridge-igcse-crime-deviance-social-control-adventure-1": [
 ("Crime reported to the police", "The justice process starts with a report or discovery"),
 ("Police investigate and arrest", "Evidence is gathered and a suspect detained"),
 ("Suspect charged", "Prosecutors decide there is a case to answer"),
 ("Trial in court", "Evidence is tested before magistrates or a jury"),
 ("Verdict and sentencing", "Guilt decided; punishment set"),
 ("Sentence served", "Prison, probation or community order carried out"),
],
"sociology-gcse-cambridge-igcse-culture-identity-socialisation-adventure-1": [
 ("Born into a family", "Life begins inside the first agency of socialisation"),
 ("Primary socialisation at home", "Infancy: language, norms and values are learned first"),
 ("Starting school", "Childhood: formal rules and the hidden curriculum"),
 ("Teenage peer groups", "Adolescence: friends and youth culture shape identity"),
 ("First job", "Adulthood: workplace norms demand resocialisation"),
 ("Raising the next generation", "Adults pass culture on, restarting the cycle"),
],
"sociology-gcse-cambridge-igcse-family-adventure-1": [
 ("Matrimonial Causes Act (1857)", "Civil divorce courts first established in England"),
 ("Equal divorce grounds for women (1923)", "Matrimonial Causes Act levels the rules"),
 ("Legal aid introduced (1949)", "Divorce becomes affordable for ordinary people"),
 ("Divorce Reform Act (1969)", "No need to prove fault; divorce rates rise"),
 ("Civil Partnership Act (2004)", "Same-sex couples gain legal recognition"),
 ("No-fault divorce begins (2022)", "Couples divorce without assigning blame"),
],
"sociology-gcse-cambridge-igcse-social-inequality-adventure-1": [
 ("Booth maps London poverty (1889)", "Street-by-street survey shocks Victorian Britain"),
 ("Rowntree's York study (1901)", "Poverty line separates primary and secondary poverty"),
 ("Beveridge Report (1942)", "Plan for the welfare state to fight the five giants"),
 ("Townsend: Poverty in the UK (1979)", "Relative deprivation becomes the key measure"),
 ("Child Poverty Act (2010)", "Targets to cut child poverty written into law"),
],
"sociology-gcse-cambridge-igcse-theory-methods-adventure-1": [
 ("State the aim or hypothesis", "Research begins with a clear, testable focus"),
 ("Choose the method and sample", "Design matches the question, time and budget"),
 ("Pilot the study", "A small-scale trial exposes design flaws"),
 ("Carry out the main data collection", "Surveys, interviews or observations are completed"),
 ("Analyse and evaluate the findings", "Conclusions are drawn and the method assessed"),
],
"sociology-gcse-crime--deviance-adventure-1": [
 ("Crime is committed", "Every crime statistic starts with an actual offence"),
 ("Crime is reported", "Victims or witnesses tell the police; many never do"),
 ("Police record the crime", "Recording rules filter out some reports"),
 ("Offence is detected and solved", "Only a fraction are cleared up with a suspect"),
 ("Offender prosecuted", "The CPS takes the strongest cases to court"),
 ("Conviction enters official statistics", "The end of the funnel; the dark figure is lost"),
],
"sociology-gcse-edexcel-families-adventure-1": [
 ("Murdock: four functions (1949)", "Claims the nuclear family is universal"),
 ("Young & Willmott in Bethnal Green (1957)", "Extended working-class family life documented"),
 ("The Symmetrical Family (1973)", "Joint conjugal roles claimed to be spreading"),
 ("Edgell: Middle-Class Couples (1980)", "Decision-making still dominated by husbands"),
 ("Beanpole families identified (2003)", "Brannen describes long, thin multi-generation families"),
],
"sociology-gcse-edexcel-research-methods-researching-society-adventure-1": [
 ("Choose a research question", "The study starts with something worth investigating"),
 ("Write a hypothesis", "A prediction that the evidence can test"),
 ("Pick method and sampling technique", "Survey, interview or observation; random or quota"),
 ("Run a pilot study", "Small trial improves questions and procedure"),
 ("Gather the main data", "Full fieldwork with the chosen sample"),
 ("Analyse results and conclude", "Data is interpreted; hypothesis accepted or rejected"),
],
"sociology-gcse-edexcel-social-stratification-adventure-1": [
 ("Registrar General's scale (1911)", "Official measurement of class by occupation begins"),
 ("Beveridge Report (1942)", "Blueprint to fight want and inequality"),
 ("Welfare state begins (1948)", "NHS and national insurance launched"),
 ("Equal Pay Act (1970)", "Equal pay for equal work becomes law"),
 ("National Minimum Wage (1999)", "Statutory wage floor introduced"),
 ("Equality Act (2010)", "Protected characteristics consolidated in one law"),
],
"sociology-gcse-edexcel-sociology-basics-key-concepts-processes-adventure-1": [
 ("Comte coins 'sociology' (1838)", "The discipline gets its name and scientific aim"),
 ("Martineau translates Comte (1853)", "Pioneer woman sociologist spreads the new science"),
 ("Marx: Capital (1867)", "Class conflict analysis of capitalism published"),
 ("Durkheim: Rules of Sociological Method (1895)", "Social facts defined; sociology systematised"),
 ("Weber: Protestant Ethic (1905)", "Social action approach takes shape"),
 ("Mills: The Sociological Imagination (1959)", "Private troubles linked to public issues"),
],
"sociology-gcse-education-adventure-1": [
 ("Education Act (1880)", "Schooling made compulsory for ages 5 to 10"),
 ("Butler Education Act (1944)", "Free secondary education and the 11-plus"),
 ("Leaving age raised to 16 (1972)", "ROSLA extends compulsory schooling"),
 ("Education Reform Act (1988)", "National Curriculum and league tables introduced"),
 ("Participation age raised to 18 (2015)", "Education or training compulsory to 18 in England"),
],
"sociology-gcse-family-diversity-adventure-1": [
 ("Divorce Reform Act (1969)", "Easier divorce multiplies lone-parent and blended families"),
 ("First IVF baby born (1978)", "Louise Brown opens new routes to parenthood"),
 ("Adoption and Children Act (2002)", "Unmarried and same-sex couples can adopt"),
 ("Civil Partnership Act (2004)", "Legal status for same-sex relationships"),
 ("Same-sex marriage legalised (2013)", "Marriage equality in England and Wales"),
 ("Opposite-sex civil partnerships (2019)", "Civil partnership extended to all couples"),
],
"sociology-gcse-feminism-perspectives-adventure-1": [
 ("Wollstonecraft's Vindication (1792)", "Founding argument for women's rights and education"),
 ("WSPU suffragettes founded (1903)", "Pankhursts begin militant campaign for the vote"),
 ("Some women win the vote (1918)", "Women over 30 enfranchised in the UK"),
 ("Friedan: The Feminine Mystique (1963)", "Second-wave feminism ignites"),
 ("Equal Pay Act (1970)", "Liberal feminist legal milestone in Britain"),
 ("#MeToo goes viral (2017)", "Digital fourth-wave activism goes global"),
],
"sociology-gcse-functionalism-adventure-1": [
 ("Comte founds positivism (1838)", "Society to be studied like a science"),
 ("Spencer's organic analogy (1876)", "Society works like a body of interdependent organs"),
 ("Durkheim: Division of Labour (1893)", "Solidarity and social facts ground functionalism"),
 ("Davis & Moore on stratification (1945)", "Inequality claimed to be functionally necessary"),
 ("Parsons: The Social System (1951)", "Grand theory of value consensus completed"),
],
"sociology-gcse-interactionism--labelling-theory-adventure-1": [
 ("Cooley: looking-glass self (1902)", "Self-image formed from how others see us"),
 ("Mead: Mind, Self and Society (1934)", "Self develops through role-taking; published posthumously"),
 ("Blumer names symbolic interactionism (1937)", "The perspective gets its label"),
 ("Goffman: Presentation of Self (1959)", "Dramaturgy: life as theatrical performance"),
 ("Becker: Outsiders (1963)", "Labelling theory of deviance set out"),
 ("Pygmalion in the Classroom (1968)", "Rosenthal & Jacobson show the self-fulfilling prophecy"),
],
"sociology-gcse-marxism-basics-adventure-1": [
 ("Marx born in Trier (1818)", "The founder of Marxism begins life in Prussia"),
 ("Marx meets Engels (1844)", "Lifelong partnership starts in Paris"),
 ("Communist Manifesto (1848)", "Workers of the world urged to unite"),
 ("Das Kapital volume 1 (1867)", "Analysis of capitalist exploitation published"),
 ("Marx dies in London (1883)", "Engels continues editing his work"),
 ("Russian Revolution (1917)", "Marxist ideas put into state practice"),
],
"sociology-gcse-media-adventure-1": [
 ("Gutenberg's printing press (c.1440)", "Mass communication becomes possible"),
 ("First British daily newspaper (1702)", "The Daily Courant launches the daily press"),
 ("BBC radio begins (1922)", "Broadcasting enters British homes"),
 ("Coronation televised (1953)", "TV ownership surges across Britain"),
 ("World Wide Web opens up (1991)", "Online media era begins"),
 ("iPhone launches (2007)", "Smartphones make media mobile and constant"),
],
"sociology-gcse-ocr-applied-methods-of-sociological-enquiry-adventure-1": [
 ("Decide the research aim", "The enquiry starts with a clear purpose"),
 ("Form the hypothesis", "A testable statement is written"),
 ("Design the primary research", "Method, sample and questions are planned"),
 ("Pilot the research", "A trial run refines the design"),
 ("Conduct the main research", "Data is collected from the sample"),
 ("Analyse and evaluate the enquiry", "Findings and methods are assessed"),
],
"sociology-gcse-ocr-family-adventure-1": [
 ("Equal divorce grounds (1923)", "Matrimonial Causes Act treats wives equally"),
 ("Divorce Reform Act (1969)", "Irretrievable breakdown becomes the sole ground"),
 ("Children Act (1989)", "The child's welfare made paramount"),
 ("Civil Partnership Act (2004)", "Same-sex partnerships legally recognised"),
 ("Same-sex marriage legalised (2013)", "Marriage equality reached in England and Wales"),
],
"sociology-gcse-ocr-social-differentiation-stratification-adventure-1": [
 ("Great Reform Act (1832)", "Vote extended to middle-class men"),
 ("Second Reform Act (1867)", "Many urban working-class men enfranchised"),
 ("Third Reform Act (1884)", "Rural working-class men gain the vote"),
 ("Women over 30 vote (1918)", "First women enfranchised after suffrage campaigns"),
 ("Equal franchise (1928)", "Women vote at 21 on the same terms as men"),
 ("Voting age lowered to 18 (1969)", "Young adults brought into the electorate"),
],
"sociology-gcse-ocr-socialisation-culture-identity-adventure-1": [
 ("Family: primary socialisation", "Infancy: first norms, values and language at home"),
 ("Nursery and primary school", "Early childhood: formal rules and routines begin"),
 ("Secondary school and peers", "Adolescence: friends and youth culture shape identity"),
 ("Workplace socialisation", "Adulthood: occupational norms are learned"),
 ("Later life and retirement", "Identity adapts to new roles in old age"),
],
"sociology-gcse-ocr-sociological-theories-methods-research-adventure-1": [
 ("Communist Manifesto (1848)", "Marxist conflict theory announced"),
 ("Durkheim's Suicide (1897)", "Landmark positivist study using official statistics"),
 ("Weber: Protestant Ethic (1905)", "Interpretivist focus on meanings"),
 ("Parsons: The Social System (1951)", "Functionalist consensus theory peaks"),
 ("Becker: Outsiders (1963)", "Interactionism and labelling theory rise"),
 ("Lyotard: Postmodern Condition (1979)", "Postmodern doubt about grand theories"),
],
"sociology-gcse-power--politics-adventure-1": [
 ("Magna Carta (1215)", "First limits placed on the monarch's power"),
 ("Bill of Rights (1689)", "Parliament's supremacy over the Crown secured"),
 ("Great Reform Act (1832)", "Franchise begins extending beyond the elite"),
 ("Women over 30 win the vote (1918)", "Suffrage campaigns force political inclusion"),
 ("Universal Declaration of Human Rights (1948)", "Global statement of political rights"),
 ("Human Rights Act (1998)", "European Convention rights written into UK law"),
],
"sociology-gcse-research-methods-adventure-1": [
 ("Choose the topic", "Research begins with what to investigate"),
 ("Write the hypothesis or aim", "A focused, testable statement"),
 ("Select method and sample", "Design matches the question and resources"),
 ("Pilot the study", "Small trial finds problems before the main study"),
 ("Collect the data", "Full fieldwork is carried out"),
 ("Analyse and conclude", "Evidence is weighed against the hypothesis"),
],
"sociology-gcse-sociological-theories-adventure-1": [
 ("Communist Manifesto (1848)", "Marxism: class conflict drives history"),
 ("Durkheim: Division of Labour (1893)", "Functionalism grows from studies of solidarity"),
 ("Weber: Protestant Ethic (1905)", "Social action theory stresses meanings"),
 ("de Beauvoir: The Second Sex (1949)", "Feminist landmark on women as 'Other'"),
 ("Becker: Outsiders (1963)", "Interactionist labelling theory arrives"),
 ("Lyotard: Postmodern Condition (1979)", "Postmodernism rejects grand narratives"),
],

# ===================== SOCIOLOGY IBDP (Social & Cultural Anthropology) =====================
"sociology-ibdp-hl-anthropological-practice-adventure-1": [
 ("Formulate the research question", "Fieldwork starts with a focused anthropological problem"),
 ("Prepare and gain ethical approval", "Literature review, consent plans and permissions"),
 ("Enter the field and build rapport", "The ethnographer settles in and earns trust"),
 ("Participant observation and field notes", "Months of immersion generate the core data"),
 ("Leave the field and analyse the data", "Notes and interviews are coded for patterns"),
 ("Write the ethnography", "Findings become a published account of the culture"),
],
"sociology-ibdp-hl-engaging-with-anthropological-material-adventure-1": [
 ("Malinowski: Argonauts (1922)", "Trobriand fieldwork sets the participant-observation standard"),
 ("Mead: Coming of Age in Samoa (1928)", "Adolescence shown to vary across cultures"),
 ("Evans-Pritchard: The Nuer (1940)", "Classic structural-functionalist ethnography"),
 ("Levi-Strauss: Tristes Tropiques (1955)", "Structuralist reflections from Brazil"),
 ("Geertz: Interpretation of Cultures (1973)", "Thick description redefines the discipline"),
 ("Bourgois: In Search of Respect (1995)", "Urban ethnography of East Harlem crack dealers"),
],
"sociology-ibdp-hl-hl-essay-reflexive-engagement-with-anthropology-adventure-1": [
 ("Choose the area of inquiry", "The essay starts with a focus you care about"),
 ("Select the ethnographic materials", "Suitable sources are gathered for comparison"),
 ("Formulate the research question", "A precise question emerges from the materials"),
 ("Plan the argument outline", "Structure and evidence are mapped before writing"),
 ("Draft the essay with citations", "The argument is written up with reflexive analysis"),
 ("Revise and submit", "Final edit checks word limit and criteria"),
],
"sociology-ibdp-hl-hl-extension-theoretical-perspectives-in-anthropology-adventure-1": [
 ("Tylor's evolutionism (1871)", "Cultures ranked on a single ladder of progress"),
 ("Boas's historical particularism (1896)", "Each culture explained by its own history"),
 ("Malinowski's functionalism (1922)", "Institutions explained by the needs they meet"),
 ("Levi-Strauss's structuralism (1958)", "Universal mental structures beneath culture"),
 ("Geertz's interpretive turn (1973)", "Culture read as a text via thick description"),
 ("Writing Culture critique (1986)", "Postmodern reflexivity questions ethnographic authority"),
],
"sociology-ibdp-hl-internal-assessment-critical-engagement-adventure-1": [
 ("Select the ethnographic account", "The IA starts by choosing a suitable source"),
 ("Summarise the account's key claims", "What the ethnographer says is set out first"),
 ("Examine the methods used", "How the data was gathered is analysed"),
 ("Apply anthropological concepts", "Key concepts frame a critical reading"),
 ("Evaluate strengths and limitations", "The account's authority is critically weighed"),
 ("Write up within the word limit", "The engagement is presented for assessment"),
],
"sociology-ibdp-hl-social-cultural-anthropology-what-is-anthropology?-adventure-1": [
 ("Tylor defines culture (1871)", "Famous 'complex whole' definition founds the field"),
 ("Boas challenges armchair ranking (1896)", "Fieldwork-based cultural relativism emerges"),
 ("Malinowski: Argonauts (1922)", "Participant observation becomes the method"),
 ("Geertz: thick description (1973)", "Interpretive anthropology reads culture as text"),
 ("Writing Culture (1986)", "Reflexive turn questions how ethnography is written"),
],
"sociology-ibdp-sl-anthropological-practice-methods-ethics-adventure-1": [
 ("Design the study and question", "Fieldwork begins with a clear research focus"),
 ("Secure informed consent and ethics", "Participants must agree before research starts"),
 ("Enter the field and build rapport", "Trust makes honest observation possible"),
 ("Collect data: observation and interviews", "Immersion produces field notes and transcripts"),
 ("Analyse and write up the findings", "Data becomes an ethnographic account"),
],
"sociology-ibdp-sl-engaging-with-anthropological-material-ethnographies-adventure-1": [
 ("Malinowski: Argonauts (1922)", "Founding fieldwork ethnography from the Trobriands"),
 ("Evans-Pritchard: The Nuer (1940)", "Classic study of Nuer politics and cattle"),
 ("Chagnon: Yanomamo (1968)", "Controversial 'fierce people' ethnography"),
 ("Bourgois: In Search of Respect (1995)", "Crack dealers studied in East Harlem"),
 ("Boellstorff: Coming of Age in Second Life (2008)", "Digital ethnography of a virtual world"),
],
"sociology-ibdp-sl-internal-assessment-critical-engagement-with-an-ethnographic-account-adventure-1": [
 ("Choose the ethnographic account", "The IA begins with selecting a suitable source"),
 ("Summarise what the ethnographer found", "Key claims are laid out before critique"),
 ("Analyse how the data was collected", "Methods and positionality are examined"),
 ("Critique using anthropological concepts", "Concepts structure the critical engagement"),
 ("Write up and submit", "The finished engagement meets the assessment criteria"),
],
"sociology-ibdp-sl-social-cultural-anthropology-what-is-anthropology?-key-concepts-adventure-1": [
 ("Tylor defines culture (1871)", "The 'complex whole' definition starts the discipline"),
 ("Boas's fieldwork revolution (1896)", "Cultural relativism replaces ranking cultures"),
 ("Malinowski: Argonauts (1922)", "Participant observation becomes the gold standard"),
 ("Benedict: Patterns of Culture (1934)", "Cultures as integrated wholes for a wide public"),
 ("Geertz: thick description (1973)", "Meaning-centred anthropology takes over"),
],

# ===================== SOCIOLOGY KS3 =====================
"sociology-ks3-class--poverty-adventure-1": [
 ("Workhouses set up (1834)", "Poor Law makes help for the poor harsh and feared"),
 ("Rowntree studies York (1901)", "Poverty measured scientifically for the first time"),
 ("Beveridge Report (1942)", "A plan to fight poverty 'from cradle to grave'"),
 ("Welfare state begins (1948)", "NHS and benefits launched for everyone"),
 ("National Minimum Wage (1999)", "A legal lowest wage is introduced"),
],
"sociology-ks3-crime--society-adventure-1": [
 ("Crime is reported", "The justice journey starts when police hear of a crime"),
 ("Police investigate", "Evidence is collected and witnesses interviewed"),
 ("Suspect arrested and charged", "Police name the person they believe responsible"),
 ("Trial in court", "Evidence is tested and a verdict reached"),
 ("Sentence is served", "Punishment such as prison or community work follows"),
],
"sociology-ks3-family--identity-adventure-1": [
 ("Young single adult", "Family life cycle starts with leaving the childhood home"),
 ("Couple forms", "Partnership or marriage creates a new household"),
 ("Family with young children", "Parenthood changes roles and routines"),
 ("Family with teenagers", "Children grow more independent"),
 ("Empty nest", "Children leave home; the couple adjusts"),
 ("Retirement and later life", "Grandparenting and new roles complete the cycle"),
],
"sociology-ks3-gender-roles-adventure-1": [
 ("Suffragettes founded (1903)", "WSPU begins militant campaign for votes for women"),
 ("Women over 30 vote (1918)", "First victory for women's suffrage in the UK"),
 ("Equal voting age (1928)", "Women vote at 21, the same as men"),
 ("Equal Pay Act (1970)", "Equal pay for equal work becomes law"),
 ("Sex Discrimination Act (1975)", "Discrimination at work and school outlawed"),
 ("Equality Act (2010)", "Gender equality laws gathered into one act"),
],
"sociology-ks3-globalisation--culture-adventure-1": [
 ("Electric telegraph (1837)", "Messages first travel faster than people"),
 ("Telephone invented (1876)", "Voices connect across distance"),
 ("Jet passenger travel (1952)", "The Comet shrinks world travel times"),
 ("World Wide Web (1991)", "Information flows globally in seconds"),
 ("Facebook launches (2004)", "Social media connects cultures instantly"),
],
"sociology-ks3-inequality-in-the-uk-adventure-1": [
 ("Some women win the vote (1918)", "A first step against political inequality"),
 ("Race Relations Act (1965)", "First UK law against racial discrimination"),
 ("Equal Pay Act (1970)", "Pay gaps between men and women outlawed"),
 ("Sex Discrimination Act (1975)", "Sex discrimination banned in work and education"),
 ("Disability Discrimination Act (1995)", "Rights for disabled people written into law"),
 ("Equality Act (2010)", "All protected characteristics under one law"),
],
"sociology-ks3-media--religion-adventure-1": [
 ("Printing press (c.1440)", "Books, including Bibles, can be mass-produced"),
 ("First daily newspaper (1702)", "The Daily Courant starts the daily press"),
 ("Cinema arrives (1895)", "Moving pictures become mass entertainment"),
 ("BBC radio begins (1922)", "Broadcasting reaches into British homes"),
 ("BBC television starts (1936)", "Regular TV broadcasts begin"),
 ("World Wide Web (1991)", "Media and beliefs go online"),
],
"sociology-ks3-norms--values-adventure-1": [
 ("A disapproving look", "Mildest sanction: silent disapproval from others"),
 ("A telling-off", "Verbal informal sanction from parents or friends"),
 ("Detention at school", "A formal sanction with limited consequences"),
 ("A fine from a court", "Formal legal punishment hits your money"),
 ("A prison sentence", "The most severe sanction: loss of freedom"),
],
"sociology-ks3-school--education-adventure-1": [
 ("Nursery (ages 3-4)", "Education journey starts with early years play and routines"),
 ("Primary school (ages 5-11)", "Basics of literacy, numeracy and school rules"),
 ("Secondary school (ages 11-16)", "Subject teaching leads towards exams"),
 ("GCSEs at 16", "First major qualifications are sat"),
 ("Sixth form or college (16-18)", "A levels or vocational courses follow"),
 ("University or apprenticeship (18+)", "Higher education or skilled training completes the path"),
],
"sociology-ks3-socialisation-adventure-1": [
 ("Family teaches first norms", "Infancy: primary socialisation begins at home"),
 ("School adds formal rules", "Childhood: secondary socialisation starts"),
 ("Friends matter most as a teenager", "Adolescence: peer group pressure peaks"),
 ("First job teaches work norms", "Adulthood: the workplace resocialises us"),
 ("Passing norms to your own children", "The socialisation cycle starts again"),
],
"sociology-ks3-youth--subcultures-adventure-1": [
 ("Teddy Boys (early 1950s)", "Britain's first famous youth subculture"),
 ("Hippies (1967)", "Summer of Love counterculture spreads"),
 ("Punks (1976)", "DIY rebellion led by the Sex Pistols era"),
 ("Goths (early 1980s)", "Dark post-punk style built around clubs like the Batcave"),
 ("Emo goes mainstream (mid-2000s)", "Internet-era subculture goes global"),
],
}
