#!/bin/bash
# Delete Learn/adventure content built against topics that are NOT on the current spec.
# Verified July 2026 against the awarding bodies own specs:
#   Cambridge History 0470 : China / South Africa / Israelis-Palestinians depth studies WITHDRAWN after 2023
#   CCEA History 4010      : Peace-War-Neutrality (not on spec), Russia 1914-41 (is A-LEVEL), USA 1918-41 (does not exist)
#   Cambridge RS 0490      : all 9 topics were NEVER on the syllabus (real spec = 3 religions x 6 sections)
#   CCEA RS 4610           : Acts of the Apostles (not a unit), Matthew/Mark/Luke (no Luke unit), World Religions (no Buddhism/Hinduism units)
# Correct replacement lessons have already been built. These files now have no hub path.
# Run from the repo root:  bash DELETE-dead-lessons.sh
set -e
cd "$(dirname "$0")/classcraft/adventures"

echo "--- Learn mini-lessons (18) ---"
rm -f "history-gcse-cambridge-igcse-depth-study-china-c1930-c1990-mini-lesson.html" && echo "deleted: history-gcse-cambridge-igcse-depth-study-china-c1930-c1990-mini-lesson.html"
rm -f "history-gcse-cambridge-igcse-depth-study-israelis-palestinians-since-1945-mini-lesson.html" && echo "deleted: history-gcse-cambridge-igcse-depth-study-israelis-palestinians-since-1945-mini-lesson.html"
rm -f "history-gcse-cambridge-igcse-depth-study-south-africa-c1940-c1994-mini-lesson.html" && echo "deleted: history-gcse-cambridge-igcse-depth-study-south-africa-c1940-c1994-mini-lesson.html"
rm -f "history-gcse-ccea-peace-war-neutrality-britain-northern-ireland-ireland-in-wwii-mini-lesson.html" && echo "deleted: history-gcse-ccea-peace-war-neutrality-britain-northern-ireland-ireland-in-wwii-mini-lesson.html"
rm -f "history-gcse-ccea-russia-1914-41-mini-lesson.html" && echo "deleted: history-gcse-ccea-russia-1914-41-mini-lesson.html"
rm -f "history-gcse-ccea-the-usa-1918-41-mini-lesson.html" && echo "deleted: history-gcse-ccea-the-usa-1918-41-mini-lesson.html"
rm -f "religious-studies-gcse-cambridge-igcse-christianity-the-early-church-mini-lesson.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-christianity-the-early-church-mini-lesson.html"
rm -f "religious-studies-gcse-cambridge-igcse-christianity-the-person-of-jesus-christ-mini-lesson.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-christianity-the-person-of-jesus-christ-mini-lesson.html"
rm -f "religious-studies-gcse-cambridge-igcse-christianity-the-teachings-of-jesus-mini-lesson.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-christianity-the-teachings-of-jesus-mini-lesson.html"
rm -f "religious-studies-gcse-cambridge-igcse-islam-the-first-islamic-community-mini-lesson.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-islam-the-first-islamic-community-mini-lesson.html"
rm -f "religious-studies-gcse-cambridge-igcse-islam-the-four-rightly-guided-caliphs-mini-lesson.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-islam-the-four-rightly-guided-caliphs-mini-lesson.html"
rm -f "religious-studies-gcse-cambridge-igcse-islam-the-life-importance-of-the-prophet-muhammad-mini-lesson.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-islam-the-life-importance-of-the-prophet-muhammad-mini-lesson.html"
rm -f "religious-studies-gcse-cambridge-igcse-judaism-the-festivals-mini-lesson.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-judaism-the-festivals-mini-lesson.html"
rm -f "religious-studies-gcse-cambridge-igcse-judaism-the-patriarchs-early-leaders-mini-lesson.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-judaism-the-patriarchs-early-leaders-mini-lesson.html"
rm -f "religious-studies-gcse-cambridge-igcse-judaism-the-prophets-mini-lesson.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-judaism-the-prophets-mini-lesson.html"
rm -f "religious-studies-gcse-ccea-christianity-through-a-study-of-the-acts-of-the-apostles-mini-lesson.html" && echo "deleted: religious-studies-gcse-ccea-christianity-through-a-study-of-the-acts-of-the-apostles-mini-lesson.html"
rm -f "religious-studies-gcse-ccea-christianity-through-a-study-of-the-gospel-of-matthew-mark-luke-mini-lesson.html" && echo "deleted: religious-studies-gcse-ccea-christianity-through-a-study-of-the-gospel-of-matthew-mark-luke-mini-lesson.html"
rm -f "religious-studies-gcse-ccea-world-religions-judaism-islam-buddhism-hinduism-mini-lesson.html" && echo "deleted: religious-studies-gcse-ccea-world-religions-judaism-islam-buddhism-hinduism-mini-lesson.html"

echo
echo "--- older adventure-stage files for the same dead topics (54) ---"
rm -f "history-gcse-cambridge-igcse-depth-study-china-c1930-c1990-adventure-1.html" && echo "deleted: history-gcse-cambridge-igcse-depth-study-china-c1930-c1990-adventure-1.html"
rm -f "history-gcse-cambridge-igcse-depth-study-china-c1930-c1990-adventure-2.html" && echo "deleted: history-gcse-cambridge-igcse-depth-study-china-c1930-c1990-adventure-2.html"
rm -f "history-gcse-cambridge-igcse-depth-study-china-c1930-c1990-adventure-3.html" && echo "deleted: history-gcse-cambridge-igcse-depth-study-china-c1930-c1990-adventure-3.html"
rm -f "history-gcse-cambridge-igcse-depth-study-israelis-palestinians-since-1945-adventure-1.html" && echo "deleted: history-gcse-cambridge-igcse-depth-study-israelis-palestinians-since-1945-adventure-1.html"
rm -f "history-gcse-cambridge-igcse-depth-study-israelis-palestinians-since-1945-adventure-2.html" && echo "deleted: history-gcse-cambridge-igcse-depth-study-israelis-palestinians-since-1945-adventure-2.html"
rm -f "history-gcse-cambridge-igcse-depth-study-israelis-palestinians-since-1945-adventure-3.html" && echo "deleted: history-gcse-cambridge-igcse-depth-study-israelis-palestinians-since-1945-adventure-3.html"
rm -f "history-gcse-cambridge-igcse-depth-study-south-africa-c1940-c1994-adventure-1.html" && echo "deleted: history-gcse-cambridge-igcse-depth-study-south-africa-c1940-c1994-adventure-1.html"
rm -f "history-gcse-cambridge-igcse-depth-study-south-africa-c1940-c1994-adventure-2.html" && echo "deleted: history-gcse-cambridge-igcse-depth-study-south-africa-c1940-c1994-adventure-2.html"
rm -f "history-gcse-cambridge-igcse-depth-study-south-africa-c1940-c1994-adventure-3.html" && echo "deleted: history-gcse-cambridge-igcse-depth-study-south-africa-c1940-c1994-adventure-3.html"
rm -f "history-gcse-ccea-peace-war-neutrality-britain-northern-ireland-ireland-in-wwii-adventure-1.html" && echo "deleted: history-gcse-ccea-peace-war-neutrality-britain-northern-ireland-ireland-in-wwii-adventure-1.html"
rm -f "history-gcse-ccea-peace-war-neutrality-britain-northern-ireland-ireland-in-wwii-adventure-2.html" && echo "deleted: history-gcse-ccea-peace-war-neutrality-britain-northern-ireland-ireland-in-wwii-adventure-2.html"
rm -f "history-gcse-ccea-peace-war-neutrality-britain-northern-ireland-ireland-in-wwii-adventure-3.html" && echo "deleted: history-gcse-ccea-peace-war-neutrality-britain-northern-ireland-ireland-in-wwii-adventure-3.html"
rm -f "history-gcse-ccea-russia-1914-41-adventure-1.html" && echo "deleted: history-gcse-ccea-russia-1914-41-adventure-1.html"
rm -f "history-gcse-ccea-russia-1914-41-adventure-2.html" && echo "deleted: history-gcse-ccea-russia-1914-41-adventure-2.html"
rm -f "history-gcse-ccea-russia-1914-41-adventure-3.html" && echo "deleted: history-gcse-ccea-russia-1914-41-adventure-3.html"
rm -f "history-gcse-ccea-the-usa-1918-41-adventure-1.html" && echo "deleted: history-gcse-ccea-the-usa-1918-41-adventure-1.html"
rm -f "history-gcse-ccea-the-usa-1918-41-adventure-2.html" && echo "deleted: history-gcse-ccea-the-usa-1918-41-adventure-2.html"
rm -f "history-gcse-ccea-the-usa-1918-41-adventure-3.html" && echo "deleted: history-gcse-ccea-the-usa-1918-41-adventure-3.html"
rm -f "religious-studies-gcse-cambridge-igcse-christianity-the-early-church-adventure-1.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-christianity-the-early-church-adventure-1.html"
rm -f "religious-studies-gcse-cambridge-igcse-christianity-the-early-church-adventure-2.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-christianity-the-early-church-adventure-2.html"
rm -f "religious-studies-gcse-cambridge-igcse-christianity-the-early-church-adventure-3.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-christianity-the-early-church-adventure-3.html"
rm -f "religious-studies-gcse-cambridge-igcse-christianity-the-person-of-jesus-christ-adventure-1.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-christianity-the-person-of-jesus-christ-adventure-1.html"
rm -f "religious-studies-gcse-cambridge-igcse-christianity-the-person-of-jesus-christ-adventure-2.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-christianity-the-person-of-jesus-christ-adventure-2.html"
rm -f "religious-studies-gcse-cambridge-igcse-christianity-the-person-of-jesus-christ-adventure-3.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-christianity-the-person-of-jesus-christ-adventure-3.html"
rm -f "religious-studies-gcse-cambridge-igcse-christianity-the-teachings-of-jesus-adventure-1.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-christianity-the-teachings-of-jesus-adventure-1.html"
rm -f "religious-studies-gcse-cambridge-igcse-christianity-the-teachings-of-jesus-adventure-2.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-christianity-the-teachings-of-jesus-adventure-2.html"
rm -f "religious-studies-gcse-cambridge-igcse-christianity-the-teachings-of-jesus-adventure-3.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-christianity-the-teachings-of-jesus-adventure-3.html"
rm -f "religious-studies-gcse-cambridge-igcse-islam-the-first-islamic-community-adventure-1.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-islam-the-first-islamic-community-adventure-1.html"
rm -f "religious-studies-gcse-cambridge-igcse-islam-the-first-islamic-community-adventure-2.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-islam-the-first-islamic-community-adventure-2.html"
rm -f "religious-studies-gcse-cambridge-igcse-islam-the-first-islamic-community-adventure-3.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-islam-the-first-islamic-community-adventure-3.html"
rm -f "religious-studies-gcse-cambridge-igcse-islam-the-four-rightly-guided-caliphs-adventure-1.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-islam-the-four-rightly-guided-caliphs-adventure-1.html"
rm -f "religious-studies-gcse-cambridge-igcse-islam-the-four-rightly-guided-caliphs-adventure-2.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-islam-the-four-rightly-guided-caliphs-adventure-2.html"
rm -f "religious-studies-gcse-cambridge-igcse-islam-the-four-rightly-guided-caliphs-adventure-3.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-islam-the-four-rightly-guided-caliphs-adventure-3.html"
rm -f "religious-studies-gcse-cambridge-igcse-islam-the-life-importance-of-the-prophet-muhammad-adventure-1.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-islam-the-life-importance-of-the-prophet-muhammad-adventure-1.html"
rm -f "religious-studies-gcse-cambridge-igcse-islam-the-life-importance-of-the-prophet-muhammad-adventure-2.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-islam-the-life-importance-of-the-prophet-muhammad-adventure-2.html"
rm -f "religious-studies-gcse-cambridge-igcse-islam-the-life-importance-of-the-prophet-muhammad-adventure-3.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-islam-the-life-importance-of-the-prophet-muhammad-adventure-3.html"
rm -f "religious-studies-gcse-cambridge-igcse-judaism-the-festivals-adventure-1.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-judaism-the-festivals-adventure-1.html"
rm -f "religious-studies-gcse-cambridge-igcse-judaism-the-festivals-adventure-2.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-judaism-the-festivals-adventure-2.html"
rm -f "religious-studies-gcse-cambridge-igcse-judaism-the-festivals-adventure-3.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-judaism-the-festivals-adventure-3.html"
rm -f "religious-studies-gcse-cambridge-igcse-judaism-the-patriarchs-early-leaders-adventure-1.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-judaism-the-patriarchs-early-leaders-adventure-1.html"
rm -f "religious-studies-gcse-cambridge-igcse-judaism-the-patriarchs-early-leaders-adventure-2.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-judaism-the-patriarchs-early-leaders-adventure-2.html"
rm -f "religious-studies-gcse-cambridge-igcse-judaism-the-patriarchs-early-leaders-adventure-3.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-judaism-the-patriarchs-early-leaders-adventure-3.html"
rm -f "religious-studies-gcse-cambridge-igcse-judaism-the-prophets-adventure-1.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-judaism-the-prophets-adventure-1.html"
rm -f "religious-studies-gcse-cambridge-igcse-judaism-the-prophets-adventure-2.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-judaism-the-prophets-adventure-2.html"
rm -f "religious-studies-gcse-cambridge-igcse-judaism-the-prophets-adventure-3.html" && echo "deleted: religious-studies-gcse-cambridge-igcse-judaism-the-prophets-adventure-3.html"
rm -f "religious-studies-gcse-ccea-christianity-through-a-study-of-the-acts-of-the-apostles-adventure-1.html" && echo "deleted: religious-studies-gcse-ccea-christianity-through-a-study-of-the-acts-of-the-apostles-adventure-1.html"
rm -f "religious-studies-gcse-ccea-christianity-through-a-study-of-the-acts-of-the-apostles-adventure-2.html" && echo "deleted: religious-studies-gcse-ccea-christianity-through-a-study-of-the-acts-of-the-apostles-adventure-2.html"
rm -f "religious-studies-gcse-ccea-christianity-through-a-study-of-the-acts-of-the-apostles-adventure-3.html" && echo "deleted: religious-studies-gcse-ccea-christianity-through-a-study-of-the-acts-of-the-apostles-adventure-3.html"
rm -f "religious-studies-gcse-ccea-christianity-through-a-study-of-the-gospel-of-matthew-mark-luke-adventure-1.html" && echo "deleted: religious-studies-gcse-ccea-christianity-through-a-study-of-the-gospel-of-matthew-mark-luke-adventure-1.html"
rm -f "religious-studies-gcse-ccea-christianity-through-a-study-of-the-gospel-of-matthew-mark-luke-adventure-2.html" && echo "deleted: religious-studies-gcse-ccea-christianity-through-a-study-of-the-gospel-of-matthew-mark-luke-adventure-2.html"
rm -f "religious-studies-gcse-ccea-christianity-through-a-study-of-the-gospel-of-matthew-mark-luke-adventure-3.html" && echo "deleted: religious-studies-gcse-ccea-christianity-through-a-study-of-the-gospel-of-matthew-mark-luke-adventure-3.html"
rm -f "religious-studies-gcse-ccea-world-religions-judaism-islam-buddhism-hinduism-adventure-1.html" && echo "deleted: religious-studies-gcse-ccea-world-religions-judaism-islam-buddhism-hinduism-adventure-1.html"
rm -f "religious-studies-gcse-ccea-world-religions-judaism-islam-buddhism-hinduism-adventure-2.html" && echo "deleted: religious-studies-gcse-ccea-world-religions-judaism-islam-buddhism-hinduism-adventure-2.html"
rm -f "religious-studies-gcse-ccea-world-religions-judaism-islam-buddhism-hinduism-adventure-3.html" && echo "deleted: religious-studies-gcse-ccea-world-religions-judaism-islam-buddhism-hinduism-adventure-3.html"

echo
echo "Deleted 18 mini-lessons + 54 adventure files = 72 total."
echo
echo "NOW regenerate the Learn manifest so it matches disk:"
echo "  cd ../.. && python3 -c \"import json,glob,os; json.dump(sorted(os.path.basename(p) for p in glob.glob(classcraft/adventures/*-mini-lesson.html)), open(classcraft/learn-manifest.json,w))\""
echo
echo "NOTE: the adventure-stage files belong to the arcade/adventure stage, which may have its own"
echo "manifest. If the arcade lists topics separately, re-check it for these dead topic slugs."
