#!/usr/bin/env python3
# Run from repo root: python3 check_missing_photos.py
# Prints a list of missing images and their Wikimedia source URLs

import os

SPECIES = [
    ("nature/northern-ireland/red-squirrel.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Red_Squirrel_in_St_James%27s_Park%2C_London_-_Nov_2006_edit.jpg/800px-Red_Squirrel_in_St_James%27s_Park%2C_London_-_Nov_2006_edit.jpg", "Red Squirrel"),
    ("nature/northern-ireland/barn-owl.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tyto_alba_-British_Wildlife_Centre%2C_Surrey%2C_England-8a_%281%29.jpg/800px-Tyto_alba_-British_Wildlife_Centre%2C_Surrey%2C_England-8a_%281%29.jpg", "Barn Owl"),
    ("nature/northern-ireland/irish-hare.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Mountain_Hare_%28Lepus_timidus%29_in_summer_coat.jpg/800px-Mountain_Hare_%28Lepus_timidus%29_in_summer_coat.jpg", "Irish Hare"),
    ("nature/northern-ireland/common-seal.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Phoca_vitulina_Edit.jpg/800px-Phoca_vitulina_Edit.jpg", "Common Seal"),
    ("nature/northern-ireland/swift.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Common_Swift_at_Basildon.jpg/800px-Common_Swift_at_Basildon.jpg", "Common Swift"),
    ("nature/northern-ireland/curlew.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Eurasian_Curlew.jpg/800px-Eurasian_Curlew.jpg", "Curlew"),
    ("nature/northern-ireland/peregrine.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Falco_peregrinus_-_01.jpg/800px-Falco_peregrinus_-_01.jpg", "Peregrine Falcon"),
    ("nature/northern-ireland/brent-goose.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Branta_bernicla_hrota.jpg/800px-Branta_bernicla_hrota.jpg", "Light-bellied Brent Goose"),
    ("nature/northern-ireland/red-kite.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Red_Kite_-_Milvus_milvus.jpg/800px-Red_Kite_-_Milvus_milvus.jpg", "Red Kite"),
    ("nature/northern-ireland/common-lizard.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Zootoca_vivipara_bosc.jpg/800px-Zootoca_vivipara_bosc.jpg", "Common Lizard"),
    ("nature/northern-ireland/pipistrelle.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Pipistrellus_pipistrellus_crop.jpg/800px-Pipistrellus_pipistrellus_crop.jpg", "Common Pipistrelle"),
    ("nature/northern-ireland/grey-heron.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Grey_Heron_%28Ardea_cinerea%29_in_flight_-_Hamina_-_Finland.jpg/800px-Grey_Heron_%28Ardea_cinerea%29_in_flight_-_Hamina_-_Finland.jpg", "Grey Heron"),
    ("nature/northern-ireland/hedgehog.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Erinaceus_europaeus_LC0124.jpg/800px-Erinaceus_europaeus_LC0124.jpg", "Hedgehog"),
    ("nature/northern-ireland/arctic-tern.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Arctic_Tern_in_flight.jpg/800px-Arctic_Tern_in_flight.jpg", "Arctic Tern"),
    ("nature/northern-ireland/water-vole.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Water_vole.jpg/800px-Water_vole.jpg", "Water Vole"),
    ("nature/northern-ireland/bog-cotton.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Eriophorum_angustifolium_a1.jpg/800px-Eriophorum_angustifolium_a1.jpg", "Bog Cotton"),
    ("nature/northern-ireland/heather.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Calluna_vulgaris_-_harilik_kanarbik.jpg/800px-Calluna_vulgaris_-_harilik_kanarbik.jpg", "Heather"),
    ("nature/northern-ireland/yellow-iris.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Iris_pseudacorus_-_20060527.jpg/800px-Iris_pseudacorus_-_20060527.jpg", "Yellow Iris"),
    ("nature/northern-ireland/wood-anemone.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Anemone_nemorosa_LC0303.jpg/800px-Anemone_nemorosa_LC0303.jpg", "Wood Anemone"),
    ("nature/northern-ireland/thrift.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Armeria_maritima_Westkueste_Schottland.jpg/800px-Armeria_maritima_Westkueste_Schottland.jpg", "Thrift"),
    ("nature/northern-ireland/lesser-celandine.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Ficaria_verna_LC0193.jpg/800px-Ficaria_verna_LC0193.jpg", "Lesser Celandine"),
    ("nature/northern-ireland/meadowsweet.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Filipendula_ulmaria_LC0049.jpg/800px-Filipendula_ulmaria_LC0049.jpg", "Meadowsweet"),
    ("nature/northern-ireland/cuckoo-flower.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Cardamine_pratensis_LC0020.jpg/800px-Cardamine_pratensis_LC0020.jpg", "Cuckoo Flower"),
    ("nature/northern-ireland/devils-bit-scabious.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Succisa_pratensis_LC0064.jpg/800px-Succisa_pratensis_LC0064.jpg", "Devil's-bit Scabious"),
    ("nature/northern-ireland/sea-holly.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Eryngium_maritimum_kz.jpg/800px-Eryngium_maritimum_kz.jpg", "Sea Holly"),
    ("nature/northern-ireland/bilberry.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Blueberry_3148.jpg/800px-Blueberry_3148.jpg", "Bilberry"),
    ("nature/northern-ireland/marsh-marigold.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Caltha_palustris_LC0074.jpg/800px-Caltha_palustris_LC0074.jpg", "Marsh Marigold"),
    ("nature/northern-ireland/purple-moor-grass.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Molinia_caerulea_subsp._caerulea_kz02.jpg/800px-Molinia_caerulea_subsp._caerulea_kz02.jpg", "Purple Moor-grass"),
    ("nature/northern-ireland/water-mint.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Mentha_aquatica_LC0292.jpg/800px-Mentha_aquatica_LC0292.jpg", "Water Mint"),
    ("nature/northern-ireland/cross-leaved-heath.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Erica_tetralix_a2.jpg/800px-Erica_tetralix_a2.jpg", "Cross-leaved Heath"),
    ("nature/northern-ireland/fly-agaric.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Amanita_muscaria_3_vliegenzwammen_op_rij.jpg/800px-Amanita_muscaria_3_vliegenzwammen_op_rij.jpg", "Fly Agaric"),
    ("nature/northern-ireland/giant-puffball.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Calvatia.gigantea.jpg/800px-Calvatia.gigantea.jpg", "Giant Puffball"),
    ("nature/northern-ireland/oyster-mushroom.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Oyster_mushroom_%28Pleurotus_ostreatus%29.jpg/800px-Oyster_mushroom_%28Pleurotus_ostreatus%29.jpg", "Oyster Mushroom"),
    ("nature/northern-ireland/waxcap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Cuphophyllus_pratensis_%28Fr.%29_Bon_%281989%29_%2836093671285%29.jpg/800px-Cuphophyllus_pratensis_%28Fr.%29_Bon_%281989%29_%2836093671285%29.jpg", "Meadow Waxcap"),
    ("nature/northern-ireland/blackening-waxcap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Hygrocybe_conica_2009_G1.jpg/800px-Hygrocybe_conica_2009_G1.jpg", "Blackening Waxcap"),
    ("nature/northern-ireland/honey-fungus.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Armillaria_mellea_2012_G2.jpg/800px-Armillaria_mellea_2012_G2.jpg", "Honey Fungus"),
    ("nature/northern-ireland/velvet-shank.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Flammulina_velutipes_1.jpg/800px-Flammulina_velutipes_1.jpg", "Velvet Shank"),
    ("nature/northern-ireland/turkey-tail.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Trametes_versicolor_-_Turkey_Tail.jpg/800px-Trametes_versicolor_-_Turkey_Tail.jpg", "Turkey Tail"),
    ("nature/northern-ireland/earthball.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Scleroderma_citrinum_2009_G2.jpg/800px-Scleroderma_citrinum_2009_G2.jpg", "Common Earthball"),
    ("nature/northern-ireland/jelly-ear.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Auricularia_auricula-judae_2012_G4.jpg/800px-Auricularia_auricula-judae_2012_G4.jpg", "Jelly Ear"),
    ("nature/scotland/red-deer.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/2006_RedDeer_Petrozavodsk.jpg/800px-2006_RedDeer_Petrozavodsk.jpg", "Red Deer"),
    ("nature/scotland/golden-eagle.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Golden_eagle_in_flight_-_5.jpg/800px-Golden_eagle_in_flight_-_5.jpg", "Golden Eagle"),
    ("nature/scotland/osprey.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Osprey_in_flight_%28Andrew_Reding%29.jpg/800px-Osprey_in_flight_%28Andrew_Reding%29.jpg", "Osprey"),
    ("nature/scotland/pine-marten.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Martes_martes-0107.jpg/800px-Martes_martes-0107.jpg", "Pine Marten"),
    ("nature/scotland/puffin.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Atlantic_puffin_42.jpg/800px-Atlantic_puffin_42.jpg", "Atlantic Puffin"),
    ("nature/scotland/capercaillie.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Tetrao_urogallus_-_01.jpg/800px-Tetrao_urogallus_-_01.jpg", "Capercaillie"),
    ("nature/scotland/red-grouse.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/RedGrouse.jpg/800px-RedGrouse.jpg", "Red Grouse"),
    ("nature/scotland/scottish-wildcat.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Scottish_Wildcat_Scottish_Wildlife_Park.jpg/800px-Scottish_Wildcat_Scottish_Wildlife_Park.jpg", "Scottish Wildcat"),
    ("nature/scotland/red-squirrel.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Red_Squirrel_in_St_James%27s_Park%2C_London_-_Nov_2006_edit.jpg/800px-Red_Squirrel_in_St_James%27s_Park%2C_London_-_Nov_2006_edit.jpg", "Red Squirrel"),
    ("nature/scotland/minke-whale.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Minke_Whale_%28NOAA%29.jpg/800px-Minke_Whale_%28NOAA%29.jpg", "Minke Whale"),
    ("nature/scotland/bottlenose-dolphin.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tursiops_truncatus_01.jpg/800px-Tursiops_truncatus_01.jpg", "Bottlenose Dolphin"),
    ("nature/scotland/mountain-hare.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Mountain_Hare_%28Lepus_timidus%29_in_summer_coat.jpg/800px-Mountain_Hare_%28Lepus_timidus%29_in_summer_coat.jpg", "Mountain Hare"),
    ("nature/scotland/common-lizard.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Zootoca_vivipara_bosc.jpg/800px-Zootoca_vivipara_bosc.jpg", "Common Lizard"),
    ("nature/scotland/ptarmigan.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Ptarmigan_%28Lagopus_muta%29_in_summer_plumage_-_cropped.jpg/800px-Ptarmigan_%28Lagopus_muta%29_in_summer_plumage_-_cropped.jpg", "Ptarmigan"),
    ("nature/scotland/atlantic-salmon.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Atlantic_salmon_%28Salmo_salar%29.jpg/800px-Atlantic_salmon_%28Salmo_salar%29.jpg", "Atlantic Salmon"),
    ("nature/scotland/scots-pine.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Scots_Pine_Pinus_sylvestris_Loch_Broom_Highlands.jpg/800px-Scots_Pine_Pinus_sylvestris_Loch_Broom_Highlands.jpg", "Scots Pine"),
    ("nature/scotland/bluebell.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Bluebell_-_geograph.org.uk_-_1412360.jpg/800px-Bluebell_-_geograph.org.uk_-_1412360.jpg", "Bluebell"),
    ("nature/scotland/sundew.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Drosera_rotundifolia_Scawen_1.jpg/800px-Drosera_rotundifolia_Scawen_1.jpg", "Round-leaved Sundew"),
    ("nature/scotland/rowan.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Rowan_Sorbus_aucuparia_Beeren.jpg/800px-Rowan_Sorbus_aucuparia_Beeren.jpg", "Rowan"),
    ("nature/scotland/bog-myrtle.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Myrica_gale_-_bog_myrtle.jpg/800px-Myrica_gale_-_bog_myrtle.jpg", "Bog Myrtle"),
    ("nature/scotland/mountain-avens.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Dryas_octopetala_a1.jpg/800px-Dryas_octopetala_a1.jpg", "Mountain Avens"),
    ("nature/scotland/common-reed.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Phragmites_australis_Biebrza.jpg/800px-Phragmites_australis_Biebrza.jpg", "Common Reed"),
    ("nature/scotland/purple-loosestrife.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Lythrum_salicaria_LC0233.jpg/800px-Lythrum_salicaria_LC0233.jpg", "Purple Loosestrife"),
    ("nature/scotland/tormentil.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Potentilla_erecta_LC0064.jpg/800px-Potentilla_erecta_LC0064.jpg", "Tormentil"),
    ("nature/scotland/crowberry.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Empetrum_nigrum1.jpg/800px-Empetrum_nigrum1.jpg", "Crowberry"),
    ("nature/scotland/cross-leaved-heath.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Erica_tetralix_a2.jpg/800px-Erica_tetralix_a2.jpg", "Cross-leaved Heath"),
    ("nature/scotland/alpine-lady-fern.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Athyrium_distentifolium_a.jpg/800px-Athyrium_distentifolium_a.jpg", "Alpine Lady-fern"),
    ("nature/scotland/wood-sorrel.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Oxalis_acetosella_LC0101.jpg/800px-Oxalis_acetosella_LC0101.jpg", "Wood Sorrel"),
    ("nature/scotland/lesser-twayblade.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Neottia_cordata_060704.jpg/800px-Neottia_cordata_060704.jpg", "Lesser Twayblade"),
    ("nature/scotland/goldenrod.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Solidago_virgaurea_LC0278.jpg/800px-Solidago_virgaurea_LC0278.jpg", "Goldenrod"),
    ("nature/scotland/chanterelle.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Golden_Chanterelle.jpg/800px-Golden_Chanterelle.jpg", "Chanterelle"),
    ("nature/scotland/birch-polypore.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Birch_Polypore_edit.jpg/800px-Birch_Polypore_edit.jpg", "Birch Polypore"),
    ("nature/scotland/amethyst-deceiver.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/2009-10-11_Laccaria_amethystina_%28Huds.%29_Cooke_58993.jpg/800px-2009-10-11_Laccaria_amethystina_%28Huds.%29_Cooke_58993.jpg", "Amethyst Deceiver"),
    ("nature/scotland/birch-bolete.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Leccinum_scabrum_-_Rough-stemmed_Bolete.jpg/800px-Leccinum_scabrum_-_Rough-stemmed_Bolete.jpg", "Brown Birch Bolete"),
    ("nature/scotland/parrot-waxcap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Gliophorus_psittacinus_2.jpg/800px-Gliophorus_psittacinus_2.jpg", "Parrot Waxcap"),
    ("nature/scotland/sulphur-tuft.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Hypholoma_fasciculare_2009_G6.jpg/800px-Hypholoma_fasciculare_2009_G6.jpg", "Sulphur Tuft"),
    ("nature/scotland/hedgehog-mushroom.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Hydnum_repandum_2012_G3.jpg/800px-Hydnum_repandum_2012_G3.jpg", "Hedgehog Mushroom"),
    ("nature/scotland/velvet-bolete.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Suillus_variegatus.jpg/800px-Suillus_variegatus.jpg", "Velvet Bolete"),
    ("nature/scotland/woolly-milkcap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Lactarius_torminosus_2009_G1.jpg/800px-Lactarius_torminosus_2009_G1.jpg", "Woolly Milkcap"),
    ("nature/scotland/pine-spike.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Gomphidius_rutilus_%28Chroogomphus_rutilus%29_2009_G1.jpg/800px-Gomphidius_rutilus_%28Chroogomphus_rutilus%29_2009_G1.jpg", "Pine Spike"),
    ("nature/republic-ireland/white-tailed-eagle.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Haliaeetus_albicilla_-_01.jpg/800px-Haliaeetus_albicilla_-_01.jpg", "White-tailed Eagle"),
    ("nature/republic-ireland/atlantic-salmon.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Atlantic_salmon_%28Salmo_salar%29.jpg/800px-Atlantic_salmon_%28Salmo_salar%29.jpg", "Atlantic Salmon"),
    ("nature/republic-ireland/otter.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Fischotter%2C_Lutra_Lutra.JPG/800px-Fischotter%2C_Lutra_Lutra.JPG", "Eurasian Otter"),
    ("nature/republic-ireland/corncrake.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Corncrake_Crex_crex.jpg/800px-Corncrake_Crex_crex.jpg", "Corncrake"),
    ("nature/republic-ireland/grey-seal.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Grey_seal_%28Halichoerus_grypus%29_2014.jpg/800px-Grey_seal_%28Halichoerus_grypus%29_2014.jpg", "Grey Seal"),
    ("nature/republic-ireland/red-fox.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Vulpes_vulpes_ssp_fulvus.jpg/800px-Vulpes_vulpes_ssp_fulvus.jpg", "Red Fox"),
    ("nature/republic-ireland/badger.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Badger-badger.jpg/800px-Badger-badger.jpg", "Eurasian Badger"),
    ("nature/republic-ireland/painted-lady.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Painted_lady_%28Vanessa_cardui%29.jpg/800px-Painted_lady_%28Vanessa_cardui%29.jpg", "Painted Lady"),
    ("nature/republic-ireland/harbour-porpoise.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Harbour_porpoise.jpg/800px-Harbour_porpoise.jpg", "Harbour Porpoise"),
    ("nature/republic-ireland/red-kite.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Red_Kite_-_Milvus_milvus.jpg/800px-Red_Kite_-_Milvus_milvus.jpg", "Red Kite"),
    ("nature/republic-ireland/common-frog.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Rana_temporaria.jpg/800px-Rana_temporaria.jpg", "Common Frog"),
    ("nature/republic-ireland/swallow.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Hirundo_rustica_-Flickr_-_Lip_Kee.jpg/800px-Hirundo_rustica_-Flickr_-_Lip_Kee.jpg", "Barn Swallow"),
    ("nature/republic-ireland/pine-marten.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Martes_martes-0107.jpg/800px-Martes_martes-0107.jpg", "Pine Marten"),
    ("nature/republic-ireland/whooper-swan.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Whooper_Swans_-_geograph.org.uk_-_1008059.jpg/800px-Whooper_Swans_-_geograph.org.uk_-_1008059.jpg", "Whooper Swan"),
    ("nature/republic-ireland/basking-shark.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Cetorhinus_maximus_by_greg_skomal.JPG/800px-Cetorhinus_maximus_by_greg_skomal.JPG", "Basking Shark"),
    ("nature/republic-ireland/fuchsia.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Fuchsia_magellanica2.jpg/800px-Fuchsia_magellanica2.jpg", "Fuchsia"),
    ("nature/republic-ireland/montbretia.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Crocosmia_x_crocosmiiflora.jpg/800px-Crocosmia_x_crocosmiiflora.jpg", "Montbretia"),
    ("nature/republic-ireland/early-purple-orchid.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Orchis_mascula_LC0366.jpg/800px-Orchis_mascula_LC0366.jpg", "Early Purple Orchid"),
    ("nature/republic-ireland/spring-gentian.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Gentiana_verna_Ois%C3%ADs_2.jpg/800px-Gentiana_verna_Ois%C3%ADs_2.jpg", "Spring Gentian"),
    ("nature/republic-ireland/thrift.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Armeria_maritima_Westkueste_Schottland.jpg/800px-Armeria_maritima_Westkueste_Schottland.jpg", "Thrift"),
    ("nature/republic-ireland/bog-asphodel.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Narthecium_ossifragum_LC0256.jpg/800px-Narthecium_ossifragum_LC0256.jpg", "Bog Asphodel"),
    ("nature/republic-ireland/tormentil.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Potentilla_erecta_LC0064.jpg/800px-Potentilla_erecta_LC0064.jpg", "Tormentil"),
    ("nature/republic-ireland/ragged-robin.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Silene_flos-cuculi_LC0044.jpg/800px-Silene_flos-cuculi_LC0044.jpg", "Ragged Robin"),
    ("nature/republic-ireland/ivy.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Hedera_helix_070103.jpg/800px-Hedera_helix_070103.jpg", "Common Ivy"),
    ("nature/republic-ireland/gorse.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Ulex_europaeus1.jpg/800px-Ulex_europaeus1.jpg", "Gorse"),
    ("nature/republic-ireland/hawthorn.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Hawthorn_-_geograph.org.uk_-_1365015.jpg/800px-Hawthorn_-_geograph.org.uk_-_1365015.jpg", "Hawthorn"),
    ("nature/republic-ireland/sea-campion.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Silene_uniflora_Worthing.jpg/800px-Silene_uniflora_Worthing.jpg", "Sea Campion"),
    ("nature/republic-ireland/primrose.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Primula_vulgaris_LC0073.jpg/800px-Primula_vulgaris_LC0073.jpg", "Primrose"),
    ("nature/republic-ireland/yellow-iris.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Iris_pseudacorus_-_20060527.jpg/800px-Iris_pseudacorus_-_20060527.jpg", "Yellow Flag Iris"),
    ("nature/republic-ireland/maidenhair-fern.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Adiantum_capillus-veneris.jpg/800px-Adiantum_capillus-veneris.jpg", "Maidenhair Fern"),
    ("nature/republic-ireland/death-cap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Amanita_phalloides_1.JPG/800px-Amanita_phalloides_1.JPG", "Death Cap"),
    ("nature/republic-ireland/penny-bun.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Boletus_edulis_IT.jpg/800px-Boletus_edulis_IT.jpg", "Penny Bun (Cep)"),
    ("nature/republic-ireland/earthstar.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Geastrum_triplex_1.jpg/800px-Geastrum_triplex_1.jpg", "Collared Earthstar"),
    ("nature/republic-ireland/velvet-shank.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Flammulina_velutipes_1.jpg/800px-Flammulina_velutipes_1.jpg", "Velvet Shank"),
    ("nature/republic-ireland/scarlet-elf-cup.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Sarcoscypha_coccinea.jpg/800px-Sarcoscypha_coccinea.jpg", "Scarlet Elf Cup"),
    ("nature/republic-ireland/turkey-tail.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Trametes_versicolor_-_Turkey_Tail.jpg/800px-Trametes_versicolor_-_Turkey_Tail.jpg", "Turkey Tail"),
    ("nature/republic-ireland/honey-fungus.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Armillaria_mellea_2012_G2.jpg/800px-Armillaria_mellea_2012_G2.jpg", "Honey Fungus"),
    ("nature/republic-ireland/jelly-ear.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Auricularia_auricula-judae_2012_G4.jpg/800px-Auricularia_auricula-judae_2012_G4.jpg", "Jelly Ear"),
    ("nature/republic-ireland/shaggy-inkcap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Coprinus_comatus_2011_G2.jpg/800px-Coprinus_comatus_2011_G2.jpg", "Shaggy Inkcap"),
    ("nature/republic-ireland/stinkhorn.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Phallus_impudicus_2011_G1.jpg/800px-Phallus_impudicus_2011_G1.jpg", "Common Stinkhorn"),
    ("nature/wales/red-kite.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Red_Kite_-_Milvus_milvus.jpg/800px-Red_Kite_-_Milvus_milvus.jpg", "Red Kite"),
    ("nature/wales/polecat.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Mustela_putorius_-_1700-1880_-_Print_-_Iconographia_Zoologica_-_Special_Collections_University_of_Amsterdam.jpg/800px-Mustela_putorius_-_1700-1880_-_Print_-_Iconographia_Zoologica_-_Special_Collections_University_of_Amsterdam.jpg", "Polecat"),
    ("nature/wales/sea-trout.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Salmo_trutta_Sturm.jpg/800px-Salmo_trutta_Sturm.jpg", "Sewin (Sea Trout)"),
    ("nature/wales/chough.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Pyrrhocorax_pyrrhocorax_-Pembrokeshire%2C_Wales-8.jpg/800px-Pyrrhocorax_pyrrhocorax_-Pembrokeshire%2C_Wales-8.jpg", "Chough"),
    ("nature/wales/horseshoe-bat.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Horseshoe_bat.jpg/800px-Horseshoe_bat.jpg", "Lesser Horseshoe Bat"),
    ("nature/wales/gwyniad.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Gwyniad_fish.jpg/800px-Gwyniad_fish.jpg", "Gwyniad"),
    ("nature/wales/bottlenose-dolphin.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tursiops_truncatus_01.jpg/800px-Tursiops_truncatus_01.jpg", "Bottlenose Dolphin"),
    ("nature/wales/merlin.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Falco_columbarius_-_01.jpg/800px-Falco_columbarius_-_01.jpg", "Merlin"),
    ("nature/wales/grey-seal.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Grey_seal_%28Halichoerus_grypus%29_2014.jpg/800px-Grey_seal_%28Halichoerus_grypus%29_2014.jpg", "Grey Seal"),
    ("nature/wales/common-sandpiper.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/CommonSandpiper.jpg/800px-CommonSandpiper.jpg", "Common Sandpiper"),
    ("nature/wales/slow-worm.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Anguis_fragilis_2.jpg/800px-Anguis_fragilis_2.jpg", "Slow Worm"),
    ("nature/wales/harbour-porpoise.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Harbour_porpoise.jpg/800px-Harbour_porpoise.jpg", "Harbour Porpoise"),
    ("nature/wales/curlew.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Eurasian_Curlew.jpg/800px-Eurasian_Curlew.jpg", "Curlew"),
    ("nature/wales/otter.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Fischotter%2C_Lutra_Lutra.JPG/800px-Fischotter%2C_Lutra_Lutra.JPG", "Eurasian Otter"),
    ("nature/wales/puffin.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Atlantic_puffin_42.jpg/800px-Atlantic_puffin_42.jpg", "Atlantic Puffin"),
    ("nature/wales/snowdon-lily.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Lloydia_serotina_flower.jpg/800px-Lloydia_serotina_flower.jpg", "Snowdon Lily"),
    ("nature/wales/welsh-poppy.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Meconopsis_cambrica.jpg/800px-Meconopsis_cambrica.jpg", "Welsh Poppy"),
    ("nature/wales/grass-of-parnassus.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Parnassia_palustris_LC0083.jpg/800px-Parnassia_palustris_LC0083.jpg", "Grass of Parnassus"),
    ("nature/wales/purple-saxifrage.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Saxifraga_oppositifolia_a1.jpg/800px-Saxifraga_oppositifolia_a1.jpg", "Purple Saxifrage"),
    ("nature/wales/bluebell.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Bluebell_-_geograph.org.uk_-_1412360.jpg/800px-Bluebell_-_geograph.org.uk_-_1412360.jpg", "Bluebell"),
    ("nature/wales/sea-campion.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Silene_uniflora_Worthing.jpg/800px-Silene_uniflora_Worthing.jpg", "Sea Campion"),
    ("nature/wales/early-marsh-orchid.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Dactylorhiza_incarnata_%28LC0292%29.jpg/800px-Dactylorhiza_incarnata_%28LC0292%29.jpg", "Early Marsh Orchid"),
    ("nature/wales/cottongrass.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Eriophorum_vaginatum_Torf.jpg/800px-Eriophorum_vaginatum_Torf.jpg", "Cottongrass"),
    ("nature/wales/wood-anemone.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Anemone_nemorosa_LC0303.jpg/800px-Anemone_nemorosa_LC0303.jpg", "Wood Anemone"),
    ("nature/wales/primrose.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Primula_vulgaris_LC0073.jpg/800px-Primula_vulgaris_LC0073.jpg", "Primrose"),
    ("nature/wales/whorled-caraway.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Carum_verticillatum_Oisterwijk.jpg/800px-Carum_verticillatum_Oisterwijk.jpg", "Whorled Caraway"),
    ("nature/wales/heather.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Calluna_vulgaris_-_harilik_kanarbik.jpg/800px-Calluna_vulgaris_-_harilik_kanarbik.jpg", "Heather"),
    ("nature/wales/gorse.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Ulex_europaeus1.jpg/800px-Ulex_europaeus1.jpg", "Gorse"),
    ("nature/wales/green-spleenwort.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Asplenium_viride_LC0069.jpg/800px-Asplenium_viride_LC0069.jpg", "Green Spleenwort"),
    ("nature/wales/butterfly-orchid.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Platanthera_chlorantha_LC0066.jpg/800px-Platanthera_chlorantha_LC0066.jpg", "Greater Butterfly Orchid"),
    ("nature/wales/chicken-of-woods.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Laetiporus_sulphureus_2015_G1.jpg/800px-Laetiporus_sulphureus_2015_G1.jpg", "Chicken of the Woods"),
    ("nature/wales/beefsteak-fungus.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Fistulina_hepatica_2010_G5.jpg/800px-Fistulina_hepatica_2010_G5.jpg", "Beefsteak Fungus"),
    ("nature/wales/dryads-saddle.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Polyporus_squamosus_2012_G2.jpg/800px-Polyporus_squamosus_2012_G2.jpg", "Dryad's Saddle"),
    ("nature/wales/earth-tongue.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Geoglossum_cookeianum_2009_G1.jpg/800px-Geoglossum_cookeianum_2009_G1.jpg", "Earth Tongue"),
    ("nature/wales/giant-funnel.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Leucopaxillus_giganteus_2009_G2.jpg/800px-Leucopaxillus_giganteus_2009_G2.jpg", "Giant Funnel"),
    ("nature/wales/purple-jellydisc.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Ascocoryne_sarcoides_2009_G1.jpg/800px-Ascocoryne_sarcoides_2009_G1.jpg", "Purple Jellydisc"),
    ("nature/wales/oak-polypore.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Piptoporus_quercinus.jpg/800px-Piptoporus_quercinus.jpg", "Oak Polypore"),
    ("nature/wales/meadow-waxcap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Cuphophyllus_pratensis_%28Fr.%29_Bon_%281989%29_%2836093671285%29.jpg/800px-Cuphophyllus_pratensis_%28Fr.%29_Bon_%281989%29_%2836093671285%29.jpg", "Meadow Waxcap"),
    ("nature/wales/stinkhorn.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Phallus_impudicus_2011_G1.jpg/800px-Phallus_impudicus_2011_G1.jpg", "Common Stinkhorn"),
    ("nature/wales/scarlet-caterpillarclub.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Cordyceps_militaris_2009_G3.jpg/800px-Cordyceps_militaris_2009_G3.jpg", "Scarlet Caterpillarclub"),
    ("nature/north-england/red-squirrel.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Red_Squirrel_in_St_James%27s_Park%2C_London_-_Nov_2006_edit.jpg/800px-Red_Squirrel_in_St_James%27s_Park%2C_London_-_Nov_2006_edit.jpg", "Red Squirrel"),
    ("nature/north-england/golden-plover.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Pluvialis_apricaria_-_01.jpg/800px-Pluvialis_apricaria_-_01.jpg", "Golden Plover"),
    ("nature/north-england/curlew.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Eurasian_Curlew.jpg/800px-Eurasian_Curlew.jpg", "Curlew"),
    ("nature/north-england/short-eared-owl.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Short-eared_Owl_%28Asio_flammeus%29_%2814278511723%29.jpg/800px-Short-eared_Owl_%28Asio_flammeus%29_%2814278511723%29.jpg", "Short-eared Owl"),
    ("nature/north-england/water-vole.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Water_vole.jpg/800px-Water_vole.jpg", "Water Vole"),
    ("nature/north-england/lapwing.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Vanellus_vanellus_in_flight.jpg/800px-Vanellus_vanellus_in_flight.jpg", "Lapwing"),
    ("nature/north-england/brown-hare.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Brown_Hare_%28Lepus_europaeus%29.jpg/800px-Brown_Hare_%28Lepus_europaeus%29.jpg", "Brown Hare"),
    ("nature/north-england/whooper-swan.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Whooper_Swans_-_geograph.org.uk_-_1008059.jpg/800px-Whooper_Swans_-_geograph.org.uk_-_1008059.jpg", "Whooper Swan"),
    ("nature/north-england/adder.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Vipera_berus_LC0124.jpg/800px-Vipera_berus_LC0124.jpg", "Adder"),
    ("nature/north-england/pied-flycatcher.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Ficedula_hypoleuca_-_01.jpg/800px-Ficedula_hypoleuca_-_01.jpg", "Pied Flycatcher"),
    ("nature/north-england/hen-harrier.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Hen_harrier_Circus_cyaneus.jpg/800px-Hen_harrier_Circus_cyaneus.jpg", "Hen Harrier"),
    ("nature/north-england/roe-deer.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Capreolus_capreolus_2_Jojo.jpg/800px-Capreolus_capreolus_2_Jojo.jpg", "Roe Deer"),
    ("nature/north-england/swift.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Common_Swift_at_Basildon.jpg/800px-Common_Swift_at_Basildon.jpg", "Common Swift"),
    ("nature/north-england/peregrine.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Falco_peregrinus_-_01.jpg/800px-Falco_peregrinus_-_01.jpg", "Peregrine Falcon"),
    ("nature/north-england/natterjack-toad.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Epidalea_calamita.jpg/800px-Epidalea_calamita.jpg", "Natterjack Toad"),
    ("nature/north-england/bird-cherry.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Prunus_padus_subsp._padus_Sturm53.jpg/800px-Prunus_padus_subsp._padus_Sturm53.jpg", "Bird Cherry"),
    ("nature/north-england/melancholy-thistle.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Cirsium_heterophyllum_a2.jpg/800px-Cirsium_heterophyllum_a2.jpg", "Melancholy Thistle"),
    ("nature/north-england/mountain-pansy.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Viola_lutea_LC0067.jpg/800px-Viola_lutea_LC0067.jpg", "Mountain Pansy"),
    ("nature/north-england/globeflower.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Trollius_europaeus_LC0088.jpg/800px-Trollius_europaeus_LC0088.jpg", "Globeflower"),
    ("nature/north-england/spring-sandwort.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Minuartia_verna_a.jpg/800px-Minuartia_verna_a.jpg", "Spring Sandwort"),
    ("nature/north-england/birds-eye-primrose.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Primula_farinosa_LC0168.jpg/800px-Primula_farinosa_LC0168.jpg", "Bird's-eye Primrose"),
    ("nature/north-england/grass-of-parnassus.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Parnassia_palustris_LC0083.jpg/800px-Parnassia_palustris_LC0083.jpg", "Grass of Parnassus"),
    ("nature/north-england/purple-saxifrage.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Saxifraga_oppositifolia_a1.jpg/800px-Saxifraga_oppositifolia_a1.jpg", "Purple Saxifrage"),
    ("nature/north-england/sea-lavender.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Limonium_vulgare_Biebrza_2.jpg/800px-Limonium_vulgare_Biebrza_2.jpg", "Common Sea-lavender"),
    ("nature/north-england/rowan.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Rowan_Sorbus_aucuparia_Beeren.jpg/800px-Rowan_Sorbus_aucuparia_Beeren.jpg", "Rowan"),
    ("nature/north-england/heather.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Calluna_vulgaris_-_harilik_kanarbik.jpg/800px-Calluna_vulgaris_-_harilik_kanarbik.jpg", "Heather"),
    ("nature/north-england/great-burnet.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Sanguisorba_officinalis_LC0174.jpg/800px-Sanguisorba_officinalis_LC0174.jpg", "Great Burnet"),
    ("nature/north-england/wood-cranesbill.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Geranium_sylvaticum_LC0237.jpg/800px-Geranium_sylvaticum_LC0237.jpg", "Wood Cranesbill"),
    ("nature/north-england/thrift.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Armeria_maritima_Westkueste_Schottland.jpg/800px-Armeria_maritima_Westkueste_Schottland.jpg", "Thrift"),
    ("nature/north-england/cloudberry.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Rubus_chamaemorus_3.jpg/800px-Rubus_chamaemorus_3.jpg", "Cloudberry"),
    ("nature/north-england/velvet-shank.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Flammulina_velutipes_1.jpg/800px-Flammulina_velutipes_1.jpg", "Velvet Shank"),
    ("nature/north-england/golden-scalycap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Pholiota_squarrosa_2009_G3.jpg/800px-Pholiota_squarrosa_2009_G3.jpg", "Golden Scalycap"),
    ("nature/north-england/giant-puffball.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Calvatia.gigantea.jpg/800px-Calvatia.gigantea.jpg", "Giant Puffball"),
    ("nature/north-england/crimson-waxcap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Hygrocybe_punicea.jpg/800px-Hygrocybe_punicea.jpg", "Crimson Waxcap"),
    ("nature/north-england/fly-agaric.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Amanita_muscaria_3_vliegenzwammen_op_rij.jpg/800px-Amanita_muscaria_3_vliegenzwammen_op_rij.jpg", "Fly Agaric"),
    ("nature/north-england/jelly-ear.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Auricularia_auricula-judae_2012_G4.jpg/800px-Auricularia_auricula-judae_2012_G4.jpg", "Jelly Ear"),
    ("nature/north-england/birch-polypore.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Birch_Polypore_edit.jpg/800px-Birch_Polypore_edit.jpg", "Birch Polypore"),
    ("nature/north-england/chanterelle.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Golden_Chanterelle.jpg/800px-Golden_Chanterelle.jpg", "Chanterelle"),
    ("nature/north-england/sulphur-tuft.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Hypholoma_fasciculare_2009_G6.jpg/800px-Hypholoma_fasciculare_2009_G6.jpg", "Sulphur Tuft"),
    ("nature/north-england/amethyst-deceiver.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/2009-10-11_Laccaria_amethystina_%28Huds.%29_Cooke_58993.jpg/800px-2009-10-11_Laccaria_amethystina_%28Huds.%29_Cooke_58993.jpg", "Amethyst Deceiver"),
    ("nature/midlands-east/bittern.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Eurasian_bittern_%28Botaurus_stellaris%29.jpg/800px-Eurasian_bittern_%28Botaurus_stellaris%29.jpg", "Eurasian Bittern"),
    ("nature/midlands-east/marsh-harrier.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Circus_aeruginosus_-_01.jpg/800px-Circus_aeruginosus_-_01.jpg", "Marsh Harrier"),
    ("nature/midlands-east/crane.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Grus_grus_3_%28Martin_Mecnarowski%29.jpg/800px-Grus_grus_3_%28Martin_Mecnarowski%29.jpg", "Common Crane"),
    ("nature/midlands-east/barn-owl.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tyto_alba_-British_Wildlife_Centre%2C_Surrey%2C_England-8a_%281%29.jpg/800px-Tyto_alba_-British_Wildlife_Centre%2C_Surrey%2C_England-8a_%281%29.jpg", "Barn Owl"),
    ("nature/midlands-east/fen-raft-spider.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Dolomedes_plantarius.jpg/800px-Dolomedes_plantarius.jpg", "Fen Raft Spider"),
    ("nature/midlands-east/red-kite.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Red_Kite_-_Milvus_milvus.jpg/800px-Red_Kite_-_Milvus_milvus.jpg", "Red Kite"),
    ("nature/midlands-east/white-admiral.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/White_admiral_butterfly_%28Limenitis_camilla%29.jpg/800px-White_admiral_butterfly_%28Limenitis_camilla%29.jpg", "White Admiral"),
    ("nature/midlands-east/water-vole.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Water_vole.jpg/800px-Water_vole.jpg", "Water Vole"),
    ("nature/midlands-east/brown-long-eared-bat.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Plecotus_auritus_-_1700-1880_-_Print_-_Iconographia_Zoologica_-_Special_Collections_University_of_Amsterdam.jpg/800px-Plecotus_auritus_-_1700-1880_-_Print_-_Iconographia_Zoologica_-_Special_Collections_University_of_Amsterdam.jpg", "Brown Long-eared Bat"),
    ("nature/midlands-east/common-tern.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Common_tern_%28Sterna_hirundo%29_in_flight.jpg/800px-Common_tern_%28Sterna_hirundo%29_in_flight.jpg", "Common Tern"),
    ("nature/midlands-east/great-crested-newt.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Triturus_cristatus_male_Vlasac.jpg/800px-Triturus_cristatus_male_Vlasac.jpg", "Great Crested Newt"),
    ("nature/midlands-east/brown-hare.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Brown_Hare_%28Lepus_europaeus%29.jpg/800px-Brown_Hare_%28Lepus_europaeus%29.jpg", "Brown Hare"),
    ("nature/midlands-east/stag-beetle.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Lucanus_cervus_qtl5.jpg/800px-Lucanus_cervus_qtl5.jpg", "Stag Beetle"),
    ("nature/midlands-east/osprey.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Osprey_in_flight_%28Andrew_Reding%29.jpg/800px-Osprey_in_flight_%28Andrew_Reding%29.jpg", "Osprey"),
    ("nature/midlands-east/avocet.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Recurvirostra_avosetta_-_01.jpg/800px-Recurvirostra_avosetta_-_01.jpg", "Avocet"),
    ("nature/midlands-east/pasque-flower.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Pulsatilla_vulgaris_LC0019.jpg/800px-Pulsatilla_vulgaris_LC0019.jpg", "Pasque Flower"),
    ("nature/midlands-east/fen-orchid.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Liparis_loeselii.jpg/800px-Liparis_loeselii.jpg", "Fen Orchid"),
    ("nature/midlands-east/yellow-water-lily.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Nuphar_lutea_LC0235.jpg/800px-Nuphar_lutea_LC0235.jpg", "Yellow Water-lily"),
    ("nature/midlands-east/greater-spearwort.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Ranunculus_lingua_LC0093.jpg/800px-Ranunculus_lingua_LC0093.jpg", "Greater Spearwort"),
    ("nature/midlands-east/bluebell.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Bluebell_-_geograph.org.uk_-_1412360.jpg/800px-Bluebell_-_geograph.org.uk_-_1412360.jpg", "Bluebell"),
    ("nature/midlands-east/oxlip.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Primula_elatior_LC0183.jpg/800px-Primula_elatior_LC0183.jpg", "Oxlip"),
    ("nature/midlands-east/marsh-pea.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Lathyrus_palustris_LC0290.jpg/800px-Lathyrus_palustris_LC0290.jpg", "Marsh Pea"),
    ("nature/midlands-east/cowslip.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Primula_veris_LC0057.jpg/800px-Primula_veris_LC0057.jpg", "Cowslip"),
    ("nature/midlands-east/purple-loosestrife.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Lythrum_salicaria_LC0233.jpg/800px-Lythrum_salicaria_LC0233.jpg", "Purple Loosestrife"),
    ("nature/midlands-east/bee-orchid.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Ophrys_apifera_-_Malmsbury.jpg/800px-Ophrys_apifera_-_Malmsbury.jpg", "Bee Orchid"),
    ("nature/midlands-east/water-soldier.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Stratiotes_aloides_LC0299.jpg/800px-Stratiotes_aloides_LC0299.jpg", "Water Soldier"),
    ("nature/midlands-east/common-spotted-orchid.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Dactylorhiza_fuchsii_LC0049.jpg/800px-Dactylorhiza_fuchsii_LC0049.jpg", "Common Spotted Orchid"),
    ("nature/midlands-east/ragged-robin.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Silene_flos-cuculi_LC0044.jpg/800px-Silene_flos-cuculi_LC0044.jpg", "Ragged Robin"),
    ("nature/midlands-east/great-burnet.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Sanguisorba_officinalis_LC0174.jpg/800px-Sanguisorba_officinalis_LC0174.jpg", "Great Burnet"),
    ("nature/midlands-east/tussock-sedge.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Carex_paniculata_kz2.jpg/800px-Carex_paniculata_kz2.jpg", "Greater Tussock Sedge"),
    ("nature/midlands-east/oak-milkcap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Lactarius_quietus_2009_G2.jpg/800px-Lactarius_quietus_2009_G2.jpg", "Oak Milkcap"),
    ("nature/midlands-east/beech-knight.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Tricholoma_scalpturatum_2012_G5.jpg/800px-Tricholoma_scalpturatum_2012_G5.jpg", "Beech Knight"),
    ("nature/midlands-east/penny-bun.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Boletus_edulis_IT.jpg/800px-Boletus_edulis_IT.jpg", "Penny Bun (Cep)"),
    ("nature/midlands-east/parrot-waxcap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Gliophorus_psittacinus_2.jpg/800px-Gliophorus_psittacinus_2.jpg", "Parrot Waxcap"),
    ("nature/midlands-east/earthstar.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Geastrum_triplex_1.jpg/800px-Geastrum_triplex_1.jpg", "Collared Earthstar"),
    ("nature/midlands-east/scarlet-elf-cup.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Sarcoscypha_coccinea.jpg/800px-Sarcoscypha_coccinea.jpg", "Scarlet Elf Cup"),
    ("nature/midlands-east/porcelain-fungus.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Porcelain_Fungus_%28Oudemansiella_mucida%29_%281%29.jpg/800px-Porcelain_Fungus_%28Oudemansiella_mucida%29_%281%29.jpg", "Porcelain Fungus"),
    ("nature/midlands-east/chicken-of-woods.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Laetiporus_sulphureus_2015_G1.jpg/800px-Laetiporus_sulphureus_2015_G1.jpg", "Chicken of the Woods"),
    ("nature/midlands-east/shaggy-inkcap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Coprinus_comatus_2011_G2.jpg/800px-Coprinus_comatus_2011_G2.jpg", "Shaggy Inkcap"),
    ("nature/midlands-east/hares-ear.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Otidea_onotica_2009_G2.jpg/800px-Otidea_onotica_2009_G2.jpg", "Hare's Ear"),
    ("nature/south-england/nightingale.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Luscinia_megarhynchos_-_01.jpg/800px-Luscinia_megarhynchos_-_01.jpg", "Nightingale"),
    ("nature/south-england/dormouse.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Muscardinus_avellanarius_%28cropped%29.jpg/800px-Muscardinus_avellanarius_%28cropped%29.jpg", "Hazel Dormouse"),
    ("nature/south-england/adonis-blue.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Polyommatus_bellargus_male_-_Dorset.jpg/800px-Polyommatus_bellargus_male_-_Dorset.jpg", "Adonis Blue"),
    ("nature/south-england/sand-lizard.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Lacerta_agilis_male.jpg/800px-Lacerta_agilis_male.jpg", "Sand Lizard"),
    ("nature/south-england/smooth-snake.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Coronella_austriaca.jpg/800px-Coronella_austriaca.jpg", "Smooth Snake"),
    ("nature/south-england/turtle-dove.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Streptopelia_turtur_-_01.jpg/800px-Streptopelia_turtur_-_01.jpg", "Turtle Dove"),
    ("nature/south-england/smooth-newt.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Lissotriton_vulgaris_01.jpg/800px-Lissotriton_vulgaris_01.jpg", "Smooth Newt"),
    ("nature/south-england/grey-heron.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Grey_Heron_%28Ardea_cinerea%29_in_flight_-_Hamina_-_Finland.jpg/800px-Grey_Heron_%28Ardea_cinerea%29_in_flight_-_Hamina_-_Finland.jpg", "Grey Heron"),
    ("nature/south-england/silver-spotted-skipper.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Hesperia_comma_male_-_Dorset.jpg/800px-Hesperia_comma_male_-_Dorset.jpg", "Silver-spotted Skipper"),
    ("nature/south-england/roe-deer.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Capreolus_capreolus_2_Jojo.jpg/800px-Capreolus_capreolus_2_Jojo.jpg", "Roe Deer"),
    ("nature/south-england/dartford-warbler.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Dartford_Warbler_%28Sylvia_undata%29.jpg/800px-Dartford_Warbler_%28Sylvia_undata%29.jpg", "Dartford Warbler"),
    ("nature/south-england/white-clawed-crayfish.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Austropotamobius_pallipes.jpg/800px-Austropotamobius_pallipes.jpg", "White-clawed Crayfish"),
    ("nature/south-england/hobby.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Falco_subbuteo_-_01.jpg/800px-Falco_subbuteo_-_01.jpg", "Hobby"),
    ("nature/south-england/bechsteins-bat.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Myotis_bechsteinii_1.jpg/800px-Myotis_bechsteinii_1.jpg", "Bechstein's Bat"),
    ("nature/south-england/spoonbill.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Platalea_leucorodia_Spoonbill_1.jpg/800px-Platalea_leucorodia_Spoonbill_1.jpg", "Spoonbill"),
    ("nature/south-england/early-spider-orchid.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Ophrys_sphegodes_-_Branscombe.jpg/800px-Ophrys_sphegodes_-_Branscombe.jpg", "Early Spider Orchid"),
    ("nature/south-england/wild-gladiolus.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Gladiolus_illyricus.jpg/800px-Gladiolus_illyricus.jpg", "Wild Gladiolus"),
    ("nature/south-england/field-cow-wheat.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Melampyrum_arvense.jpg/800px-Melampyrum_arvense.jpg", "Field Cow-wheat"),
    ("nature/south-england/childing-pink.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Petrorhagia_nanteuilii.jpg/800px-Petrorhagia_nanteuilii.jpg", "Childing Pink"),
    ("nature/south-england/round-headed-rampion.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Phyteuma_orbiculare_LC0063.jpg/800px-Phyteuma_orbiculare_LC0063.jpg", "Round-headed Rampion"),
    ("nature/south-england/man-orchid.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Orchis_anthropophora_LC0126.jpg/800px-Orchis_anthropophora_LC0126.jpg", "Man Orchid"),
    ("nature/south-england/chalk-milkwort.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Polygala_calcarea_LC0024.jpg/800px-Polygala_calcarea_LC0024.jpg", "Chalk Milkwort"),
    ("nature/south-england/sea-kale.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Crambe_maritima_LC0018.jpg/800px-Crambe_maritima_LC0018.jpg", "Sea Kale"),
    ("nature/south-england/yellow-horned-poppy.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Glaucium_flavum_LC0083.jpg/800px-Glaucium_flavum_LC0083.jpg", "Yellow Horned-poppy"),
    ("nature/south-england/pyramidal-orchid.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Anacamptis_pyramidalis_LC0095.jpg/800px-Anacamptis_pyramidalis_LC0095.jpg", "Pyramidal Orchid"),
    ("nature/south-england/sea-holly.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Eryngium_maritimum_kz.jpg/800px-Eryngium_maritimum_kz.jpg", "Sea Holly"),
    ("nature/south-england/bee-orchid.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Ophrys_apifera_-_Malmsbury.jpg/800px-Ophrys_apifera_-_Malmsbury.jpg", "Bee Orchid"),
    ("nature/south-england/lords-and-ladies.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Arum_maculatum_LC0113.jpg/800px-Arum_maculatum_LC0113.jpg", "Lords and Ladies"),
    ("nature/south-england/common-rock-rose.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Helianthemum_nummularium_LC0078.jpg/800px-Helianthemum_nummularium_LC0078.jpg", "Common Rock-rose"),
    ("nature/south-england/devils-bit-scabious.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Succisa_pratensis_LC0064.jpg/800px-Succisa_pratensis_LC0064.jpg", "Devil's-bit Scabious"),
    ("nature/south-england/amethyst-deceiver.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/2009-10-11_Laccaria_amethystina_%28Huds.%29_Cooke_58993.jpg/800px-2009-10-11_Laccaria_amethystina_%28Huds.%29_Cooke_58993.jpg", "Amethyst Deceiver"),
    ("nature/south-england/death-cap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Amanita_phalloides_1.JPG/800px-Amanita_phalloides_1.JPG", "Death Cap"),
    ("nature/south-england/lurid-bolete.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Suillellus_luridus_2009_G5.jpg/800px-Suillellus_luridus_2009_G5.jpg", "Lurid Bolete"),
    ("nature/south-england/snowy-waxcap.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Cuphophyllus_virgineus_2009_G2.jpg/800px-Cuphophyllus_virgineus_2009_G2.jpg", "Snowy Waxcap"),
    ("nature/south-england/honey-fungus.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Armillaria_mellea_2012_G2.jpg/800px-Armillaria_mellea_2012_G2.jpg", "Honey Fungus"),
    ("nature/south-england/penny-bun.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Boletus_edulis_IT.jpg/800px-Boletus_edulis_IT.jpg", "Penny Bun (Cep)"),
    ("nature/south-england/porcelain-fungus.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Porcelain_Fungus_%28Oudemansiella_mucida%29_%281%29.jpg/800px-Porcelain_Fungus_%28Oudemansiella_mucida%29_%281%29.jpg", "Porcelain Fungus"),
    ("nature/south-england/chicken-of-woods.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Laetiporus_sulphureus_2015_G1.jpg/800px-Laetiporus_sulphureus_2015_G1.jpg", "Chicken of the Woods"),
    ("nature/south-england/yellow-stagshorn.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Calocera_viscosa_2009_G2.jpg/800px-Calocera_viscosa_2009_G2.jpg", "Yellow Stagshorn"),
    ("nature/south-england/beefsteak-fungus.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Fistulina_hepatica_2010_G5.jpg/800px-Fistulina_hepatica_2010_G5.jpg", "Beefsteak Fungus"),
]


missing = []
for path, url, name in SPECIES:
    if not os.path.exists(path):
        missing.append((path, url, name))
    else:
        # Check it's a real image not an HTML error page
        with open(path, "rb") as f:
            header = f.read(4)
        is_jpg = header[:3] == b"\xff\xd8\xff"
        is_png = header[:4] == b"\x89PNG"
        if not is_jpg and not is_png:
            missing.append((path, url, f"{name} [CORRUPT]"))

print(f"Missing or corrupt: {len(missing)} / {len(SPECIES)}\n")
for path, url, name in missing:
    print(f"  {name}")
    print(f"    Save to: {path}")
    print(f"    From:    {url}")
    print()
