/* Velvet Elements — canonical dataset (v1)
   One record per element. Price in Velvet Coins = atomic number (n).
   mass: IUPAC standard atomic weight (abridged). Values in [brackets] are the
   mass number of the longest-lived known isotope (no stable isotopes exist).
   group: null = lanthanoid/actinoid (f-block; shown as a dash on cards).
   state: at 25 C. A trailing "*" means predicted, never observed in bulk.
   cat keys: alk alkE trans post met nonm hal nob lan act sup
   art: optional PNG drop-in; cards fall back to a typeset tile if absent. */

const VELVET_ELEMENTS = [
{n:1,  sym:"H",  name:"Hydrogen",     cat:"nonm", group:1,  period:1, mass:"1.008",   state:"gas",    fact:"The most abundant element in the universe — about three-quarters of all ordinary matter."},
{n:2,  sym:"He", name:"Helium",       cat:"nob",  group:18, period:1, mass:"4.003",   state:"gas",    fact:"Discovered in the Sun's spectrum before anyone found it on Earth."},
{n:3,  sym:"Li", name:"Lithium",      cat:"alk",  group:1,  period:2, mass:"6.94",    state:"solid",  fact:"So light it floats on water — while fizzing furiously as it reacts."},
{n:4,  sym:"Be", name:"Beryllium",    cat:"alkE", group:2,  period:2, mass:"9.012",   state:"solid",  fact:"Transparent to X-rays, so it forms the windows of X-ray machines."},
{n:5,  sym:"B",  name:"Boron",        cat:"met",  group:13, period:2, mass:"10.81",   state:"solid",  fact:"Heat-proof borosilicate glass — the lab beaker classic — depends on boron."},
{n:6,  sym:"C",  name:"Carbon",       cat:"nonm", group:14, period:2, mass:"12.011",  state:"solid",  fact:"Forms more compounds than all other elements combined — the backbone of life."},
{n:7,  sym:"N",  name:"Nitrogen",     cat:"nonm", group:15, period:2, mass:"14.007",  state:"gas",    fact:"Makes up 78% of the air you are breathing right now."},
{n:8,  sym:"O",  name:"Oxygen",       cat:"nonm", group:16, period:2, mass:"15.999",  state:"gas",    fact:"Around two-thirds of your body mass is oxygen, mostly locked up in water."},
{n:9,  sym:"F",  name:"Fluorine",     cat:"hal",  group:17, period:2, mass:"18.998",  state:"gas",    fact:"The most reactive element of all — it will even attack glass."},
{n:10, sym:"Ne", name:"Neon",         cat:"nob",  group:18, period:2, mass:"20.180",  state:"gas",    fact:"Glows red-orange in signs, yet forms no stable compounds at all."},
{n:11, sym:"Na", name:"Sodium",       cat:"alk",  group:1,  period:3, mass:"22.990",  state:"solid",  fact:"Stored under oil in the lab because it reacts with moisture in the air."},
{n:12, sym:"Mg", name:"Magnesium",    cat:"alkE", group:2,  period:3, mass:"24.305",  state:"solid",  fact:"Burns so brilliantly white it powered early photographers' flashes."},
{n:13, sym:"Al", name:"Aluminium",    cat:"post", group:13, period:3, mass:"26.982",  state:"solid",  fact:"The most abundant metal in Earth's crust — yet once pricier than gold."},
{n:14, sym:"Si", name:"Silicon",      cat:"met",  group:14, period:3, mass:"28.085",  state:"solid",  fact:"The chip in your phone is carved from one ultra-pure silicon crystal."},
{n:15, sym:"P",  name:"Phosphorus",   cat:"nonm", group:15, period:3, mass:"30.974",  state:"solid",  fact:"First isolated from boiled urine — and its white form glows in the dark."},
{n:16, sym:"S",  name:"Sulfur",       cat:"nonm", group:16, period:3, mass:"32.06",   state:"solid",  fact:"Known since ancient times as brimstone, the yellow stone that burns."},
{n:17, sym:"Cl", name:"Chlorine",     cat:"hal",  group:17, period:3, mass:"35.45",   state:"gas",    fact:"Keeps drinking water and swimming pools safe from microbes worldwide."},
{n:18, sym:"Ar", name:"Argon",        cat:"nob",  group:18, period:3, mass:"39.95",   state:"gas",    fact:"About 1% of the air; its name comes from the Greek for 'lazy'."},
{n:19, sym:"K",  name:"Potassium",    cat:"alk",  group:1,  period:4, mass:"39.098",  state:"solid",  fact:"The first metal ever isolated by electrolysis — Humphry Davy, 1807."},
{n:20, sym:"Ca", name:"Calcium",      cat:"alkE", group:2,  period:4, mass:"40.078",  state:"solid",  fact:"Your skeleton is a store of roughly one kilogram of calcium."},
{n:21, sym:"Sc", name:"Scandium",     cat:"trans",group:3,  period:4, mass:"44.956",  state:"solid",  fact:"Predicted by Mendeleev years before anyone actually discovered it."},
{n:22, sym:"Ti", name:"Titanium",     cat:"trans",group:4,  period:4, mass:"47.867",  state:"solid",  fact:"As strong as many steels at barely half the weight — jets and hip joints."},
{n:23, sym:"V",  name:"Vanadium",     cat:"trans",group:5,  period:4, mass:"50.942",  state:"solid",  fact:"Named after the Norse goddess Vanadis for its beautifully coloured compounds."},
{n:24, sym:"Cr", name:"Chromium",     cat:"trans",group:6,  period:4, mass:"51.996",  state:"solid",  fact:"Gives rubies their red and emeralds their green — the same element, twice."},
{n:25, sym:"Mn", name:"Manganese",    cat:"trans",group:7,  period:4, mass:"54.938",  state:"solid",  fact:"Metal-rich manganese nodules litter the deep ocean floor."},
{n:26, sym:"Fe", name:"Iron",         cat:"trans",group:8,  period:4, mass:"55.845",  state:"solid",  fact:"Earth's core is mostly iron — and its swirling flow powers our magnetic field."},
{n:27, sym:"Co", name:"Cobalt",       cat:"trans",group:9,  period:4, mass:"58.933",  state:"solid",  fact:"Named after the kobold, a mischievous goblin of German mining folklore."},
{n:28, sym:"Ni", name:"Nickel",       cat:"trans",group:10, period:4, mass:"58.693",  state:"solid",  fact:"The American five-cent 'nickel' is actually three-quarters copper."},
{n:29, sym:"Cu", name:"Copper",       cat:"trans",group:11, period:4, mass:"63.546",  state:"solid",  fact:"One of the only coloured metals — and it kills microbes on contact."},
{n:30, sym:"Zn", name:"Zinc",         cat:"trans",group:12, period:4, mass:"65.38",   state:"solid",  fact:"Galvanising: zinc corrodes first so the steel underneath doesn't."},
{n:31, sym:"Ga", name:"Gallium",      cat:"post", group:13, period:4, mass:"69.723",  state:"solid",  fact:"Melts in the palm of your hand — its melting point is just under 30 C."},
{n:32, sym:"Ge", name:"Germanium",    cat:"met",  group:14, period:4, mass:"72.630",  state:"solid",  fact:"Powered the very first transistors before silicon took over the world."},
{n:33, sym:"As", name:"Arsenic",      cat:"met",  group:15, period:4, mass:"74.922",  state:"solid",  fact:"Infamous poison — once used, unwisely, in vivid green Victorian wallpaper."},
{n:34, sym:"Se", name:"Selenium",     cat:"nonm", group:16, period:4, mass:"78.971",  state:"solid",  fact:"Named after the Moon; it conducts better in light, so it ran early photocells."},
{n:35, sym:"Br", name:"Bromine",      cat:"hal",  group:17, period:4, mass:"79.904",  state:"liquid", fact:"One of only two elements ever seen as a liquid at room temperature."},
{n:36, sym:"Kr", name:"Krypton",      cat:"nob",  group:18, period:4, mass:"83.798",  state:"gas",    fact:"From 1960 to 1983, the metre itself was defined by krypton's light."},
{n:37, sym:"Rb", name:"Rubidium",     cat:"alk",  group:1,  period:5, mass:"85.468",  state:"solid",  fact:"So reactive it can burst into flame spontaneously in open air."},
{n:38, sym:"Sr", name:"Strontium",    cat:"alkE", group:2,  period:5, mass:"87.62",   state:"solid",  fact:"The crimson red in fireworks is strontium burning."},
{n:39, sym:"Y",  name:"Yttrium",      cat:"trans",group:3,  period:5, mass:"88.906",  state:"solid",  fact:"Yttrium compounds made the red glow of old colour television screens."},
{n:40, sym:"Zr", name:"Zirconium",    cat:"trans",group:4,  period:5, mass:"91.224",  state:"solid",  fact:"Clads nuclear fuel rods because it barely absorbs neutrons."},
{n:41, sym:"Nb", name:"Niobium",      cat:"trans",group:5,  period:5, mass:"92.906",  state:"solid",  fact:"The superconducting magnets inside MRI scanners rely on niobium alloys."},
{n:42, sym:"Mo", name:"Molybdenum",   cat:"trans",group:6,  period:5, mass:"95.95",   state:"solid",  fact:"A trace nutrient: enzymes that handle nitrogen depend on molybdenum."},
{n:43, sym:"Tc", name:"Technetium",   cat:"trans",group:7,  period:5, mass:"[98]",    state:"solid",  fact:"The first artificial element — it has no stable isotopes at all."},
{n:44, sym:"Ru", name:"Ruthenium",    cat:"trans",group:8,  period:5, mass:"101.07",  state:"solid",  fact:"One of the rarest metals on Earth; it hardens fountain-pen nib tips."},
{n:45, sym:"Rh", name:"Rhodium",      cat:"trans",group:9,  period:5, mass:"102.906", state:"solid",  fact:"Often the priciest of the precious metals — it scrubs car exhaust fumes."},
{n:46, sym:"Pd", name:"Palladium",    cat:"trans",group:10, period:5, mass:"106.42",  state:"solid",  fact:"Can soak up around 900 times its own volume of hydrogen gas."},
{n:47, sym:"Ag", name:"Silver",       cat:"trans",group:11, period:5, mass:"107.868", state:"solid",  fact:"The best electrical conductor of any element — better than copper."},
{n:48, sym:"Cd", name:"Cadmium",      cat:"trans",group:12, period:5, mass:"112.414", state:"solid",  fact:"Cadmium yellow pigment brightened the palettes of Monet and Van Gogh."},
{n:49, sym:"In", name:"Indium",       cat:"post", group:13, period:5, mass:"114.818", state:"solid",  fact:"Named for the indigo line in its spectrum; it coats every touchscreen."},
{n:50, sym:"Sn", name:"Tin",          cat:"post", group:14, period:5, mass:"118.710", state:"solid",  fact:"A 'tin can' is really steel wearing only the thinnest coat of tin."},
{n:51, sym:"Sb", name:"Antimony",     cat:"met",  group:15, period:5, mass:"121.760", state:"solid",  fact:"Ancient Egyptians ground its sulfide into kohl eyeliner."},
{n:52, sym:"Te", name:"Tellurium",    cat:"met",  group:16, period:5, mass:"127.60",  state:"solid",  fact:"Named after the Earth — and the tiniest exposure gives you garlic breath."},
{n:53, sym:"I",  name:"Iodine",       cat:"hal",  group:17, period:5, mass:"126.904", state:"solid",  fact:"Your thyroid can't work without it — the reason salt is often iodised."},
{n:54, sym:"Xe", name:"Xenon",        cat:"nob",  group:18, period:5, mass:"131.293", state:"gas",    fact:"Fires the ion engines that push probes through deep space."},
{n:55, sym:"Cs", name:"Caesium",      cat:"alk",  group:1,  period:6, mass:"132.905", state:"solid",  fact:"One second is officially defined by the ticking of a caesium atom."},
{n:56, sym:"Ba", name:"Barium",       cat:"alkE", group:2,  period:6, mass:"137.327", state:"solid",  fact:"A 'barium meal' makes your digestive system show up on X-rays."},
{n:57, sym:"La", name:"Lanthanum",    cat:"lan",  group:null,period:6, mass:"138.905", state:"solid", fact:"Lanthanum glass gives camera lenses their extra-sharp focus."},
{n:58, sym:"Ce", name:"Cerium",       cat:"lan",  group:null,period:6, mass:"140.116", state:"solid", fact:"The sparking 'flint' in a lighter is mostly cerium alloy."},
{n:59, sym:"Pr", name:"Praseodymium", cat:"lan",  group:null,period:6, mass:"140.908", state:"solid", fact:"Tints welders' goggles to block the searing glare of the torch."},
{n:60, sym:"Nd", name:"Neodymium",    cat:"lan",  group:null,period:6, mass:"144.242", state:"solid", fact:"The strongest permanent magnets — including in your earbuds — are neodymium."},
{n:61, sym:"Pm", name:"Promethium",   cat:"lan",  group:null,period:6, mass:"[145]",   state:"solid", fact:"The only lanthanide with no stable isotope — once used in glowing paint."},
{n:62, sym:"Sm", name:"Samarium",     cat:"lan",  group:null,period:6, mass:"150.36",  state:"solid", fact:"Samarium-cobalt magnets keep their grip even when seriously hot."},
{n:63, sym:"Eu", name:"Europium",     cat:"lan",  group:null,period:6, mass:"151.964", state:"solid", fact:"Makes euro banknotes glow under UV light as an anti-forgery trick."},
{n:64, sym:"Gd", name:"Gadolinium",   cat:"lan",  group:null,period:6, mass:"157.25",  state:"solid", fact:"Injected as a contrast agent to make MRI scans shine brighter."},
{n:65, sym:"Tb", name:"Terbium",      cat:"lan",  group:null,period:6, mass:"158.925", state:"solid", fact:"The brilliant green phosphor in low-energy lamps and displays."},
{n:66, sym:"Dy", name:"Dysprosium",   cat:"lan",  group:null,period:6, mass:"162.500", state:"solid", fact:"Added to wind-turbine magnets so they can survive running hot."},
{n:67, sym:"Ho", name:"Holmium",      cat:"lan",  group:null,period:6, mass:"164.930", state:"solid", fact:"The strongest magnetic pull of any element — but only while sitting inside another magnet's field."},
{n:68, sym:"Er", name:"Erbium",       cat:"lan",  group:null,period:6, mass:"167.259", state:"solid", fact:"Boosts the light signals racing through the internet's fibre-optic cables."},
{n:69, sym:"Tm", name:"Thulium",      cat:"lan",  group:null,period:6, mass:"168.934", state:"solid", fact:"The rarest of the stable rare earths — used in portable X-ray sources."},
{n:70, sym:"Yb", name:"Ytterbium",    cat:"lan",  group:null,period:6, mass:"173.045", state:"solid", fact:"Next-generation atomic clocks keep time with ytterbium atoms."},
{n:71, sym:"Lu", name:"Lutetium",     cat:"lan",  group:null,period:6, mass:"174.967", state:"solid", fact:"The hardest, densest lanthanide — and a modern cancer-targeting medicine."},
{n:72, sym:"Hf", name:"Hafnium",      cat:"trans",group:4,  period:6, mass:"178.49",  state:"solid",  fact:"Named after Copenhagen; it forms the control rods of nuclear submarines."},
{n:73, sym:"Ta", name:"Tantalum",     cat:"trans",group:5,  period:6, mass:"180.948", state:"solid",  fact:"So friendly to the human body it is used for surgical implants."},
{n:74, sym:"W",  name:"Tungsten",     cat:"trans",group:6,  period:6, mass:"183.84",  state:"solid",  fact:"The highest melting point of any metal: 3,422 degrees Celsius."},
{n:75, sym:"Re", name:"Rhenium",      cat:"trans",group:7,  period:6, mass:"186.207", state:"solid",  fact:"One of Earth's rarest elements — found in jet-engine turbine blades."},
{n:76, sym:"Os", name:"Osmium",       cat:"trans",group:8,  period:6, mass:"190.23",  state:"solid",  fact:"The densest naturally occurring element — twice as dense as lead."},
{n:77, sym:"Ir", name:"Iridium",      cat:"trans",group:9,  period:6, mass:"192.217", state:"solid",  fact:"A worldwide iridium-rich layer marks the asteroid strike that ended the dinosaurs."},
{n:78, sym:"Pt", name:"Platinum",     cat:"trans",group:10, period:6, mass:"195.084", state:"solid",  fact:"Until 2019, the kilogram was defined by one platinum-iridium cylinder."},
{n:79, sym:"Au", name:"Gold",         cat:"trans",group:11, period:6, mass:"196.967", state:"solid",  fact:"All the gold ever mined would fit in a cube about 22 metres on a side."},
{n:80, sym:"Hg", name:"Mercury",      cat:"trans",group:12, period:6, mass:"200.592", state:"liquid", fact:"The only metal ever seen as a liquid at room temperature."},
{n:81, sym:"Tl", name:"Thallium",     cat:"post", group:13, period:6, mass:"204.38",  state:"solid",  fact:"Its grim history in crime fiction earned it the name 'the poisoner's poison'."},
{n:82, sym:"Pb", name:"Lead",         cat:"post", group:14, period:6, mass:"207.2",   state:"solid",  fact:"Roman water pipes gave lead its symbol — plumbum, the root of 'plumbing'."},
{n:83, sym:"Bi", name:"Bismuth",      cat:"post", group:15, period:6, mass:"208.980", state:"solid",  fact:"Its 'stable' isotope actually decays — with a half-life a billion times the age of the universe."},
{n:84, sym:"Po", name:"Polonium",     cat:"post", group:16, period:6, mass:"[209]",   state:"solid",  fact:"Discovered by Marie Curie and named after her homeland, Poland."},
{n:85, sym:"At", name:"Astatine",     cat:"hal",  group:17, period:6, mass:"[210]",   state:"solid*", fact:"The rarest natural element — well under 30 grams in the whole crust at any moment."},
{n:86, sym:"Rn", name:"Radon",        cat:"nob",  group:18, period:6, mass:"[222]",   state:"gas",    fact:"A radioactive gas that seeps out of granite bedrock into basements."},
{n:87, sym:"Fr", name:"Francium",     cat:"alk",  group:1,  period:7, mass:"[223]",   state:"solid*", fact:"So short-lived that no one has ever seen a visible lump of it."},
{n:88, sym:"Ra", name:"Radium",       cat:"alkE", group:2,  period:7, mass:"[226]",   state:"solid",  fact:"Once painted onto watch dials to make them glow — with tragic consequences."},
{n:89, sym:"Ac", name:"Actinium",     cat:"act",  group:null,period:7, mass:"[227]",   state:"solid", fact:"Glows an eerie pale blue in the dark from its own radioactivity."},
{n:90, sym:"Th", name:"Thorium",      cat:"act",  group:null,period:7, mass:"232.038", state:"solid", fact:"Named after Thor — and long proposed as an alternative nuclear fuel."},
{n:91, sym:"Pa", name:"Protactinium", cat:"act",  group:null,period:7, mass:"231.036", state:"solid", fact:"Among the rarest and most expensive elements found in nature."},
{n:92, sym:"U",  name:"Uranium",      cat:"act",  group:null,period:7, mass:"238.029", state:"solid", fact:"Fuelled the first nuclear reactors — and makes vintage glass glow green."},
{n:93, sym:"Np", name:"Neptunium",    cat:"act",  group:null,period:7, mass:"[237]",   state:"solid", fact:"The first element beyond uranium, named for the next planet out: Neptune."},
{n:94, sym:"Pu", name:"Plutonium",    cat:"act",  group:null,period:7, mass:"[244]",   state:"solid", fact:"A small sphere of it can power a space probe for decades."},
{n:95, sym:"Am", name:"Americium",    cat:"act",  group:null,period:7, mass:"[243]",   state:"solid", fact:"There is a tiny, safe speck of americium inside most smoke detectors."},
{n:96, sym:"Cm", name:"Curium",       cat:"act",  group:null,period:7, mass:"[247]",   state:"solid", fact:"Named in honour of Marie and Pierre Curie, pioneers of radioactivity."},
{n:97, sym:"Bk", name:"Berkelium",    cat:"act",  group:null,period:7, mass:"[247]",   state:"solid", fact:"Named after Berkeley, California, the city where it was first created."},
{n:98, sym:"Cf", name:"Californium",  cat:"act",  group:null,period:7, mass:"[251]",   state:"solid", fact:"An intense neutron source, used to kick-start nuclear reactors."},
{n:99, sym:"Es", name:"Einsteinium",  cat:"act",  group:null,period:7, mass:"[252]",   state:"solid", fact:"First spotted in the radioactive debris of the first hydrogen-bomb test."},
{n:100,sym:"Fm", name:"Fermium",      cat:"act",  group:null,period:7, mass:"[257]",   state:"solid*",fact:"Found in that same 1952 test debris — named after Enrico Fermi."},
{n:101,sym:"Md", name:"Mendelevium",  cat:"act",  group:null,period:7, mass:"[258]",   state:"solid*",fact:"The first element made literally one atom at a time — named for Mendeleev."},
{n:102,sym:"No", name:"Nobelium",     cat:"act",  group:null,period:7, mass:"[259]",   state:"solid*",fact:"Named after Alfred Nobel, founder of the Nobel Prizes."},
{n:103,sym:"Lr", name:"Lawrencium",   cat:"act",  group:null,period:7, mass:"[266]",   state:"solid*",fact:"Named after Ernest Lawrence, inventor of the cyclotron atom-smasher."},
{n:104,sym:"Rf", name:"Rutherfordium",cat:"trans",group:4,  period:7, mass:"[267]",   state:"solid*", fact:"Named after Ernest Rutherford, the father of nuclear physics."},
{n:105,sym:"Db", name:"Dubnium",      cat:"trans",group:5,  period:7, mass:"[268]",   state:"solid*", fact:"Named after Dubna, the Russian town built around an atom-smasher."},
{n:106,sym:"Sg", name:"Seaborgium",   cat:"trans",group:6,  period:7, mass:"[269]",   state:"solid*", fact:"The first element ever named after a living person: Glenn Seaborg."},
{n:107,sym:"Bh", name:"Bohrium",      cat:"trans",group:7,  period:7, mass:"[270]",   state:"solid*", fact:"Named after Niels Bohr, architect of the modern model of the atom."},
{n:108,sym:"Hs", name:"Hassium",      cat:"trans",group:8,  period:7, mass:"[269]",   state:"solid*", fact:"Named after Hesse, the German state where its discovery lab stands."},
{n:109,sym:"Mt", name:"Meitnerium",   cat:"trans", group:9,  period:7, mass:"[278]",   state:"solid*", fact:"Honours Lise Meitner, co-discoverer of nuclear fission."},
{n:110,sym:"Ds", name:"Darmstadtium", cat:"trans", group:10, period:7, mass:"[281]",   state:"solid*", fact:"Named after Darmstadt, the German city where it was forged atom by atom."},
{n:111,sym:"Rg", name:"Roentgenium",  cat:"trans", group:11, period:7, mass:"[282]",   state:"solid*", fact:"Named after Wilhelm Roentgen, discoverer of X-rays."},
{n:112,sym:"Cn", name:"Copernicium",  cat:"trans", group:12, period:7, mass:"[285]",   state:"liquid*",fact:"Predicted to be liquid at room temperature, like the mercury above it — a relativity effect."},
{n:113,sym:"Nh", name:"Nihonium",     cat:"sup",  group:13, period:7, mass:"[286]",   state:"solid*", fact:"The first element discovered in Asia — nihon means Japan."},
{n:114,sym:"Fl", name:"Flerovium",    cat:"sup",  group:14, period:7, mass:"[289]",   state:"solid*", fact:"Named after Russia's Flerov Laboratory of Nuclear Reactions."},
{n:115,sym:"Mc", name:"Moscovium",    cat:"sup",  group:15, period:7, mass:"[290]",   state:"solid*", fact:"Named after the Moscow region, home of its discovery team."},
{n:116,sym:"Lv", name:"Livermorium",  cat:"sup",  group:16, period:7, mass:"[293]",   state:"solid*", fact:"Named after the Livermore laboratory in California."},
{n:117,sym:"Ts", name:"Tennessine",   cat:"sup",  group:17, period:7, mass:"[294]",   state:"solid*", fact:"Named after Tennessee — only the second element named after a US state."},
{n:118,sym:"Og", name:"Oganesson",    cat:"sup",  group:18, period:7, mass:"[294]",   state:"solid*", fact:"The heaviest known element — and only the second named after a living person."}
];

const VELVET_CATEGORIES = {
  alk:  { label:"Alkali metal",        color:"#ff6b5e" },
  alkE: { label:"Alkaline earth metal",color:"#ffb14d" },
  trans:{ label:"Transition metal",    color:"#6ab7ff" },
  post: { label:"Post-transition metal",color:"#9fb3c8" },
  met:  { label:"Metalloid",           color:"#3fe0c5" },
  nonm: { label:"Reactive nonmetal",   color:"#7dff8a" },
  hal:  { label:"Halogen",             color:"#e8ff6b" },
  nob:  { label:"Noble gas",           color:"#c58bff" },
  lan:  { label:"Lanthanoid",          color:"#ff7ad9" },
  act:  { label:"Actinoid",            color:"#b06bff" },
  sup:  { label:"Superheavy",          color:"#8a8fa8" }
};

function velvetArtPath(el){
  return "assets/elements/" + String(el.n).padStart(3,"0") + "-" + el.sym.toLowerCase() + ".webp";
}
